//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface ActiveAssistant : NSObject
{
    int _MemoryWarningCount;
}

+ (id)activeMonitor;
@property(nonatomic) int MemoryWarningCount; // @synthesize MemoryWarningCount=_MemoryWarningCount;
- (double)getSetarTime;
- (void)setSetarTime:(double)arg1;
- (int)memoryWarningCount;
- (void)handleMemoryWarning;

@end

