//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSMutableDictionary;

@interface ad_loader : NSObject
{
    NSMutableDictionary *_handlers;
}

+ (id)instance;
@property(retain, nonatomic) NSMutableDictionary *handlers; // @synthesize handlers=_handlers;
- (void).cxx_destruct;
- (void)get_ad_async:(id)arg1 cid:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)get_ad_async_cache:(int)arg1 cid:(id)arg2 adverts:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (void)get_margin_sync_cache:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)launchChannel:(int)arg1 channelConfig:(id)arg2;
- (id)init;

@end

