//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface ad_reporter : NSObject
{
}

+ (void)ad_source_clk_report:(id)arg1;
+ (void)ad_source_imp_report:(id)arg1;
+ (void)ad_reportHZ:(id)arg1 action:(id)arg2;
+ (void)ad_reportQK:(id)arg1 action:(id)arg2;
+ (void)ad_reportQK_slotId:(id)arg1 action:(id)arg2;
+ (void)adeaz_clik_ad_report:(id)arg1;
+ (void)adeaz_show_ad_report:(id)arg1;
+ (void)adeaz_download_ad_report:(id)arg1;
+ (void)qukan_nocontent_ad_report:(id)arg1;
+ (void)qukan_click_ad_report:(id)arg1;
+ (void)qukan_show_ad_sucess_report:(id)arg1;
+ (void)qukan_show_ad_report:(id)arg1;
+ (void)qukan_download_ad_failed_report:(id)arg1;
+ (void)qukan_download_ad_report:(id)arg1;
+ (_Bool)randomReport;

@end

