//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface AdeazOSInfo : NSObject
{
}

+ (id)getUser_Agent;
+ (id)device_orientation;
+ (id)device_operator;
+ (id)device_model;
+ (id)screenDensity;
+ (id)app_version;
+ (id)os_name;
+ (id)screenHeight;
+ (id)screenWidth;
+ (id)bundleId;
+ (id)os_version;
+ (id)network;
+ (id)idfa;

@end

