//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSDictionary, NSError, NSMutableDictionary, NSString;
@protocol AdsNativeAdDelegate;

@interface AdsNativeAd : NSObject
{
    NSDictionary *_ads;
    NSMutableDictionary *_params;
    NSError *_error;
    id <AdsNativeAdDelegate> _delegate;
    NSString *_slotid;
    NSString *_requestUrl;
}

@property(copy, nonatomic) NSString *requestUrl; // @synthesize requestUrl=_requestUrl;
@property(copy, nonatomic) NSString *slotid; // @synthesize slotid=_slotid;
@property(nonatomic) __weak id <AdsNativeAdDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSError *error; // @synthesize error=_error;
@property(retain, nonatomic) NSMutableDictionary *params; // @synthesize params=_params;
@property(readonly, nonatomic) NSDictionary *ads; // @synthesize ads=_ads;
- (void).cxx_destruct;
- (void)loadAdisTest:(_Bool)arg1 slotid:(id)arg2;
- (id)initWithSlotId:(id)arg1;

@end

