//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "LCBaseModel.h"

@class NSString;

@interface AdSplashModel : LCBaseModel
{
    _Bool _enable;
    _Bool _push_skip;
    NSString *_appId;
    NSString *_adPositionId;
    long long _request_countdown;
    long long _countdown;
    long long _background_interval;
}

@property(nonatomic) _Bool push_skip; // @synthesize push_skip=_push_skip;
@property(nonatomic) long long background_interval; // @synthesize background_interval=_background_interval;
@property(nonatomic) long long countdown; // @synthesize countdown=_countdown;
@property(nonatomic) long long request_countdown; // @synthesize request_countdown=_request_countdown;
@property(nonatomic) _Bool enable; // @synthesize enable=_enable;
@property(retain, nonatomic) NSString *adPositionId; // @synthesize adPositionId=_adPositionId;
@property(retain, nonatomic) NSString *appId; // @synthesize appId=_appId;
- (void).cxx_destruct;
- (_Bool)isAdSplashEnable;
- (id)initWithAttribute:(id)arg1;

@end

