//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSMutableArray, NSString;

@interface AlertQueue : NSObject
{
    NSString *_aid;
    long long _priorityLevel;
    NSMutableArray *_waitingAlerts;
    NSMutableArray *_belongPages;
}

@property(retain, nonatomic) NSMutableArray *belongPages; // @synthesize belongPages=_belongPages;
@property(retain, nonatomic) NSMutableArray *waitingAlerts; // @synthesize waitingAlerts=_waitingAlerts;
@property(nonatomic) long long priorityLevel; // @synthesize priorityLevel=_priorityLevel;
@property(copy, nonatomic) NSString *aid; // @synthesize aid=_aid;
- (void).cxx_destruct;

@end

