//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSArray, NSString;

@interface APNSUserInfoModel : NSObject
{
    NSString *_title;
    NSString *_body;
    NSString *_tipTitle;
    NSString *_otherTitle;
    NSString *_cancelTitle;
    NSArray *_imgURLs;
    NSString *_jpush_id;
    long long _jpush_jump;
    NSString *_personal_extend;
    NSString *_jpush_type;
    NSString *_messageId;
}

+ (id)modelWithUserInfo:(id)arg1;
@property(copy, nonatomic) NSString *messageId; // @synthesize messageId=_messageId;
@property(retain, nonatomic) NSString *jpush_type; // @synthesize jpush_type=_jpush_type;
@property(copy, nonatomic) NSString *personal_extend; // @synthesize personal_extend=_personal_extend;
@property(nonatomic) long long jpush_jump; // @synthesize jpush_jump=_jpush_jump;
@property(copy, nonatomic) NSString *jpush_id; // @synthesize jpush_id=_jpush_id;
@property(retain, nonatomic) NSArray *imgURLs; // @synthesize imgURLs=_imgURLs;
@property(copy, nonatomic) NSString *cancelTitle; // @synthesize cancelTitle=_cancelTitle;
@property(copy, nonatomic) NSString *otherTitle; // @synthesize otherTitle=_otherTitle;
@property(copy, nonatomic) NSString *tipTitle; // @synthesize tipTitle=_tipTitle;
@property(copy, nonatomic) NSString *body; // @synthesize body=_body;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;
- (id)init;

@end

