//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "NSCoding-Protocol.h"
#import "NSCopying-Protocol.h"

@class NSString;

@interface ArchiveMonitorModel : NSObject <NSCoding, NSCopying>
{
    NSString *_typeTitle;
    NSString *_stuckTime;
    NSString *_CPUString;
    NSString *_ramString;
    NSString *_fpsString;
    NSString *_uploadString;
    NSString *_downloadString;
    NSString *_actiPathString;
    NSString *_traceLoggerString;
    NSString *_memoryWarningString;
    NSString *_stackIDString;
}

+ (id)modelObjectWithDictionary:(id)arg1;
@property(retain, nonatomic) NSString *stackIDString; // @synthesize stackIDString=_stackIDString;
@property(retain, nonatomic) NSString *memoryWarningString; // @synthesize memoryWarningString=_memoryWarningString;
@property(retain, nonatomic) NSString *traceLoggerString; // @synthesize traceLoggerString=_traceLoggerString;
@property(retain, nonatomic) NSString *actiPathString; // @synthesize actiPathString=_actiPathString;
@property(retain, nonatomic) NSString *downloadString; // @synthesize downloadString=_downloadString;
@property(retain, nonatomic) NSString *uploadString; // @synthesize uploadString=_uploadString;
@property(retain, nonatomic) NSString *fpsString; // @synthesize fpsString=_fpsString;
@property(retain, nonatomic) NSString *ramString; // @synthesize ramString=_ramString;
@property(retain, nonatomic) NSString *CPUString; // @synthesize CPUString=_CPUString;
@property(retain, nonatomic) NSString *stuckTime; // @synthesize stuckTime=_stuckTime;
@property(retain, nonatomic) NSString *typeTitle; // @synthesize typeTitle=_typeTitle;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)objectOrNilForKey:(id)arg1 fromDictionary:(id)arg2;
- (id)dictionaryRepresentation;
- (id)initWithDictionary:(id)arg1;

@end

