//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface BFApp : NSObject
{
}

+ (_Bool)isFirstStartForVersion:(id)arg1;
+ (_Bool)isFirstStartForCurrentVersion;
+ (_Bool)isFirstStart;
+ (void)onFirstStartForVersion:(id)arg1 block:(CDUnknownBlockType)arg2;
+ (void)onFirstStartForCurrentVersion:(CDUnknownBlockType)arg1;
+ (void)onFirstStart:(CDUnknownBlockType)arg1;

@end

