//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface BFCryptor : NSObject
{
}

+ (id)AES256DecryptString:(id)arg1 withKey:(id)arg2;
+ (id)AES256EncryptString:(id)arg1 withKey:(id)arg2;
+ (id)AES128DecryptString:(id)arg1 withKey:(id)arg2;
+ (id)AES128EncryptString:(id)arg1 withKey:(id)arg2;
+ (id)AES256DecryptData:(id)arg1 withKey:(id)arg2;
+ (id)AES256EncryptData:(id)arg1 withKey:(id)arg2;
+ (id)AES128DecryptData:(id)arg1 withKey:(id)arg2;
+ (id)AES128EncryptData:(id)arg1 withKey:(id)arg2;
+ (id)SHA512:(id)arg1;
+ (id)SHA256:(id)arg1;
+ (id)SHA1:(id)arg1;
+ (id)MD5:(id)arg1;

@end

