//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface BFPassword : NSObject
{
}

+ (int)countSymbols:(id)arg1;
+ (int)countNumbers:(id)arg1;
+ (int)countUppercaseLetters:(id)arg1;
+ (int)countLowercaseLetters:(id)arg1;
+ (long long)checkPasswordStrength:(id)arg1;

@end

