//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString;

@interface BMChineseSort : NSObject
{
    NSString *_string;
    NSString *_pinYin;
    id _object;
}

+ (id)getFirstLetter2:(id)arg1;
+ (_Bool)isCatipalLetter:(id)arg1;
+ (id)getFirstLetter1:(id)arg1;
+ (id)getFirstLetter:(id)arg1;
+ (id)RemoveSpecialCharacter:(id)arg1;
+ (id)ReturnSortObjectArrar:(id)arg1 key:(id)arg2;
+ (id)sortObjectArray:(id)arg1 Key:(id)arg2;
+ (id)IndexWithArray:(id)arg1 Key:(id)arg2;
+ (id)ReturnSortChineseArrar:(id)arg1;
+ (id)LetterSortArray:(id)arg1;
+ (id)IndexArray:(id)arg1;
+ (id)transformChinese:(id)arg1;
@property(retain, nonatomic) id object; // @synthesize object=_object;
@property(retain, nonatomic) NSString *pinYin; // @synthesize pinYin=_pinYin;
@property(retain, nonatomic) NSString *string; // @synthesize string=_string;
- (void).cxx_destruct;

@end

