//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIButton, UIImageView, UILabel;

@interface BYDeleteBar : UIView
{
    UIImageView *_arrowImgView;
    UILabel *_label;
    UIButton *_sortBtn;
}

@property(retain, nonatomic) UIButton *sortBtn; // @synthesize sortBtn=_sortBtn;
@property(retain, nonatomic) UILabel *label; // @synthesize label=_label;
@property(retain, nonatomic) UIImageView *arrowImgView; // @synthesize arrowImgView=_arrowImgView;
- (void).cxx_destruct;
- (void)startEdit;
- (void)editBtnPressed;
- (void)makeNewBar;
- (id)initWithFrame:(struct CGRect)arg1;

@end

