//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIButton.h>

@class NSMutableArray, NSString, QKChannel, UIImageView, UILongPressGestureRecognizer, UIPanGestureRecognizer, UIView;

@interface BYListItem : UIButton
{
    NSMutableArray *locateView;
    NSMutableArray *topView;
    NSMutableArray *bottomView;
    _Bool _isEditing;
    int _location;
    UIView *_hitTextLabel;
    UIButton *_deleteBtn;
    UIButton *_hiddenBtn;
    UIImageView *_updateBtn;
    NSString *_itemName;
    QKChannel *_channel;
    CDUnknownBlockType _longPressBlock;
    CDUnknownBlockType _operationBlock;
    UIPanGestureRecognizer *_gesture;
    UILongPressGestureRecognizer *_longGesture;
}

@property(nonatomic) _Bool isEditing; // @synthesize isEditing=_isEditing;
@property(retain, nonatomic) UILongPressGestureRecognizer *longGesture; // @synthesize longGesture=_longGesture;
@property(retain, nonatomic) UIPanGestureRecognizer *gesture; // @synthesize gesture=_gesture;
@property(copy, nonatomic) CDUnknownBlockType operationBlock; // @synthesize operationBlock=_operationBlock;
@property(copy, nonatomic) CDUnknownBlockType longPressBlock; // @synthesize longPressBlock=_longPressBlock;
@property(retain, nonatomic) QKChannel *channel; // @synthesize channel=_channel;
@property(copy, nonatomic) NSString *itemName; // @synthesize itemName=_itemName;
@property(nonatomic) int location; // @synthesize location=_location;
@property(retain, nonatomic) UIImageView *updateBtn; // @synthesize updateBtn=_updateBtn;
@property(retain, nonatomic) UIButton *hiddenBtn; // @synthesize hiddenBtn=_hiddenBtn;
@property(retain, nonatomic) UIButton *deleteBtn; // @synthesize deleteBtn=_deleteBtn;
@property(retain, nonatomic) UIView *hitTextLabel; // @synthesize hitTextLabel=_hitTextLabel;
- (void).cxx_destruct;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)animationWithView:(id)arg1 frame:(struct CGRect)arg2;
- (void)animationForWholeView;
- (void)animationForBottomView;
- (void)animationForTopView;
- (unsigned long long)TopViewMaxY;
- (_Bool)whetherInAreaWithArray:(id)arg1 Point:(struct CGPoint)arg2;
- (void)changeFromBottomToTop;
- (void)changeFromTopToBottom;
- (void)pangestureOperation:(id)arg1;
- (void)operationWithoutHidBtn;
- (void)operationWithHidBtn;
- (void)updateButtonStatus;
- (void)sortButtonClick;
- (void)longPress;
- (void)dealloc;

@end

