//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSDate, QKActivityCardModelList, UIView;

@interface CardManager : NSObject
{
    _Bool _is_requset_service_activity;
    _Bool _is_activity_show_finished;
    _Bool _is_first_showedCard;
    _Bool _is_flag;
    _Bool _is_lanuch;
    QKActivityCardModelList *_activityCardModelList;
    UIView *_view;
    NSDate *_lastShowDate;
}

+ (id)manager;
@property(nonatomic) _Bool is_lanuch; // @synthesize is_lanuch=_is_lanuch;
@property(nonatomic) _Bool is_flag; // @synthesize is_flag=_is_flag;
@property(nonatomic) _Bool is_first_showedCard; // @synthesize is_first_showedCard=_is_first_showedCard;
@property(retain, nonatomic) NSDate *lastShowDate; // @synthesize lastShowDate=_lastShowDate;
@property(retain, nonatomic) UIView *view; // @synthesize view=_view;
@property(retain, nonatomic) QKActivityCardModelList *activityCardModelList; // @synthesize activityCardModelList=_activityCardModelList;
@property(nonatomic) _Bool is_activity_show_finished; // @synthesize is_activity_show_finished=_is_activity_show_finished;
@property(nonatomic) _Bool is_requset_service_activity; // @synthesize is_requset_service_activity=_is_requset_service_activity;
- (void).cxx_destruct;
- (id)fileName;
- (void)resetLocalCard;
- (id)fitterOutCard:(id)arg1;
- (id)getLocalCard;
- (id)lastId;
- (void)cacheCard:(id)arg1 current:(id)arg2;
- (id)isExitClipBoardGift;
- (_Bool)isExistActCard;
- (id)viewController;
- (void)showCardActivityList:(id)arg1;
- (void)getActivityCardList;
- (void)getActivityList;
- (void)remark;
- (id)init;

@end

