//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QKBaseViewController.h"

#import "BaseCellProtocol-Protocol.h"
#import "ChannelViewControllerProtocol-Protocol.h"
#import "DislikeModelViewDelegate-Protocol.h"
#import "LCTableViewConfigure-Protocol.h"
#import "QKShortVideoCellDelegate-Protocol.h"
#import "QKVideoCellDelegate-Protocol.h"
#import "ShortVideoPlayViewControllerDelegate-Protocol.h"
#import "UISearchBarDelegate-Protocol.h"

@class LCTableViewManager, NSDate, NSMutableArray, NSMutableDictionary, NSString, NSTimer, QKChannel, QKRefreshModel, QKTrackPoint, UIImageView, UILabel, UISearchBar, UIView;

@interface ChannelViewController : QKBaseViewController <BaseCellProtocol, DislikeModelViewDelegate, LCTableViewConfigure, ShortVideoPlayViewControllerDelegate, QKShortVideoCellDelegate, QKVideoCellDelegate, UISearchBarDelegate, ChannelViewControllerProtocol>
{
    double _oldPanOffsetY;
    long long _op;
    long long _status;
    long long _refresh_num;
    _Bool _bSlot;
    _Bool _bReload;
    _Bool _bCached;
    int _adStatus;
    long long _lastRefreshTime;
    double _historyY;
    _Bool _isScrollUp;
    _Bool _isFristLoad;
    CDUnknownBlockType _handler;
    _Bool _is_loading;
    _Bool _isNeedAPNSAlertView;
    _Bool _isShowHomeItemBadgeNum;
    int _src;
    id _dataSource;
    QKChannel *_model;
    UISearchBar *_searchBar;
    UIView *_tableHeaderView;
    UIView *_tableFooterView;
    QKTrackPoint *_track_point;
    NSDate *_channelStart;
    double _padding;
    QKRefreshModel *_refreshModel;
    NSTimer *_updateTipsTimer;
    UIImageView *_dotView;
    UILabel *_dotCountLabel;
    NSMutableDictionary *_storageLoadMoreData;
    LCTableViewManager *_tableManager;
    NSMutableArray *_sourceData;
    QKChannel *_shortVideoChannelModel;
}

@property(retain, nonatomic) QKChannel *shortVideoChannelModel; // @synthesize shortVideoChannelModel=_shortVideoChannelModel;
@property(retain, nonatomic) NSMutableArray *sourceData; // @synthesize sourceData=_sourceData;
@property(retain, nonatomic) LCTableViewManager *tableManager; // @synthesize tableManager=_tableManager;
@property(retain, nonatomic) NSMutableDictionary *storageLoadMoreData; // @synthesize storageLoadMoreData=_storageLoadMoreData;
@property(retain, nonatomic) UILabel *dotCountLabel; // @synthesize dotCountLabel=_dotCountLabel;
@property(retain, nonatomic) UIImageView *dotView; // @synthesize dotView=_dotView;
@property(retain, nonatomic) NSTimer *updateTipsTimer; // @synthesize updateTipsTimer=_updateTipsTimer;
@property(retain, nonatomic) QKRefreshModel *refreshModel; // @synthesize refreshModel=_refreshModel;
@property(nonatomic) double padding; // @synthesize padding=_padding;
@property(retain, nonatomic) NSDate *channelStart; // @synthesize channelStart=_channelStart;
@property(retain, nonatomic) QKTrackPoint *track_point; // @synthesize track_point=_track_point;
@property(nonatomic) _Bool isShowHomeItemBadgeNum; // @synthesize isShowHomeItemBadgeNum=_isShowHomeItemBadgeNum;
@property(nonatomic) _Bool isNeedAPNSAlertView; // @synthesize isNeedAPNSAlertView=_isNeedAPNSAlertView;
@property(nonatomic) int src; // @synthesize src=_src;
@property(retain, nonatomic) UIView *tableFooterView; // @synthesize tableFooterView=_tableFooterView;
@property(retain, nonatomic) UIView *tableHeaderView; // @synthesize tableHeaderView=_tableHeaderView;
@property(retain, nonatomic) UISearchBar *searchBar; // @synthesize searchBar=_searchBar;
@property(nonatomic) _Bool is_loading; // @synthesize is_loading=_is_loading;
@property(retain, nonatomic) QKChannel *model; // @synthesize model=_model;
@property(retain, nonatomic) id dataSource; // @synthesize dataSource=_dataSource;
- (void).cxx_destruct;
- (void)timerAction;
- (void)stopTimer;
- (void)configUpdateTipsTimer;
- (void)hideToolBar:(_Bool)arg1;
- (void)dislikeModelViewDismiss:(double)arg1;
- (void)didDeleteDislikeContents:(id)arg1;
- (void)playVCLastPageScrollToNext;
- (void)filterDuplicates:(id)arg1 isReload:(_Bool)arg2;
- (void)_resetPreSectionFooterHeightForModel:(id)arg1;
- (void)_resortDataForTableView:(id)arg1;
- (void)finish_load:(id)arg1;
- (void)load_ads:(id)arg1;
- (void)loadShortVideoListFromRemoteModel:(id)arg1 index:(long long)arg2 derection:(long long)arg3;
- (void)loadFromRemote:(long long)arg1;
- (_Bool)loadFromLocal;
- (void)loadSlots:(id)arg1;
- (id)contentType;
- (void)onDislikeModel:(id)arg1 reason:(id)arg2;
- (void)onDislikeModelView:(id)arg1;
- (void)on_video_dislike:(id)arg1;
- (void)on_content_dislike:(id)arg1;
- (void)videoCellShareClickWithModel:(id)arg1;
- (void)didClickShortVideo:(id)arg1 index:(long long)arg2;
- (void)didElemsClick:(id)arg1 oper:(int)arg2;
- (id)modelAtIndexPath:(id)arg1;
- (void)configureCell:(id)arg1 atIndexPath:(id)arg2;
- (void)doEndDisplay:(id)arg1;
- (void)doUpdateDisplay;
- (void)yx_confirm;
- (void)yx_configHeaderView;
- (void)loadMore;
- (void)loadNew;
- (void)loadData:(_Bool)arg1 reset:(_Bool)arg2;
- (void)tableView_reloadRows:(id)arg1;
- (void)tableView_reloadData;
- (void)notiTipsCloseBtn;
- (void)notification_font_changed:(id)arg1;
- (void)notification_content_delete:(id)arg1;
- (_Bool)isRecommend;
- (_Bool)checkIfExpired;
- (_Bool)is_channel_expired;
- (long long)lastRefreshTime;
- (id)displayView;
- (id)initWithModel:(id)arg1 src:(int)arg2;
- (void)dealloc;
- (void)preDownLoadContentModel:(id)arg1;
- (void)tableViewManager:(id)arg1 scrollViewDidEndDecelerating:(id)arg2;
- (void)tableViewManager:(id)arg1 scrollViewDidScroll:(id)arg2;
- (void)tableViewManager:(id)arg1 scrollViewWillBeginDragging:(id)arg2;
- (void)tableViewManager:(id)arg1 tableViewEmptyButtonTouchAction:(long long)arg2;
- (void)tableViewManager:(id)arg1 tableViewEmptyScreenTouchAction:(long long)arg2;
- (void)tableViewManager:(id)arg1 cellForRowAtIndexPath:(id)arg2 tableViewCell:(id)arg3;
- (void)tableViewManager:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)tableViewManager:(id)arg1 withPullType:(long long)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(nonatomic) double oldPanOffsetY;
@property(nonatomic) double op;
@property(nonatomic) double refresh_num;
@property(nonatomic) double status;
@property(readonly) Class superclass;

@end

