//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class ClipBoardGifModel, NSString, UIButton, UIControl;

@interface ClipBoardGifView : UIView
{
    _Bool _isAutoPullDown;
    ClipBoardGifModel *_gift;
    UIControl *_overlayView;
    UIView *_foregroundTopView;
    UIView *_foregroundBottomView;
    UIButton *_closeButton;
    UIButton *_pullButton;
    UIButton *_typeImageView;
    NSString *_button_text;
    NSString *_button_url;
    CDUnknownBlockType _dismissAction;
}

@property(copy, nonatomic) CDUnknownBlockType dismissAction; // @synthesize dismissAction=_dismissAction;
@property(copy, nonatomic) NSString *button_url; // @synthesize button_url=_button_url;
@property(copy, nonatomic) NSString *button_text; // @synthesize button_text=_button_text;
@property(retain, nonatomic) UIButton *typeImageView; // @synthesize typeImageView=_typeImageView;
@property(nonatomic) _Bool isAutoPullDown; // @synthesize isAutoPullDown=_isAutoPullDown;
@property(retain, nonatomic) UIButton *pullButton; // @synthesize pullButton=_pullButton;
@property(retain, nonatomic) UIButton *closeButton; // @synthesize closeButton=_closeButton;
@property(retain, nonatomic) UIView *foregroundBottomView; // @synthesize foregroundBottomView=_foregroundBottomView;
@property(retain, nonatomic) UIView *foregroundTopView; // @synthesize foregroundTopView=_foregroundTopView;
@property(retain, nonatomic) UIControl *overlayView; // @synthesize overlayView=_overlayView;
@property(retain, nonatomic) ClipBoardGifModel *gift; // @synthesize gift=_gift;
- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)jumpAction:(id)arg1;
- (void)openWebview:(id)arg1;
- (void)pullDown:(id)arg1;
- (void)transformRotation:(id)arg1;
- (void)login;
- (void)dismiss;
- (void)show:(_Bool)arg1;
- (void)close;
- (void)reciveGift:(id)arg1 dismissAction:(CDUnknownBlockType)arg2;
- (void)show:(id)arg1 animation:(_Bool)arg2 dismissAction:(CDUnknownBlockType)arg3;

@end

