//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "LCBaseModel.h"

@class NSString;

@interface ClipBoardGifModel : LCBaseModel
{
    NSString *_gift_id;
    NSString *_gift_desc;
    NSString *_gift_amount;
    long long _gift_type;
    NSString *_gift_url_title;
    NSString *_gift_url_desc;
    NSString *_gift_url_url;
    NSString *_gift_url_confirm_text;
    NSString *_gift_user_nick;
    NSString *_gift_user_avatar;
    NSString *_gift_target_url;
    NSString *_gift_target_text;
    NSString *_gift_pwd;
}

@property(retain, nonatomic) NSString *gift_pwd; // @synthesize gift_pwd=_gift_pwd;
@property(retain, nonatomic) NSString *gift_target_text; // @synthesize gift_target_text=_gift_target_text;
@property(retain, nonatomic) NSString *gift_target_url; // @synthesize gift_target_url=_gift_target_url;
@property(retain, nonatomic) NSString *gift_user_avatar; // @synthesize gift_user_avatar=_gift_user_avatar;
@property(retain, nonatomic) NSString *gift_user_nick; // @synthesize gift_user_nick=_gift_user_nick;
@property(retain, nonatomic) NSString *gift_url_confirm_text; // @synthesize gift_url_confirm_text=_gift_url_confirm_text;
@property(retain, nonatomic) NSString *gift_url_url; // @synthesize gift_url_url=_gift_url_url;
@property(retain, nonatomic) NSString *gift_url_desc; // @synthesize gift_url_desc=_gift_url_desc;
@property(retain, nonatomic) NSString *gift_url_title; // @synthesize gift_url_title=_gift_url_title;
@property(nonatomic) long long gift_type; // @synthesize gift_type=_gift_type;
@property(retain, nonatomic) NSString *gift_amount; // @synthesize gift_amount=_gift_amount;
@property(retain, nonatomic) NSString *gift_desc; // @synthesize gift_desc=_gift_desc;
@property(retain, nonatomic) NSString *gift_id; // @synthesize gift_id=_gift_id;
- (void).cxx_destruct;
- (id)initWithAttribute:(id)arg1;

@end

