//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class ColdAppConfig, NSMutableArray, NSString, QKAppConfig, QKChannels;

@interface ConfigManger : NSObject
{
    long long _tsBegin;
    long long _tsEnd;
    _Bool _needUpdate;
    _Bool _isFirstStartToday;
    _Bool _is_channels_update;
    _Bool _noShowRedPackage;
    int _use_start;
    int _use_leave;
    QKAppConfig *_startConfig;
    ColdAppConfig *_coldStartConfig;
    QKAppConfig *_config;
    ColdAppConfig *_cold_config;
    QKChannels *_channels;
    QKChannels *_videoChannels;
    NSString *_regex;
    long long _networkStatus;
    NSString *_network;
    NSString *_carrier;
    NSString *_ua;
    NSString *_adeaz_ua;
    NSString *_api;
    NSString *_build;
    NSString *_UUID;
    NSString *_IDFA;
    NSString *_cacheCapacity;
    NSString *_ip;
    NSString *_innoToken;
    NSString *_guid;
    NSString *_launchStyle;
    NSString *_city;
    NSMutableArray *_update_channel_ids;
}

+ (id)manger;
+ (id)shareManager;
@property(nonatomic) _Bool noShowRedPackage; // @synthesize noShowRedPackage=_noShowRedPackage;
@property(retain, nonatomic) NSMutableArray *update_channel_ids; // @synthesize update_channel_ids=_update_channel_ids;
@property(nonatomic) _Bool is_channels_update; // @synthesize is_channels_update=_is_channels_update;
@property(retain, nonatomic) NSString *city; // @synthesize city=_city;
@property(nonatomic) int use_leave; // @synthesize use_leave=_use_leave;
@property(nonatomic) int use_start; // @synthesize use_start=_use_start;
@property(nonatomic) _Bool isFirstStartToday; // @synthesize isFirstStartToday=_isFirstStartToday;
@property(retain, nonatomic) NSString *launchStyle; // @synthesize launchStyle=_launchStyle;
@property(retain, nonatomic) NSString *guid; // @synthesize guid=_guid;
@property(retain, nonatomic) NSString *innoToken; // @synthesize innoToken=_innoToken;
@property(retain, nonatomic) NSString *ip; // @synthesize ip=_ip;
@property(retain, nonatomic) NSString *cacheCapacity; // @synthesize cacheCapacity=_cacheCapacity;
@property(retain, nonatomic) NSString *IDFA; // @synthesize IDFA=_IDFA;
@property(retain, nonatomic) NSString *UUID; // @synthesize UUID=_UUID;
@property(copy, nonatomic) NSString *build; // @synthesize build=_build;
@property(copy, nonatomic) NSString *api; // @synthesize api=_api;
@property(copy, nonatomic) NSString *adeaz_ua; // @synthesize adeaz_ua=_adeaz_ua;
@property(copy, nonatomic) NSString *ua; // @synthesize ua=_ua;
@property(copy, nonatomic) NSString *carrier; // @synthesize carrier=_carrier;
@property(retain, nonatomic) NSString *network; // @synthesize network=_network;
@property(nonatomic) long long networkStatus; // @synthesize networkStatus=_networkStatus;
@property(retain, nonatomic) NSString *regex; // @synthesize regex=_regex;
@property(retain, nonatomic) QKChannels *videoChannels; // @synthesize videoChannels=_videoChannels;
@property(retain, nonatomic) QKChannels *channels; // @synthesize channels=_channels;
@property(retain, nonatomic) ColdAppConfig *cold_config; // @synthesize cold_config=_cold_config;
@property(retain, nonatomic) QKAppConfig *config; // @synthesize config=_config;
@property(retain, nonatomic) ColdAppConfig *coldStartConfig; // @synthesize coldStartConfig=_coldStartConfig;
@property(retain, nonatomic) QKAppConfig *startConfig; // @synthesize startConfig=_startConfig;
- (void).cxx_destruct;
- (id)subviews:(id)arg1;
- (id)package;
@property(readonly, nonatomic) NSString *channel;
- (id)localBuildVersion;
@property(readonly, nonatomic) NSString *shortVersion;
@property(readonly, nonatomic) NSString *AKU;
- (_Bool)is_splash_show;
- (_Bool)is_content_expired;
- (void)recordUserActive;
- (void)update:(id)arg1;
- (void)update:(id)arg1 isCallByStart:(_Bool)arg2;
- (void)getUserContentChannelList;
- (void)getVideoChannelList;
- (void)getDefaultChannelList;
- (void)checkNetwork:(long long)arg1;
- (void)showAlertForUsable:(id)arg1;
- (void)checkAppUsable:(id)arg1;
- (void)lightConfig;
- (void)checkHttps:(id)arg1;
- (void)coldStart;
- (void)start;
- (id)_loadLocalColdStartConfigData;
- (id)_loadLocalStartConfigData;
- (void)_update;
- (void)reloadData;
- (void)updateIfNeed;
- (void)setNeedUpdate;
- (void)loadConfigDataFromRemote;
- (void)updateTimestamp;
- (id)init;

@end

