//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QKBaseViewController.h"

#import "UISearchBarDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSArray, NSMutableArray, NSString, QKShareModel, UIButton, UISearchBar, UITableView, UIView;

@interface ContactViewController : QKBaseViewController <UITableViewDelegate, UITableViewDataSource, UISearchBarDelegate>
{
    _Bool _isSearch;
    UITableView *_tableView;
    QKShareModel *_shareObject;
    NSArray *_contacts;
    NSMutableArray *_contacts_selected;
    NSArray *_contacts_group;
    NSArray *_contacts_index;
    NSMutableArray *_contacts_search;
    NSArray *_default_contacts_index;
    UIButton *_smsInviteButton;
    UISearchBar *_searchBar;
    UIView *_toolBar;
}

@property(retain, nonatomic) UIView *toolBar; // @synthesize toolBar=_toolBar;
@property(retain, nonatomic) UISearchBar *searchBar; // @synthesize searchBar=_searchBar;
@property(retain, nonatomic) UIButton *smsInviteButton; // @synthesize smsInviteButton=_smsInviteButton;
@property(retain, nonatomic) NSArray *default_contacts_index; // @synthesize default_contacts_index=_default_contacts_index;
@property(retain, nonatomic) NSMutableArray *contacts_search; // @synthesize contacts_search=_contacts_search;
@property(retain, nonatomic) NSArray *contacts_index; // @synthesize contacts_index=_contacts_index;
@property(retain, nonatomic) NSArray *contacts_group; // @synthesize contacts_group=_contacts_group;
@property(retain, nonatomic) NSMutableArray *contacts_selected; // @synthesize contacts_selected=_contacts_selected;
@property(retain, nonatomic) NSArray *contacts; // @synthesize contacts=_contacts;
@property(retain, nonatomic) QKShareModel *shareObject; // @synthesize shareObject=_shareObject;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
- (void).cxx_destruct;
- (void)searchBarCancelButtonClicked:(id)arg1;
- (void)searchBarSearchButtonClicked:(id)arg1;
- (void)searchBar:(id)arg1 textDidChange:(id)arg2;
- (void)searchBarTextDidBeginEditing:(id)arg1;
- (void)selectAll:(id)arg1;
- (void)smsInvite:(id)arg1;
- (void)loadContacts;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 sectionForSectionIndexTitle:(id)arg2 atIndex:(long long)arg3;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)sectionIndexTitlesForTableView:(id)arg1;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

