//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "AVAudioPlayerDelegate-Protocol.h"

@class AVAudioPlayer, NSString;
@protocol CRAVAudioPlayerDelegate;

@interface CRAVAudioPlayer : NSObject <AVAudioPlayerDelegate>
{
    AVAudioPlayer *_player;
    id <CRAVAudioPlayerDelegate> _delegate;
}

+ (id)sharedInstance;
@property(nonatomic) __weak id <CRAVAudioPlayerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) AVAudioPlayer *player; // @synthesize player=_player;
- (void).cxx_destruct;
- (_Bool)isPlaying;
- (void)applicationWillResignActive:(id)arg1;
- (void)stopSound;
- (void)audioPlayerDidFinishPlaying:(id)arg1 successfully:(_Bool)arg2;
- (void)setupPlaySound;
- (_Bool)playSoundWithData:(id)arg1;
- (_Bool)playSoundWithPath:(id)arg1;
- (_Bool)playSongWithData:(id)arg1;
- (_Bool)playSongWithFilePath:(id)arg1;
- (void)playSongWithUrl:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

