//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIButton.h>

@class CRMessageFrame, CRMusicView, CRVideoView, CRVoiceView, UIImageView, V5KZLinkLabel;

@interface CRMessageContentButton : UIButton
{
    _Bool _isMyMessage;
    UIImageView *_backImageView;
    V5KZLinkLabel *_richLabel;
    CRVoiceView *_voiceView;
    CRVideoView *_videoView;
    CRMusicView *_musicView;
    CRMessageFrame *_messageFrame;
}

@property(nonatomic) _Bool isMyMessage; // @synthesize isMyMessage=_isMyMessage;
@property(nonatomic) CRMessageFrame *messageFrame; // @synthesize messageFrame=_messageFrame;
@property(retain, nonatomic) CRMusicView *musicView; // @synthesize musicView=_musicView;
@property(retain, nonatomic) CRVideoView *videoView; // @synthesize videoView=_videoView;
@property(retain, nonatomic) CRVoiceView *voiceView; // @synthesize voiceView=_voiceView;
@property(retain, nonatomic) V5KZLinkLabel *richLabel; // @synthesize richLabel=_richLabel;
@property(retain, nonatomic) UIImageView *backImageView; // @synthesize backImageView=_backImageView;
- (void).cxx_destruct;
- (_Bool)canBecomeFirstResponder;
- (void)setFrame:(struct CGRect)arg1;
- (void)addMusicView;
- (void)addVideoView;
- (void)addVoiceView;
- (void)addImageView;
- (void)addTextView;
- (void)clearView;
- (id)initWithFrame:(struct CGRect)arg1;

@end

