//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class CRMessageCell, NSString;

@protocol CRMessageCellDelegate <NSObject>

@optional
- (void)cellDidMediaLoadFailed:(CRMessageCell *)arg1 willRetry:(_Bool)arg2;
- (void)resendDidClick:(CRMessageCell *)arg1;
- (void)cellLinkDidLongClick:(CRMessageCell *)arg1 linkType:(long long)arg2 link:(NSString *)arg3;
- (void)cellLinkDidClick:(CRMessageCell *)arg1 linkType:(long long)arg2 link:(NSString *)arg3;
- (void)cellDidLongClick:(CRMessageCell *)arg1 messageType:(long long)arg2 direction:(long long)arg3;
- (void)cellDidClick:(CRMessageCell *)arg1 messageType:(long long)arg2 direction:(long long)arg3;
@end

