//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSTimer, UIImageView, UILabel, UIWindow;

@interface CRProgressHUD : UIView
{
    NSTimer *myTimer;
    int angle;
    UILabel *centerLabel;
    UIImageView *edgeImageView;
    UIWindow *overlayWindow;
    UILabel *_titleLabel;
    UILabel *_subTitleLabel;
}

+ (void)dismissWithError:(id)arg1;
+ (void)dismissWithSuccess:(id)arg1;
+ (void)changeSubTitle:(id)arg1;
+ (void)show;
+ (id)sharedView;
@property(retain, nonatomic) UILabel *subTitleLabel; // @synthesize subTitleLabel=_subTitleLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void).cxx_destruct;
@property(readonly, nonatomic) UIWindow *overlayWindow; // @synthesize overlayWindow;
- (void)dismiss:(id)arg1;
- (void)setState:(id)arg1;
- (void)startAnimation;
- (void)show;

@end

