//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIActivityIndicatorView, UIButton, UILabel, UISlider;

@interface CRVideoPlayerControlView : UIView
{
    _Bool _isBarShowing;
    UIView *_topBar;
    UIView *_bottomBar;
    UIButton *_playButton;
    UIButton *_pauseButton;
    UIButton *_fullScreenButton;
    UIButton *_shrinkScreenButton;
    UISlider *_progressSlider;
    UIButton *_closeButton;
    UILabel *_timeLabel;
    UIActivityIndicatorView *_indicatorView;
}

@property(retain, nonatomic) UIActivityIndicatorView *indicatorView; // @synthesize indicatorView=_indicatorView;
@property(nonatomic) _Bool isBarShowing; // @synthesize isBarShowing=_isBarShowing;
@property(retain, nonatomic) UILabel *timeLabel; // @synthesize timeLabel=_timeLabel;
@property(retain, nonatomic) UIButton *closeButton; // @synthesize closeButton=_closeButton;
@property(retain, nonatomic) UISlider *progressSlider; // @synthesize progressSlider=_progressSlider;
@property(retain, nonatomic) UIButton *shrinkScreenButton; // @synthesize shrinkScreenButton=_shrinkScreenButton;
@property(retain, nonatomic) UIButton *fullScreenButton; // @synthesize fullScreenButton=_fullScreenButton;
@property(retain, nonatomic) UIButton *pauseButton; // @synthesize pauseButton=_pauseButton;
@property(retain, nonatomic) UIButton *playButton; // @synthesize playButton=_playButton;
@property(retain, nonatomic) UIView *bottomBar; // @synthesize bottomBar=_bottomBar;
@property(retain, nonatomic) UIView *topBar; // @synthesize topBar=_topBar;
- (void).cxx_destruct;
- (id)videoImageName:(id)arg1;
- (void)onTap:(id)arg1;
- (void)cancelAutoFadeOutControlBar;
- (void)autoFadeOutControlBar;
- (void)animateShow;
- (void)animateHide;
- (void)didMoveToSuperview;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

