//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MediaPlayer/MPMoviePlayerController.h>

@class CRVideoPlayerControlView, NSTimer, UIView;

@interface CRVideoPlayerController : MPMoviePlayerController
{
    _Bool _isFullscreenMode;
    CDUnknownBlockType _dimissCompleteBlock;
    CRVideoPlayerControlView *_videoControl;
    UIView *_movieBackgroundView;
    NSTimer *_durationTimer;
    struct CGRect _frame;
    struct CGRect _originFrame;
}

@property(retain, nonatomic) NSTimer *durationTimer; // @synthesize durationTimer=_durationTimer;
@property(nonatomic) struct CGRect originFrame; // @synthesize originFrame=_originFrame;
@property(nonatomic) _Bool isFullscreenMode; // @synthesize isFullscreenMode=_isFullscreenMode;
@property(retain, nonatomic) UIView *movieBackgroundView; // @synthesize movieBackgroundView=_movieBackgroundView;
@property(retain, nonatomic) CRVideoPlayerControlView *videoControl; // @synthesize videoControl=_videoControl;
@property(nonatomic) struct CGRect frame; // @synthesize frame=_frame;
@property(copy, nonatomic) CDUnknownBlockType dimissCompleteBlock; // @synthesize dimissCompleteBlock=_dimissCompleteBlock;
- (void).cxx_destruct;
- (void)fadeDismissControl;
- (void)stopDurationTimer;
- (void)startDurationTimer;
- (void)setTimeLabelValues:(double)arg1 totalTime:(double)arg2;
- (void)monitorVideoPlayback;
- (void)progressSliderValueChanged:(id)arg1;
- (void)progressSliderTouchEnded:(id)arg1;
- (void)progressSliderTouchBegan:(id)arg1;
- (void)setProgressSliderMaxMinValues;
- (void)shrinkScreenButtonClick;
- (void)fullScreenButtonClick;
- (void)closeButtonClick;
- (void)pauseButtonClick;
- (void)playButtonClick;
- (void)onMPMovieDurationAvailableNotification;
- (void)onMPMoviePlayerReadyForDisplayDidChangeNotification;
- (void)onMPMoviePlayerLoadStateDidChangeNotification;
- (void)onMPMoviePlayerPlaybackStateDidChangeNotification;
- (void)configControlAction;
- (void)cancelObserver;
- (void)configObserver;
- (void)dismiss;
- (void)showInWindow;
- (void)setContentURL:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;

@end

