//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "CRAVAudioPlayerDelegate-Protocol.h"

@class CRMessageFrame, CRProgressView, CRVideoPlayerController, NSString, UIButton, UIImageView, V5VideoMessage;

@interface CRVideoView : UIView <CRAVAudioPlayerDelegate>
{
    _Bool videoIsPlaying;
    V5VideoMessage *message;
    UIButton *_videoControlButton;
    UIImageView *_videoBg;
    CRProgressView *_progressView;
    CRMessageFrame *_messageFrame;
    CRVideoPlayerController *_videoController;
}

@property(retain, nonatomic) CRVideoPlayerController *videoController; // @synthesize videoController=_videoController;
@property(retain, nonatomic) CRMessageFrame *messageFrame; // @synthesize messageFrame=_messageFrame;
@property(retain, nonatomic) CRProgressView *progressView; // @synthesize progressView=_progressView;
@property(retain, nonatomic) UIImageView *videoBg; // @synthesize videoBg=_videoBg;
@property(retain, nonatomic) UIButton *videoControlButton; // @synthesize videoControlButton=_videoControlButton;
- (void).cxx_destruct;
- (void)setHVVideoMessage:(id)arg1;
- (void)CRAVAudioPlayerDidFinishPlay;
- (void)CRAVAudioPlayerBeiginPlay;
- (void)CRAVAudioPlayerBeiginLoadVoice;
- (void)stopPlayVideo;
- (void)playVideoWithURL:(id)arg1;
- (void)startPlayVideo:(id)arg1;
- (void)didStopPlay;
- (void)didStartPlay;
- (void)didLoadVideoFailed;
- (void)didLoadVideo;
- (void)benginLoadVideo;
- (void)playVideo:(id)arg1;
- (void)addCustomProgressView;
- (void)updateViewOfMessage:(id)arg1;
- (void)clearView;
- (void)dealloc;
- (void)removeFromSuperview;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

