//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "CRAVAudioPlayerDelegate-Protocol.h"

@class CRAVAudioPlayer, CRMessageFrame, NSString, UIActivityIndicatorView, UIImageView, UILabel, V5VoiceMessage;

@interface CRVoiceView : UIView <CRAVAudioPlayerDelegate>
{
    _Bool voiceIsPlaying;
    CRAVAudioPlayer *audio;
    V5VoiceMessage *message;
    UILabel *_second;
    UIImageView *_voice;
    UIActivityIndicatorView *_indicator;
    CRMessageFrame *_messageFrame;
}

@property(retain, nonatomic) CRMessageFrame *messageFrame; // @synthesize messageFrame=_messageFrame;
@property(retain, nonatomic) UIActivityIndicatorView *indicator; // @synthesize indicator=_indicator;
@property(retain, nonatomic) UIImageView *voice; // @synthesize voice=_voice;
@property(retain, nonatomic) UILabel *second; // @synthesize second=_second;
- (void).cxx_destruct;
- (void)setHVVoiceMessage:(id)arg1;
- (void)playVoice:(id)arg1;
- (void)sensorStateChange:(id)arg1;
- (void)CRAVAudioPlayerDidFinishPlay;
- (void)CRAVAudioPlayerBeiginPlay;
- (void)CRAVAudioPlayerBeiginLoadVoice;
- (void)stopPlayVoice;
- (void)startPlayVoice:(id)arg1;
- (void)didStopPlay;
- (void)didStartPlay;
- (void)didLoadVoiceFailed;
- (void)didLoadVoice;
- (void)benginLoadVoice;
- (void)loadVoice:(id)arg1;
- (void)updateViewOfMessage:(id)arg1;
- (void)clearView;
- (void)dealloc;
- (void)removeFromSuperview;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

