//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString, UIImage;

@interface EmptyModel : NSObject
{
    _Bool _touchEnable;
    _Bool _enable;
    long long _type;
    UIImage *_image;
    NSString *_text;
    NSString *_buttonText;
    UIImage *_buttonImage;
}

@property(nonatomic) _Bool enable; // @synthesize enable=_enable;
@property(nonatomic) _Bool touchEnable; // @synthesize touchEnable=_touchEnable;
@property(copy, nonatomic) UIImage *buttonImage; // @synthesize buttonImage=_buttonImage;
@property(copy, nonatomic) NSString *buttonText; // @synthesize buttonText=_buttonText;
@property(copy, nonatomic) NSString *text; // @synthesize text=_text;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
@property(nonatomic) long long type; // @synthesize type=_type;
- (void).cxx_destruct;

@end

