//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSArray, NSMutableDictionary, NSString;

@interface ExceptionModel : NSObject
{
    float _memory;
    float _cpu;
    float _battery;
    int _exception_first;
    NSString *_model;
    NSString *_system;
    NSString *_version;
    NSString *_network;
    NSString *_user_id;
    unsigned long long _use_duration;
    NSArray *_use_tracks;
    NSString *_exception_id;
    NSString *_exception_name;
    NSString *_exception_module;
    NSString *_exception_type;
    NSString *_exception_reason;
    NSArray *_exception_stack;
    NSString *_exception_time;
    NSMutableDictionary *_extra;
}

+ (id)exceptionWithDictionary:(id)arg1;
+ (id)exception;
@property(retain, nonatomic) NSMutableDictionary *extra; // @synthesize extra=_extra;
@property(retain, nonatomic) NSString *exception_time; // @synthesize exception_time=_exception_time;
@property(retain, nonatomic) NSArray *exception_stack; // @synthesize exception_stack=_exception_stack;
@property(retain, nonatomic) NSString *exception_reason; // @synthesize exception_reason=_exception_reason;
@property(retain, nonatomic) NSString *exception_type; // @synthesize exception_type=_exception_type;
@property(nonatomic) int exception_first; // @synthesize exception_first=_exception_first;
@property(retain, nonatomic) NSString *exception_module; // @synthesize exception_module=_exception_module;
@property(retain, nonatomic) NSString *exception_name; // @synthesize exception_name=_exception_name;
@property(retain, nonatomic) NSString *exception_id; // @synthesize exception_id=_exception_id;
@property(retain, nonatomic) NSArray *use_tracks; // @synthesize use_tracks=_use_tracks;
@property(nonatomic) unsigned long long use_duration; // @synthesize use_duration=_use_duration;
@property(retain, nonatomic) NSString *user_id; // @synthesize user_id=_user_id;
@property(nonatomic) float battery; // @synthesize battery=_battery;
@property(nonatomic) float cpu; // @synthesize cpu=_cpu;
@property(nonatomic) float memory; // @synthesize memory=_memory;
@property(retain, nonatomic) NSString *network; // @synthesize network=_network;
@property(retain, nonatomic) NSString *version; // @synthesize version=_version;
@property(retain, nonatomic) NSString *system; // @synthesize system=_system;
@property(retain, nonatomic) NSString *model; // @synthesize model=_model;
- (void).cxx_destruct;
- (id)getExceptionInfo;
- (id)getUserInfo;
- (id)getKpiInfo;
- (id)getBasicInfo;
- (id)getExtraInfo;
- (id)get_exception_info;
- (id)dictionary;
- (void)loadException:(id)arg1;

@end

