//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface InnoMain : NSObject
{
}

+ (void)reportJSSubChannelInfo:(id)arg1;
+ (void)reportJSSubChannelInfo;
+ (id)checkInfo;
+ (id)loadInfo;
+ (void)changeCustomParams:(id)arg1;
+ (void)submitWithRetryWithTimes:(id)arg1;
+ (void)submitWithRetryWithData:(id)arg1;
+ (void)onReportTimer:(id)arg1;
+ (void)startInnoWithBlock:(CDUnknownBlockType)arg1;

@end

