//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QKBaseViewController.h"

#import "QKCodeImageViewDelegate-Protocol.h"

@class ClipBoardGifModel, CodeInputView, NSMutableDictionary, NSString, NSTimer, UIButton, UIView;

@interface InputCaptchaController : QKBaseViewController <QKCodeImageViewDelegate>
{
    CDUnknownBlockType _loginCompletion;
    NSMutableDictionary *_paramDictionary;
    NSTimer *_timer;
    UIButton *_tip_button;
    UIButton *_reCodeButton;
    NSString *_phoneNumber;
    UIView *_backgroudView;
    NSString *_codeString;
    ClipBoardGifModel *_clipboardGif;
    CodeInputView *_codeView;
    id _scheme;
}

@property(retain, nonatomic) id scheme; // @synthesize scheme=_scheme;
@property(retain, nonatomic) CodeInputView *codeView; // @synthesize codeView=_codeView;
@property(retain, nonatomic) ClipBoardGifModel *clipboardGif; // @synthesize clipboardGif=_clipboardGif;
@property(retain, nonatomic) NSString *codeString; // @synthesize codeString=_codeString;
@property(retain, nonatomic) UIView *backgroudView; // @synthesize backgroudView=_backgroudView;
@property(retain, nonatomic) NSString *phoneNumber; // @synthesize phoneNumber=_phoneNumber;
@property(retain, nonatomic) UIButton *reCodeButton; // @synthesize reCodeButton=_reCodeButton;
@property(retain, nonatomic) UIButton *tip_button; // @synthesize tip_button=_tip_button;
@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
@property(retain, nonatomic) NSMutableDictionary *paramDictionary; // @synthesize paramDictionary=_paramDictionary;
@property(copy, nonatomic) CDUnknownBlockType loginCompletion; // @synthesize loginCompletion=_loginCompletion;
- (void).cxx_destruct;
- (void)notifyLoginSucess;
- (void)back;
- (void)dismiss;
- (void)tagsAliasCallback:(int)arg1 tags:(id)arg2 alias:(id)arg3;
- (void)showFreezzingReason:(id)arg1 confirmText:(id)arg2;
- (void)showFreezzingReason:(id)arg1 confirmText:(id)arg2 selector:(id)arg3;
- (void)didReceiveMemoryWarnitng;
- (void)dismiss:(_Bool)arg1;
- (void)openGift:(id)arg1;
- (void)getUserContentChannelList:(_Bool)arg1;
- (void)gotoInvite;
- (void)api_login_finish:(id)arg1;
- (id)loginParam:(id)arg1;
- (void)login;
- (void)contact:(id)arg1;
- (void)reSendCode;
- (id)returnCodeTitle:(int)arg1;
- (void)invalidateTimer;
- (void)creatrTimer;
- (void)changeTitle:(id)arg1;
- (void)qkCodeImageViewButtonClick:(id)arg1;
- (void)qkCodeImageViewButtonClose:(id)arg1;
- (void)getCode;
- (void)createUI;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)handleDeepLink;
- (id)initWithPhoneNumber:(id)arg1 clipboardGif:(id)arg2 scheme:(id)arg3;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

