//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QKTableViewCell.h"

#import "LCTableViewCellConfigure-Protocol.h"

@class NSMutableArray, NSString, UIButton, UIImageView, UILabel, UIView;

@interface InviteFollowerCell : QKTableViewCell <LCTableViewCellConfigure>
{
    CDUnknownBlockType _pressButtonActionBlock;
    CDUnknownBlockType _pressTopViewActionBlock;
    UIView *_topView;
    UIButton *_topBtn;
    UIView *_leftLine;
    UIView *_bottomLine;
    UILabel *_topTitle;
    UILabel *_subTitle;
    UIImageView *_rightRoundView;
    UIView *_redDot;
    UIView *_rightPointView;
    UIImageView *_bgImageView;
    UIView *_bottomView;
    NSMutableArray *_invBtns;
}

@property(retain, nonatomic) NSMutableArray *invBtns; // @synthesize invBtns=_invBtns;
@property(retain, nonatomic) UIView *bottomView; // @synthesize bottomView=_bottomView;
@property(retain, nonatomic) UIImageView *bgImageView; // @synthesize bgImageView=_bgImageView;
@property(retain, nonatomic) UIView *rightPointView; // @synthesize rightPointView=_rightPointView;
@property(retain, nonatomic) UIView *redDot; // @synthesize redDot=_redDot;
@property(retain, nonatomic) UIImageView *rightRoundView; // @synthesize rightRoundView=_rightRoundView;
@property(retain, nonatomic) UILabel *subTitle; // @synthesize subTitle=_subTitle;
@property(retain, nonatomic) UILabel *topTitle; // @synthesize topTitle=_topTitle;
@property(retain, nonatomic) UIView *bottomLine; // @synthesize bottomLine=_bottomLine;
@property(retain, nonatomic) UIView *leftLine; // @synthesize leftLine=_leftLine;
@property(retain, nonatomic) UIButton *topBtn; // @synthesize topBtn=_topBtn;
@property(retain, nonatomic) UIView *topView; // @synthesize topView=_topView;
@property(copy, nonatomic) CDUnknownBlockType pressTopViewActionBlock; // @synthesize pressTopViewActionBlock=_pressTopViewActionBlock;
@property(copy, nonatomic) CDUnknownBlockType pressButtonActionBlock; // @synthesize pressButtonActionBlock=_pressButtonActionBlock;
- (void).cxx_destruct;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)update:(id)arg1;
- (id)getInvitationBtn:(long long)arg1 size:(struct CGSize)arg2 model:(id)arg3;
- (void)modifyBgImage:(id)arg1;
- (void)adjustSubviewsFrame;
- (void)layoutSubviews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)dealloc;
- (void)configureCellWithModel:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

