//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "JSExport-Protocol.h"

@class NSNumber, NSString;

@protocol JavaScriptOCDelegate <JSExport>
- (NSNumber *)isTimeVersion:(NSString *)arg1;
- (void)timeLimitProp:(NSString *)arg1;
- (void)hidePopup;
- (void)showPopup:(NSString *)arg1:(NSString *)arg2;
- (void)askAsynData:(NSString *)arg1:(NSString *)arg2:(NSString *)arg3:(NSString *)arg4;
- (void)openviewFromRecommend:(NSString *)arg1:(NSString *)arg2:(NSString *)arg3:(NSString *)arg4:(NSString *)arg5:(NSString *)arg6:(long long)arg7;
- (void)scrollBounces:(_Bool)arg1;
- (_Bool)displayLike:(NSString *)arg1;
- (void)openWebviewFromHtml:(NSString *)arg1:(NSString *)arg2;
- (void)localWrite:(NSString *)arg1:(NSString *)arg2;
- (NSString *)localRead:(NSString *)arg1;
- (double)getScrollHeight;
- (double)getScrollTop;
- (long long)dangerousUser;
- (void)report:(NSString *)arg1;
- (NSString *)getTk;
@end

