//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface kNPzCwtMrjPndaxN : NSObject
{
}

+ (id)zIAAMYiCmCNeCSHT;
+ (void)ztRYyvqEHzzkwPgq:(id)arg1 withRequest:(id)arg2;
+ (id)BbVVnmDdEBqhMPZr:(id)arg1;
+ (id)TfsZvqkaGxQWFmlq:(id)arg1;
+ (void)YkalCjvaoyjvNnFP:(id)arg1 withResponse:(id)arg2 withError:(id)arg3 onComplete:(CDUnknownBlockType)arg4;
+ (void)MhHwgLCOmkuSxRGr:(id)arg1 withBody:(id)arg2 withHeaders:(id)arg3 onComplete:(CDUnknownBlockType)arg4;
+ (void)MIIfANsdJUWzcFDZ:(id)arg1 withParams:(id)arg2 withHeaders:(id)arg3 onComplete:(CDUnknownBlockType)arg4;
+ (void)YHEftJPWYAKmOOcS:(id)arg1 withParams:(id)arg2 withHeaders:(id)arg3 onComplete:(CDUnknownBlockType)arg4;
+ (void)nPDxWjbqHjSegGeY;

@end

