//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@protocol LCAdvertisingProtocol;

@interface LCAdvertising : NSObject
{
    id <LCAdvertisingProtocol> _delegate;
}

+ (id)sharedInstance;
@property(nonatomic) __weak id <LCAdvertisingProtocol> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)ad_report_clickAdObj:(id)arg1;
- (void)ad_report_clickAdvert:(id)arg1;
- (void)ad_report_displayAdObj:(id)arg1;
- (void)ad_report_displayAdvert:(id)arg1;
- (void)deleteCachedAdObject_Splash;
- (void)saveAdObject_SplashToDisk:(id)arg1;
- (id)cachedAdObject_Splash;
- (void)download_adObject_Splash:(id)arg1;
- (void)get_ad_async_cache:(int)arg1 cid:(id)arg2 adverts:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (void)get_ad_slots:(int)arg1 contentType:(id)arg2 channelId:(id)arg3;

@end

