//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class FMDatabaseQueue;

@interface LCAnalyicsDB : NSObject
{
    FMDatabaseQueue *_dbQueue;
}

+ (id)sharedInstance;
@property(retain, nonatomic) FMDatabaseQueue *dbQueue; // @synthesize dbQueue=_dbQueue;
- (void).cxx_destruct;
- (void)insertEventWithModel:(id)arg1;
- (void)removeEvents:(id)arg1;
- (id)allEvents;
- (void)insertEvents:(id)arg1;
- (void)insertEventWithAttribute:(id)arg1;
- (void)creatTable;
- (id)init;

@end

