//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSMutableArray, NSThread;
@protocol LCAnalyicsProtocol;

@interface LCAnalyicsReporter : NSObject
{
    _Bool _bExit;
    NSThread *_workThread;
    _Bool _switchRedpacket;
    _Bool _switchDd;
    _Bool _switchQuantize;
    id <LCAnalyicsProtocol> _delegate;
    NSMutableArray *_readTimeEventList;
}

+ (void)suspect_and_reportWithHandler:(CDUnknownBlockType)arg1;
+ (id)sharedInstance;
@property(retain, nonatomic) NSMutableArray *readTimeEventList; // @synthesize readTimeEventList=_readTimeEventList;
@property(nonatomic) __weak id <LCAnalyicsProtocol> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)reportReadTimeEventList;
- (void)readTimeEvent:(id)arg1 action:(id)arg2 metric:(id)arg3 info:(id)arg4 cache:(_Bool)arg5;
- (void)readTimeEvent:(id)arg1 action:(id)arg2 metric:(id)arg3 info:(id)arg4;
- (void)report_to_DDD:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)__setupReport_to_DDD_requestOnMainThread:(id)arg1;
- (void)report_quantize;
- (void)report_dd;
- (void)postRedpacketsNotification;
- (void)workThreadProc;
- (void)conclude;
- (void)exit;
- (void)setSwitchRedpacket:(_Bool)arg1;
- (Class)mediator;
- (id)init;

@end

