//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class LCDataBase, LCFileStorage;

@interface LCCache : NSObject
{
    LCFileStorage *_fileStorage;
    LCDataBase *_db;
}

+ (id)sharedInstance;
@property(retain, nonatomic) LCDataBase *db; // @synthesize db=_db;
@property(retain, nonatomic) LCFileStorage *fileStorage; // @synthesize fileStorage=_fileStorage;
- (void).cxx_destruct;
- (id)init;

@end

