//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class FMDatabaseQueue;

@interface LCDataBase : NSObject
{
    FMDatabaseQueue *_dbQueue;
}

@property(retain, nonatomic) FMDatabaseQueue *dbQueue; // @synthesize dbQueue=_dbQueue;
- (void).cxx_destruct;
- (void)executeQuery:(id)arg1 enumerateObjectsUsingBlock:(CDUnknownBlockType)arg2;
- (void)executeUpdate:(id)arg1 enumerateObjectsUsingBlock:(CDUnknownBlockType)arg2;
- (void)executeUpdate:(id)arg1;
- (void)executeCreate:(id)arg1;
- (void)configDataBasePath:(id)arg1;
- (id)init;

@end

