//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface LCHNetworking : NSObject
{
}

+ (void)uploadFile2:(id)arg1 src:(int)arg2 handler:(CDUnknownBlockType)arg3;
+ (void)uploadFile:(id)arg1 src:(int)arg2 handler:(CDUnknownBlockType)arg3;
+ (void)upload:(id)arg1 file:(id)arg2 handler:(CDUnknownBlockType)arg3;
+ (void)request_GET:(id)arg1 parameters:(id)arg2 handler:(CDUnknownBlockType)arg3;
+ (void)requset:(id)arg1 method:(unsigned long long)arg2 parameters:(id)arg3 handler:(CDUnknownBlockType)arg4;
+ (void)GET:(id)arg1 response:(CDUnknownBlockType)arg2;
+ (void)POST:(id)arg1 response:(CDUnknownBlockType)arg2;
+ (id)bundleWithParams:(id)arg1;
+ (id)cgetSign:(id)arg1;
+ (id)parseModel:(Class)arg1 data:(id)arg2 info:(id)arg3;
+ (id)parse:(id)arg1;
+ (void)parseResp:(id)arg1;
+ (_Bool)__readData:(id)arg1;
+ (void)__saveData:(id)arg1;
+ (id)getPath:(id)arg1;

@end

