//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "LCSystemicService.h"

#import "UIImagePickerControllerDelegate-Protocol.h"
#import "UINavigationControllerDelegate-Protocol.h"

@class NSString, UIImagePickerController;

@interface LCImagePickerService : LCSystemicService <UINavigationControllerDelegate, UIImagePickerControllerDelegate>
{
    unsigned long long _sourceType;
    CDUnknownBlockType _didFinishPickingImage;
    CDUnknownBlockType _didCancel;
    UIImagePickerController *_imagePicker;
}

@property(retain, nonatomic) UIImagePickerController *imagePicker; // @synthesize imagePicker=_imagePicker;
@property(copy, nonatomic) CDUnknownBlockType didCancel; // @synthesize didCancel=_didCancel;
@property(copy, nonatomic) CDUnknownBlockType didFinishPickingImage; // @synthesize didFinishPickingImage=_didFinishPickingImage;
@property(nonatomic) unsigned long long sourceType; // @synthesize sourceType=_sourceType;
- (void).cxx_destruct;
- (void)imagePickerControllerDidCancel:(id)arg1;
- (void)imagePickerController:(id)arg1 didFinishPickingMediaWithInfo:(id)arg2;
- (void)showServiceController;
- (void)requestAuthorization:(CDUnknownBlockType)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

