//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "LCSystemicService.h"

#import "CLLocationManagerDelegate-Protocol.h"

@class CLLocationManager, NSArray, NSDate, NSString;

@interface LCLocationService : LCSystemicService <CLLocationManagerDelegate>
{
    NSArray *_locations;
    CDUnknownBlockType _didChangeAuthorizationStatus;
    CDUnknownBlockType _didUpdateLocations;
    CDUnknownBlockType _didFailWithError;
    CLLocationManager *_locationManager;
}

@property(retain, nonatomic) CLLocationManager *locationManager; // @synthesize locationManager=_locationManager;
@property(copy, nonatomic) CDUnknownBlockType didFailWithError; // @synthesize didFailWithError=_didFailWithError;
@property(copy, nonatomic) CDUnknownBlockType didUpdateLocations; // @synthesize didUpdateLocations=_didUpdateLocations;
@property(copy, nonatomic) CDUnknownBlockType didChangeAuthorizationStatus; // @synthesize didChangeAuthorizationStatus=_didChangeAuthorizationStatus;
@property(retain, nonatomic) NSArray *locations; // @synthesize locations=_locations;
- (void).cxx_destruct;
- (void)locationManager:(id)arg1 didFailWithError:(id)arg2;
- (void)locationManager:(id)arg1 didUpdateLocations:(id)arg2;
- (void)locationManager:(id)arg1 didChangeAuthorizationStatus:(int)arg2;
- (void)stopUpdatingLocation;
- (void)startUpdatingLocation:(CDUnknownBlockType)arg1;
- (void)startUpdatingLocation;
- (void)requestLocationAuthorization:(CDUnknownBlockType)arg1;
- (void)setAllowsBackgroundLocationUpdates:(_Bool)arg1;
- (void)requestWhenInUseAuthorization;
- (void)requestAlwaysAuthorization;
- (void)_sendLocation:(id)arg1;
- (void)qtt_reverseGeocodeLocation:(id)arg1;
@property(nonatomic) _Bool qtt_isSend;
@property(retain, nonatomic) NSDate *qtt_locationDate;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

