//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString;
@protocol LCQualityDelegate;

@interface LCQuality : NSObject
{
    NSString *_userId;
    id <LCQualityDelegate> _delegate;
    long long _useStart;
}

+ (id)sharedInstance;
@property(readonly, nonatomic) long long useStart; // @synthesize useStart=_useStart;
@property(nonatomic) __weak id <LCQualityDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (double)getSetarTime;
- (void)setSetarTime:(double)arg1;
- (int)memoryWarningCount;
- (void)del_fills:(id)arg1;
- (id)qualityFills;
- (void)addFillTask:(id)arg1;
- (void)stopMonitoring;
- (void)startMonitoring;
- (void)setCurrentPage:(id)arg1;
- (id)getCurrentPage;
- (void)installUncaughtExceptionHandler;
- (id)userID;
@property(readonly, nonatomic) long long usedDuration;
- (id)init;

@end

