//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, NSDictionary, NSString, NSURL;

@protocol LCRouterServiceProtocol <NSObject>
+ (void)showLocalPushTopView;
+ (NSDictionary *)appDelegateApnsHandlerLaunchOptions;
+ (_Bool)appDelegateApnsHandlerAllowedNotification;
+ (_Bool)appDelegateNeedForceShowRedEnvelope;
+ (_Bool)containsRootInArr:(NSArray *)arg1;
+ (_Bool)containsGlobalInArr:(NSArray *)arg1;
+ (NSDictionary *)pageCMDMap;
+ (NSDictionary *)pageIDMap;
+ (NSDictionary *)pageMap;
+ (_Bool)checkPageEnabledWithIDs:(NSArray *)arg1;
+ (NSArray *)rootPageIds;
+ (void)showAbout;
+ (void)showReport:(id)arg1;
+ (void)pushAdsWithDpUrl:(NSString *)arg1 dpCurl:(NSString *)arg2 cUrl:(NSString *)arg3 isLunchAd:(_Bool)arg4 needTrace:(_Bool)arg5;
+ (void)gotoQKInviteViewController;
+ (void)gotoQKMissionViewController;
+ (void)showWemediaPage:(NSString *)arg1;
+ (void)showWebView:(NSString *)arg1;
+ (void)mappingConfigWithControllerName:(NSURL *)arg1;
+ (_Bool)handleScheme:(id)arg1;
+ (_Bool)handleSchemeURL:(NSURL *)arg1;
@end

