//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString;

@protocol LCRouterInfoServiceProtocol <NSObject>
- (id)content_fontAttributes;
- (_Bool)content_isRead:(NSString *)arg1;
- (void)checkPushMsgs:(id)arg1 withBlock:(void (^)(_Bool))arg2;
- (void)checkPushMsgsLocal:(id)arg1 withBlock:(void (^)(_Bool))arg2;
- (void)launchCheckPushMsgs:(id)arg1 withBlock:(void (^)(_Bool))arg2;
- (void)dismissDislikeModelView;
- (void)gotoContentSearch:(id)arg1;
- (void)gotoCollectionWithKey:(NSString *)arg1;
- (void)gotoWemediaWithKey:(NSString *)arg1;
- (void)gotoPushBox;
- (void)gotoPhotoBrowser:(id)arg1 index:(long long)arg2;
- (void)gotoCommentDetail:(id)arg1;
- (void)gotoSubcript:(id)arg1;
- (void)pushContent:(id)arg1 src:(int)arg2;
@end

