//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "LCTableViewSectionData-Protocol.h"

@class NSMutableArray, NSString, UIView;

@interface LCTableViewSectionModel : NSObject <LCTableViewSectionData>
{
    NSMutableArray *_rowData;
    double _sectionFooterHeight;
    UIView *_sectionFooterView;
    double _sectionHeaderHeight;
    UIView *_sectionHeaderView;
}

@property(retain, nonatomic) UIView *sectionHeaderView; // @synthesize sectionHeaderView=_sectionHeaderView;
@property(nonatomic) double sectionHeaderHeight; // @synthesize sectionHeaderHeight=_sectionHeaderHeight;
@property(retain, nonatomic) UIView *sectionFooterView; // @synthesize sectionFooterView=_sectionFooterView;
@property(nonatomic) double sectionFooterHeight; // @synthesize sectionFooterHeight=_sectionFooterHeight;
@property(retain, nonatomic) NSMutableArray *rowData; // @synthesize rowData=_rowData;
- (void).cxx_destruct;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

