//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSDictionary, NSString;

@interface LCUserDefaults : NSObject
{
    _Bool _QKMonitorWhetherOpeKey;
    _Bool _QKMyFirstLogin;
    NSString *_DeviceToken;
    NSString *_h5_back_url;
    NSString *_using_h5_back_host;
    long long _RecordAlertNoobRedEnvelopeTimes;
    NSDictionary *_Rate_LaunchIntervalDaysInfo;
    NSDictionary *_Rate_UserActivityInfo;
    NSDictionary *_BindingMaster_UserActivityInfo;
}

@property(nonatomic) _Bool QKMyFirstLogin; // @synthesize QKMyFirstLogin=_QKMyFirstLogin;
@property(retain, nonatomic) NSDictionary *BindingMaster_UserActivityInfo; // @synthesize BindingMaster_UserActivityInfo=_BindingMaster_UserActivityInfo;
@property(retain, nonatomic) NSDictionary *Rate_UserActivityInfo; // @synthesize Rate_UserActivityInfo=_Rate_UserActivityInfo;
@property(retain, nonatomic) NSDictionary *Rate_LaunchIntervalDaysInfo; // @synthesize Rate_LaunchIntervalDaysInfo=_Rate_LaunchIntervalDaysInfo;
@property(nonatomic) long long RecordAlertNoobRedEnvelopeTimes; // @synthesize RecordAlertNoobRedEnvelopeTimes=_RecordAlertNoobRedEnvelopeTimes;
@property(copy, nonatomic) NSString *using_h5_back_host; // @synthesize using_h5_back_host=_using_h5_back_host;
@property(copy, nonatomic) NSString *h5_back_url; // @synthesize h5_back_url=_h5_back_url;
@property(nonatomic) _Bool QKMonitorWhetherOpeKey; // @synthesize QKMonitorWhetherOpeKey=_QKMonitorWhetherOpeKey;
@property(copy, nonatomic) NSString *DeviceToken; // @synthesize DeviceToken=_DeviceToken;
- (void).cxx_destruct;

@end

