//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "LCRouterUserServiceProtocol-Protocol.h"

@class NSString;

@interface LCUserService : NSObject <LCRouterUserServiceProtocol>
{
    CDUnknownBlockType _loginCompletion;
}

+ (id)sharedInstance;
@property(copy, nonatomic) CDUnknownBlockType loginCompletion; // @synthesize loginCompletion=_loginCompletion;
- (void).cxx_destruct;
- (void)rewardToLoginCompletion:(CDUnknownBlockType)arg1;
- (void)safeBlock_LoginCompletion;
- (void)qrcodeScanWithBlock:(CDUnknownBlockType)arg1;
- (void)gotoContactPageWithModel:(id)arg1;
- (void)gotoSettingPage;
- (void)gotoProfile;
- (void)gotoLoginWithType:(long long)arg1 fromPage:(long long)arg2 clipboardGif:(id)arg3 scheme:(id)arg4 withParam:(id)arg5 complete:(CDUnknownBlockType)arg6;
- (void)gotoLoginWithType:(long long)arg1 fromPage:(long long)arg2 clipboardGif:(id)arg3 scheme:(id)arg4 complete:(CDUnknownBlockType)arg5;
- (void)gotoLoginWithType:(long long)arg1 fromPage:(long long)arg2 clipboardGif:(id)arg3 scheme:(id)arg4;
- (void)gotoLoginWithScheme:(id)arg1;
- (void)gotoLoginWithClipboardGif:(id)arg1;
- (void)gotoLoginWithPrama:(id)arg1 withComplete:(CDUnknownBlockType)arg2;
- (void)gotoLoginWithComplete:(CDUnknownBlockType)arg1;
- (void)gotoLogin;
- (void)setComment_like_ids:(id)arg1;
- (void)add_comment_like_id:(id)arg1;
- (id)comment_like_ids;
- (_Bool)is_article_liked:(id)arg1;
- (void)like_article_id:(id)arg1;
- (void)logout:(_Bool)arg1;
- (_Bool)isLogin_gotoIfNot;
- (void)setAutoLogin:(_Bool)arg1;
- (_Bool)showRedDotForMyTab;
- (void)resetUser;
- (void)getMemberInfo:(CDUnknownBlockType)arg1;
- (void)refresh:(CDUnknownBlockType)arg1;
- (void)refresh;
- (id)userId;
- (void)setUesr:(id)arg1;
- (id)user;
- (void)setUserFolderPath:(id)arg1;
- (id)userFolderPath;
- (void)setLiked_ids:(id)arg1;
- (id)liked_ids;
- (void)setHeart:(id)arg1;
- (id)heart;
- (_Bool)isAutoLogin;
- (id)token;
- (void)setDelegate:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

