//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class CocoaClass, NSDictionary, NSUserDefaults;

@interface LCUserDefaultsManager : NSObject
{
    NSUserDefaults *_userDefault;
    CocoaClass *_classInfo;
    NSDictionary *_originMethods;
}

+ (id)shareManager;
- (void).cxx_destruct;
- (void)__injectCodeForSetterAndGetter;
- (void)removeAllData;
- (void)removeObjectsForKeys:(id)arg1;
- (void)removeObjectForKey:(id)arg1;
- (id)objectForKey:(id)arg1;
- (void)setObject:(id)arg1 forKey:(id)arg2;
- (void)unregisterClass;
- (void)registerClass:(Class)arg1;
- (id)init;

@end

