//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface LCUtility : NSObject
{
}

+ (id)month_dayStr;
+ (void)videoRestrictionPageNumArray:(id)arg1 withObject:(id)arg2 withblock:(CDUnknownBlockType)arg3;
+ (void)removeObjectForKeys:(id)arg1;
+ (void)setObjectsAndKeys:(id)arg1;
+ (void)removeObjectForKey:(id)arg1;
+ (void)setObject:(id)arg1 forKey:(id)arg2;
+ (id)objectForKey:(id)arg1;
+ (id)fetchLunchImageName;
+ (_Bool)isTFInstalled;
- (id)getIPAddresses;
- (id)getIPAddress:(_Bool)arg1;
- (id)ipV6;
- (id)ipV4;
- (id)ip;

@end

