//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "LEEBaseViewController.h"

@class LEEActionButton, NSMutableArray, UIScrollView, UIView;

@interface LEEActionSheetViewController : LEEBaseViewController
{
    _Bool isShowed;
    UIView *_containerView;
    UIScrollView *_actionSheetView;
    NSMutableArray *_actionSheetItemArray;
    NSMutableArray *_actionSheetActionArray;
    UIView *_actionSheetCancelActionSpaceView;
    LEEActionButton *_actionSheetCancelAction;
}

@property(retain, nonatomic) LEEActionButton *actionSheetCancelAction; // @synthesize actionSheetCancelAction=_actionSheetCancelAction;
@property(retain, nonatomic) UIView *actionSheetCancelActionSpaceView; // @synthesize actionSheetCancelActionSpaceView=_actionSheetCancelActionSpaceView;
@property(retain, nonatomic) NSMutableArray *actionSheetActionArray; // @synthesize actionSheetActionArray=_actionSheetActionArray;
@property(retain, nonatomic) NSMutableArray *actionSheetItemArray; // @synthesize actionSheetItemArray=_actionSheetItemArray;
@property(retain, nonatomic) UIScrollView *actionSheetView; // @synthesize actionSheetView=_actionSheetView;
@property(retain, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
- (void).cxx_destruct;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (void)closeAnimationsWithCompletionBlock:(CDUnknownBlockType)arg1;
- (void)showAnimationsWithCompletionBlock:(CDUnknownBlockType)arg1;
- (void)headerTapAction:(id)arg1;
- (void)cancelButtonAction:(id)arg1;
- (void)buttonAction:(id)arg1;
- (void)configActionSheet;
- (void)updateActionSheetLayoutWithViewWidth:(double)arg1 ViewHeight:(double)arg2;
- (void)updateActionSheetLayout;
- (void)viewSafeAreaInsetsDidChange;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)dealloc;

@end

