//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class LEEAlertWindow, LEEBaseViewController, NSMutableArray, UIWindow;

@interface LEEAlert : NSObject
{
    UIWindow *_mainWindow;
    LEEAlertWindow *_leeWindow;
    NSMutableArray *_queueArray;
    LEEBaseViewController *_viewController;
}

+ (void)closeWithCompletionBlock:(CDUnknownBlockType)arg1;
+ (void)clearQueue;
+ (void)continueQueueDisplay;
+ (void)configMainWindow:(id)arg1;
+ (id)getAlertWindow;
+ (id)actionsheet;
+ (id)alert;
+ (id)shareManager;
@property(retain, nonatomic) LEEBaseViewController *viewController; // @synthesize viewController=_viewController;
@property(retain, nonatomic) NSMutableArray *queueArray; // @synthesize queueArray=_queueArray;
@property(retain, nonatomic) LEEAlertWindow *leeWindow; // @synthesize leeWindow=_leeWindow;
@property(retain, nonatomic) UIWindow *mainWindow; // @synthesize mainWindow=_mainWindow;
- (void).cxx_destruct;

@end

