//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSAttributedString, NSString, UIColor, UIFont, UIImage;

@interface LEEAction : NSObject
{
    _Bool _isClickNotClose;
    long long _type;
    NSString *_title;
    NSString *_highlight;
    NSAttributedString *_attributedTitle;
    NSAttributedString *_attributedHighlight;
    UIFont *_font;
    UIColor *_titleColor;
    UIColor *_highlightColor;
    UIColor *_backgroundColor;
    UIColor *_backgroundHighlightColor;
    UIImage *_image;
    UIImage *_highlightImage;
    double _cornerRadius;
    double _height;
    double _borderWidth;
    UIColor *_borderColor;
    long long _borderPosition;
    CDUnknownBlockType _clickBlock;
    CDUnknownBlockType _updateBlock;
    struct UIEdgeInsets _insets;
    struct UIEdgeInsets _imageEdgeInsets;
    struct UIEdgeInsets _titleEdgeInsets;
}

@property(copy, nonatomic) CDUnknownBlockType updateBlock; // @synthesize updateBlock=_updateBlock;
@property(copy, nonatomic) CDUnknownBlockType clickBlock; // @synthesize clickBlock=_clickBlock;
@property(nonatomic) _Bool isClickNotClose; // @synthesize isClickNotClose=_isClickNotClose;
@property(nonatomic) long long borderPosition; // @synthesize borderPosition=_borderPosition;
@property(retain, nonatomic) UIColor *borderColor; // @synthesize borderColor=_borderColor;
@property(nonatomic) double borderWidth; // @synthesize borderWidth=_borderWidth;
@property(nonatomic) double height; // @synthesize height=_height;
@property(nonatomic) double cornerRadius; // @synthesize cornerRadius=_cornerRadius;
@property(nonatomic) struct UIEdgeInsets titleEdgeInsets; // @synthesize titleEdgeInsets=_titleEdgeInsets;
@property(nonatomic) struct UIEdgeInsets imageEdgeInsets; // @synthesize imageEdgeInsets=_imageEdgeInsets;
@property(nonatomic) struct UIEdgeInsets insets; // @synthesize insets=_insets;
@property(retain, nonatomic) UIImage *highlightImage; // @synthesize highlightImage=_highlightImage;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
@property(retain, nonatomic) UIColor *backgroundHighlightColor; // @synthesize backgroundHighlightColor=_backgroundHighlightColor;
@property(retain, nonatomic) UIColor *backgroundColor; // @synthesize backgroundColor=_backgroundColor;
@property(retain, nonatomic) UIColor *highlightColor; // @synthesize highlightColor=_highlightColor;
@property(retain, nonatomic) UIColor *titleColor; // @synthesize titleColor=_titleColor;
@property(retain, nonatomic) UIFont *font; // @synthesize font=_font;
@property(retain, nonatomic) NSAttributedString *attributedHighlight; // @synthesize attributedHighlight=_attributedHighlight;
@property(retain, nonatomic) NSAttributedString *attributedTitle; // @synthesize attributedTitle=_attributedTitle;
@property(retain, nonatomic) NSString *highlight; // @synthesize highlight=_highlight;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) long long type; // @synthesize type=_type;
- (void).cxx_destruct;
- (void)update;

@end

