//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "LEEBaseViewController.h"

@class NSMutableArray, UIScrollView, UIView;

@interface LEEAlertViewController : LEEBaseViewController
{
    double alertViewHeight;
    struct CGRect keyboardFrame;
    _Bool isShowingKeyboard;
    UIView *_containerView;
    UIScrollView *_alertView;
    NSMutableArray *_alertItemArray;
    NSMutableArray *_alertActionArray;
}

@property(retain, nonatomic) NSMutableArray *alertActionArray; // @synthesize alertActionArray=_alertActionArray;
@property(retain, nonatomic) NSMutableArray *alertItemArray; // @synthesize alertItemArray=_alertItemArray;
@property(retain, nonatomic) UIScrollView *alertView; // @synthesize alertView=_alertView;
@property(retain, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
- (void).cxx_destruct;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (id)findFirstResponder:(id)arg1;
- (void)closeAnimationsWithCompletionBlock:(CDUnknownBlockType)arg1;
- (void)showAnimationsWithCompletionBlock:(CDUnknownBlockType)arg1;
- (void)headerTapAction:(id)arg1;
- (void)buttonAction:(id)arg1;
- (void)configAlert;
- (void)updateAlertItemsLayout;
- (void)updateAlertLayoutWithViewWidth:(double)arg1 ViewHeight:(double)arg2;
- (void)updateAlertLayout;
- (void)viewSafeAreaInsetsDidChange;
- (void)viewDidLayoutSubviews;
- (void)keyboardWillChangeFrame:(id)arg1;
- (void)configNotification;
- (void)viewDidLoad;
- (void)dealloc;

@end

