//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MJRefreshComponent.h"

@class MJTipView, NSDate, NSMutableDictionary, NSString, UIActivityIndicatorView, UIImageView, UILabel;

@interface MJRefreshTipHeader : MJRefreshComponent
{
    UILabel *_lastUpdatedTimeLabel;
    UILabel *_stateLabel;
    UIImageView *_arrowView;
    _Bool _tipEnabel;
    _Bool _isTipAnimating;
    NSString *_lastUpdatedTimeKey;
    double _ignoredScrollViewContentInsetTop;
    CDUnknownBlockType _lastUpdatedTimeText;
    double _labelLeftInset;
    long long _activityIndicatorViewStyle;
    double _insetTDelta;
    NSMutableDictionary *_stateTitles;
    UIActivityIndicatorView *_loadingView;
    MJTipView *_tipView;
    unsigned long long _tipType;
    NSString *_tipText;
    struct UIEdgeInsets _originalEdgeInsets;
}

+ (id)headerWithRefreshingTarget:(id)arg1 refreshingAction:(SEL)arg2;
+ (id)headerWithRefreshingBlock:(CDUnknownBlockType)arg1;
@property(nonatomic) _Bool isTipAnimating; // @synthesize isTipAnimating=_isTipAnimating;
@property(nonatomic) _Bool tipEnabel; // @synthesize tipEnabel=_tipEnabel;
@property(copy, nonatomic) NSString *tipText; // @synthesize tipText=_tipText;
@property(nonatomic) unsigned long long tipType; // @synthesize tipType=_tipType;
@property(nonatomic) __weak MJTipView *tipView; // @synthesize tipView=_tipView;
@property(nonatomic) __weak UIActivityIndicatorView *loadingView; // @synthesize loadingView=_loadingView;
@property(retain, nonatomic) NSMutableDictionary *stateTitles; // @synthesize stateTitles=_stateTitles;
@property(nonatomic) double insetTDelta; // @synthesize insetTDelta=_insetTDelta;
@property(nonatomic) long long activityIndicatorViewStyle; // @synthesize activityIndicatorViewStyle=_activityIndicatorViewStyle;
@property(nonatomic) double labelLeftInset; // @synthesize labelLeftInset=_labelLeftInset;
@property(copy, nonatomic) CDUnknownBlockType lastUpdatedTimeText; // @synthesize lastUpdatedTimeText=_lastUpdatedTimeText;
@property(nonatomic) double ignoredScrollViewContentInsetTop; // @synthesize ignoredScrollViewContentInsetTop=_ignoredScrollViewContentInsetTop;
@property(copy, nonatomic) NSString *lastUpdatedTimeKey; // @synthesize lastUpdatedTimeKey=_lastUpdatedTimeKey;
@property(nonatomic) struct UIEdgeInsets originalEdgeInsets; // @synthesize originalEdgeInsets=_originalEdgeInsets;
- (void).cxx_destruct;
- (void)setTitle:(id)arg1 forState:(long long)arg2;
@property(readonly, nonatomic) NSDate *lastUpdatedTime;
- (void)endRefreshingWithType:(unsigned long long)arg1 text:(id)arg2;
- (void)endRefreshing;
- (void)tipAnimation;
- (void)normalAnimation;
- (void)setState:(long long)arg1;
- (void)configureTipText;
- (void)configureTipViewFrame;
- (void)setupSubViews;
- (void)scrollViewContentOffsetDidChange:(id)arg1;
- (void)placeSubviews;
- (void)prepare;
- (id)currentCalendar;
@property(readonly, nonatomic) __weak UIImageView *arrowView;
@property(readonly, nonatomic) __weak UILabel *lastUpdatedTimeLabel;
@property(readonly, nonatomic) __weak UILabel *stateLabel;
- (void)setupDefaultValue;

@end

