//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSArray, UIImageView;

@interface MyPageGuideView : UIView
{
    int _step;
    UIImageView *_guideImgView;
    NSArray *_guideImgArr;
}

+ (id)guideOnView:(id)arg1;
@property(retain, nonatomic) NSArray *guideImgArr; // @synthesize guideImgArr=_guideImgArr;
@property(retain, nonatomic) UIImageView *guideImgView; // @synthesize guideImgView=_guideImgView;
- (void).cxx_destruct;
- (void)tapToNext:(id)arg1;
- (void)commonInit;
- (id)initWithFrame:(struct CGRect)arg1;

@end

