//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSArray, UIButton, UIImageView;

@interface NetworkHintView : UIView
{
    UIImageView *_imgView;
    UIView *_backgroundView;
    UIButton *_cancelButton;
    UIButton *_settingButton;
    NSArray *_guideImgArr;
}

+ (void)removeNetworkHintViewFromSuperview:(id)arg1;
+ (id)showOnView:(id)arg1;
@property(retain, nonatomic) NSArray *guideImgArr; // @synthesize guideImgArr=_guideImgArr;
@property(retain, nonatomic) UIButton *settingButton; // @synthesize settingButton=_settingButton;
@property(retain, nonatomic) UIButton *cancelButton; // @synthesize cancelButton=_cancelButton;
@property(retain, nonatomic) UIView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(retain, nonatomic) UIImageView *imgView; // @synthesize imgView=_imgView;
- (void).cxx_destruct;
- (void)cancelAction;
- (void)settingAction;
- (void)commonInit;
- (id)initWithFrame:(struct CGRect)arg1;

@end

