//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BaseHeaderView.h"

@class QKButton, QKReadTime, UIButton, UIImageView, UILabel, UIView;

@interface NewHuiMyHeaderView : BaseHeaderView
{
    long long _itemCount;
    QKReadTime *_readTimeMode;
    UILabel *_nickName;
    UIButton *_avatar;
    QKButton *_lGold;
    QKButton *_lCash;
    QKButton *_lReadTime;
    UIImageView *_rewardImageView;
    UIImageView *_topBackgroundImageView;
    UIView *_cornerBackgroundView;
}

@property(retain, nonatomic) UIView *cornerBackgroundView; // @synthesize cornerBackgroundView=_cornerBackgroundView;
@property(retain, nonatomic) UIImageView *topBackgroundImageView; // @synthesize topBackgroundImageView=_topBackgroundImageView;
@property(retain, nonatomic) UIImageView *rewardImageView; // @synthesize rewardImageView=_rewardImageView;
@property(retain, nonatomic) QKButton *lReadTime; // @synthesize lReadTime=_lReadTime;
@property(retain, nonatomic) QKButton *lCash; // @synthesize lCash=_lCash;
@property(retain, nonatomic) QKButton *lGold; // @synthesize lGold=_lGold;
@property(retain, nonatomic) UIButton *avatar; // @synthesize avatar=_avatar;
@property(retain, nonatomic) UILabel *nickName; // @synthesize nickName=_nickName;
- (void).cxx_destruct;
- (void)addSels:(SEL)arg1 profile:(SEL)arg2 onGold:(SEL)arg3 onCash:(SEL)arg4 onReadTime:(SEL)arg5 toTarget:(id)arg6;
- (void)setWithObject:(id)arg1;
- (void)updateItemConfigure;
- (id)initWithObject:(id)arg1;

@end

