//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "NWBigRedEnvelopeViewDelegate-Protocol.h"

@class NSString, NWBigRedEnvelopeView, NWSmallRedEnvelopeView, NoobRedEnvelopeEntity, UIView;

@interface NoobWelfareManager : NSObject <NWBigRedEnvelopeViewDelegate>
{
    _Bool _displayBigRedEnvelope;
    NoobRedEnvelopeEntity *_config;
    NWSmallRedEnvelopeView *_smallRedEnv;
    NWBigRedEnvelopeView *_bigRedEnv;
    UIView *_superView;
}

+ (id)managerWithView:(id)arg1;
@property(nonatomic) __weak UIView *superView; // @synthesize superView=_superView;
@property(retain, nonatomic) NWBigRedEnvelopeView *bigRedEnv; // @synthesize bigRedEnv=_bigRedEnv;
@property(retain, nonatomic) NWSmallRedEnvelopeView *smallRedEnv; // @synthesize smallRedEnv=_smallRedEnv;
@property(nonatomic) _Bool displayBigRedEnvelope; // @synthesize displayBigRedEnvelope=_displayBigRedEnvelope;
@property(retain, nonatomic) NoobRedEnvelopeEntity *config; // @synthesize config=_config;
- (void).cxx_destruct;
- (void)tapSmallEnvelope;
- (void)hideAll;
- (void)redEnvelopeViewDidDimiss:(id)arg1;
- (void)showBigRedEnvelope;
- (void)showSmallRedEnvelope;
- (void)getRedEnvConfig:(CDUnknownBlockType)arg1 completion:(CDUnknownBlockType)arg2;
- (void)getRedEnvConfig:(CDUnknownBlockType)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

