//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QKView.h"

#import "UIScrollViewDelegate-Protocol.h"

@class NSString, QKActivityCardModel, UIButton, UIControl, UIImageView, UIScrollView;

@interface NormalCardAlertView : QKView <UIScrollViewDelegate>
{
    UIScrollView *_scrollView;
    UIImageView *_imageView;
    UIControl *_overlayView;
    UIButton *_closeBtn;
    QKActivityCardModel *_currentCardModel;
}

+ (void)show:(id)arg1;
+ (void)dismiss;
@property(retain, nonatomic) QKActivityCardModel *currentCardModel; // @synthesize currentCardModel=_currentCardModel;
@property(retain, nonatomic) UIButton *closeBtn; // @synthesize closeBtn=_closeBtn;
@property(retain, nonatomic) UIControl *overlayView; // @synthesize overlayView=_overlayView;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
- (void).cxx_destruct;
- (void)dismissActivity:(id)arg1;
- (void)showActivityDetail:(id)arg1;
- (void)dismiss;
- (void)show;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

