//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSAttributedString.h>

@interface NSAttributedString (V5Emotion)
+ (id)attachmentsForAttributedString:(id)arg1;
+ (id)getFaceMap;
+ (id)emotionAttributedStringFrom:(id)arg1 attributes:(id)arg2;
+ (struct CGRect)boundsForString:(id)arg1 size:(struct CGSize)arg2 attributes:(id)arg3;
- (struct CGRect)boundsWithSize:(struct CGSize)arg1;
@end

