//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSDictionary.h>

@interface NSDictionary (adeaz_dic)
- (id)getNumberValueForKey:(id)arg1;
- (id)getDictionaryValueForKey:(id)arg1;
- (id)getArrayValueForKey:(id)arg1;
- (float)getFloatValueForKey:(id)arg1;
- (double)getDoubleValueForKey:(id)arg1;
- (long long)getIntegerValueForKey:(id)arg1;
- (id)getStringValueForKey:(id)arg1;
@end

