//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSDictionary.h>

@interface NSDictionary (InnoOpt)
- (long long)optLongLongForKey:(id)arg1 defaultValue:(long long)arg2;
- (double)optFloatForKey:(id)arg1 defaultValue:(double)arg2;
- (id)optArrayForKey:(id)arg1 defaultValue:(id)arg2;
- (_Bool)optBoolForKey:(id)arg1 defaultValue:(_Bool)arg2;
- (long long)optIntegerForKey:(id)arg1 defaultValue:(long long)arg2;
- (id)optDictionaryForKey:(id)arg1 defaultValue:(id)arg2;
- (id)optStringForKey:(id)arg1 defaultValue:(id)arg2;
@end

