//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSFileManager.h>

@interface NSFileManager (BFKit)
+ (_Bool)setAppSettingsForObject:(id)arg1 forKey:(id)arg2;
+ (id)getAppSettingsForObjectWithKey:(id)arg1;
+ (_Bool)setSettings:(id)arg1 object:(id)arg2 forKey:(id)arg3;
+ (id)getSettings:(id)arg1 objectForKey:(id)arg2;
+ (_Bool)renameFileFromDirectory:(long long)arg1 atPath:(id)arg2 withOldName:(id)arg3 andNewName:(id)arg4;
+ (_Bool)duplicateFileAtPath:(id)arg1 toNewPath:(id)arg2;
+ (_Bool)moveLocalFile:(id)arg1 fromDirectory:(long long)arg2 toDirectory:(long long)arg3 withFolderName:(id)arg4;
+ (_Bool)moveLocalFile:(id)arg1 fromDirectory:(long long)arg2 toDirectory:(long long)arg3;
+ (_Bool)deleteFile:(id)arg1 fromDirectory:(long long)arg2;
+ (id)fileSize:(id)arg1 fromDirectory:(long long)arg2;
+ (id)getCacheDirectoryForFile:(id)arg1;
+ (id)getLibraryDirectoryForFile:(id)arg1;
+ (id)getDocumentsDirectoryForFile:(id)arg1;
+ (id)getBundlePathForFile:(id)arg1;
+ (id)loadArrayFromPath:(long long)arg1 withFilename:(id)arg2;
+ (_Bool)saveArrayToPath:(long long)arg1 withFilename:(id)arg2 array:(id)arg3;
+ (id)readTextFile:(id)arg1 ofType:(id)arg2;
@end

