//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSString.h>

@interface NSString (Encrypt)
- (id)__toHexString:(char *)arg1 length:(unsigned int)arg2;
- (unsigned int)__UTF8Length;
- (id)ol_SHA256;
- (id)ol_SHA1;
- (id)ol_MD5;
- (id)ol_base64Encode;
@end

