//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NoobRedEnvelopeEntity, QKButton, UIButton, UIImageView, UILabel;

@interface NWBigRedEnvelopeContentView : UIView
{
    CDUnknownBlockType _redEnvelopeDidOpen;
    CDUnknownBlockType _didPressWithdrawButtonAction;
    NoobRedEnvelopeEntity *_config;
    UIView *_topView;
    UILabel *_title;
    UILabel *_subtitle;
    UILabel *_despTitle;
    UILabel *_tipTitle;
    UIImageView *_sealView;
    QKButton *_openBtn;
    UIView *_bottomView;
    UILabel *_bottomTitle;
    UIButton *_withdrawBtn;
    UIImageView *_highlightImageView;
    UILabel *_bottomHint;
    UILabel *_bottomHintLine;
}

@property(retain, nonatomic) UILabel *bottomHintLine; // @synthesize bottomHintLine=_bottomHintLine;
@property(retain, nonatomic) UILabel *bottomHint; // @synthesize bottomHint=_bottomHint;
@property(retain, nonatomic) UIImageView *highlightImageView; // @synthesize highlightImageView=_highlightImageView;
@property(retain, nonatomic) UIButton *withdrawBtn; // @synthesize withdrawBtn=_withdrawBtn;
@property(retain, nonatomic) UILabel *bottomTitle; // @synthesize bottomTitle=_bottomTitle;
@property(retain, nonatomic) UIView *bottomView; // @synthesize bottomView=_bottomView;
@property(retain, nonatomic) QKButton *openBtn; // @synthesize openBtn=_openBtn;
@property(retain, nonatomic) UIImageView *sealView; // @synthesize sealView=_sealView;
@property(retain, nonatomic) UILabel *tipTitle; // @synthesize tipTitle=_tipTitle;
@property(retain, nonatomic) UILabel *despTitle; // @synthesize despTitle=_despTitle;
@property(retain, nonatomic) UILabel *subtitle; // @synthesize subtitle=_subtitle;
@property(retain, nonatomic) UILabel *title; // @synthesize title=_title;
@property(retain, nonatomic) UIView *topView; // @synthesize topView=_topView;
@property(retain, nonatomic) NoobRedEnvelopeEntity *config; // @synthesize config=_config;
@property(copy, nonatomic) CDUnknownBlockType didPressWithdrawButtonAction; // @synthesize didPressWithdrawButtonAction=_didPressWithdrawButtonAction;
@property(copy, nonatomic) CDUnknownBlockType redEnvelopeDidOpen; // @synthesize redEnvelopeDidOpen=_redEnvelopeDidOpen;
- (void).cxx_destruct;
- (id)getAmountImageDict;
- (id)getAmountView:(id)arg1;
- (void)pressWithdrawButtonAction:(id)arg1;
- (void)pressOpenButtonAction:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

