//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "LCSystemFunction.h"

#import "UIImagePickerControllerDelegate-Protocol.h"
#import "UINavigationControllerDelegate-Protocol.h"

@class NSString, UIImagePickerController;

@interface OLSystemImagePicker : LCSystemFunction <UINavigationControllerDelegate, UIImagePickerControllerDelegate>
{
    UIImagePickerController *_imagePicker;
    CDUnknownBlockType _pickImageCallBack;
    CDUnknownBlockType _unavailableHolder;
    CDUnknownBlockType _unavailableCallBack;
    CDUnknownBlockType _cancelCallBack;
}

@property(copy, nonatomic) CDUnknownBlockType cancelCallBack; // @synthesize cancelCallBack=_cancelCallBack;
@property(copy, nonatomic) CDUnknownBlockType unavailableCallBack; // @synthesize unavailableCallBack=_unavailableCallBack;
@property(copy, nonatomic) CDUnknownBlockType unavailableHolder; // @synthesize unavailableHolder=_unavailableHolder;
@property(copy, nonatomic) CDUnknownBlockType pickImageCallBack; // @synthesize pickImageCallBack=_pickImageCallBack;
@property(retain, nonatomic) UIImagePickerController *imagePicker; // @synthesize imagePicker=_imagePicker;
- (void).cxx_destruct;
- (void)imagePickerControllerDidCancel:(id)arg1;
- (void)imagePickerController:(id)arg1 didFinishPickingMediaWithInfo:(id)arg2;
@property(readonly, copy, nonatomic) CDUnknownBlockType cancel;
@property(readonly, copy, nonatomic) CDUnknownBlockType unavailable;
@property(readonly, copy, nonatomic) CDUnknownBlockType pickImage;
@property(readonly, copy, nonatomic) CDUnknownBlockType album;
@property(readonly, copy, nonatomic) CDUnknownBlockType camera;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

