//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QKTableViewCell.h"

#import "LCTableViewCellConfigure-Protocol.h"

@class NSString, PromptTaskScheduleView, QKButton, UILabel, UIView;

@interface PromptTaskCell : QKTableViewCell <LCTableViewCellConfigure>
{
    UILabel *_title;
    UILabel *_countDown;
    UILabel *_tipTitle;
    UIView *_bottomView;
    PromptTaskScheduleView *_taskView;
    QKButton *_withdrawBtn;
}

@property(retain, nonatomic) QKButton *withdrawBtn; // @synthesize withdrawBtn=_withdrawBtn;
@property(retain, nonatomic) PromptTaskScheduleView *taskView; // @synthesize taskView=_taskView;
@property(retain, nonatomic) UIView *bottomView; // @synthesize bottomView=_bottomView;
@property(retain, nonatomic) UILabel *tipTitle; // @synthesize tipTitle=_tipTitle;
@property(retain, nonatomic) UILabel *countDown; // @synthesize countDown=_countDown;
@property(retain, nonatomic) UILabel *title; // @synthesize title=_title;
- (void).cxx_destruct;
- (void)highlightNumberOnLabel:(id)arg1;
- (void)pressWithdrawBtnAction:(id)arg1;
- (void)setImageGifData:(id)arg1 onBtn:(id)arg2;
- (void)update:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)configureCellWithModel:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

