//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSArray, UIImageView;

@interface PromptTaskScheduleView : UIView
{
    NSArray *_taskNodeTitles;
    double _currTaskProgress;
    UIView *_progressBarBackground;
    UIImageView *_progressBar;
    NSArray *_taskNodes;
}

@property(retain, nonatomic) NSArray *taskNodes; // @synthesize taskNodes=_taskNodes;
@property(retain, nonatomic) UIImageView *progressBar; // @synthesize progressBar=_progressBar;
@property(retain, nonatomic) UIView *progressBarBackground; // @synthesize progressBarBackground=_progressBarBackground;
@property(nonatomic) double currTaskProgress; // @synthesize currTaskProgress=_currTaskProgress;
@property(retain, nonatomic) NSArray *taskNodeTitles; // @synthesize taskNodeTitles=_taskNodeTitles;
- (void).cxx_destruct;
- (void)setTaskFinished:(unsigned long long)arg1;
- (unsigned long long)currentTaskNo;
- (void)setupSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

