//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSString, UIImageView, UILabel;

@interface PromptTaskNode : UIView
{
    _Bool _highlighted;
    _Bool _finished;
    NSString *_title;
    UIImageView *_node;
    UILabel *_nodeTitle;
}

@property(retain, nonatomic) UILabel *nodeTitle; // @synthesize nodeTitle=_nodeTitle;
@property(retain, nonatomic) UIImageView *node; // @synthesize node=_node;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) _Bool finished; // @synthesize finished=_finished;
@property(nonatomic) _Bool highlighted; // @synthesize highlighted=_highlighted;
- (void).cxx_destruct;
- (void)setupSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

