//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "LCBaseModel.h"

@class NSString;

@interface PushBoxBannerModel : LCBaseModel
{
    int _enable;
    NSString *_msg;
    NSString *_url;
}

@property(retain, nonatomic) NSString *url; // @synthesize url=_url;
@property(retain, nonatomic) NSString *msg; // @synthesize msg=_msg;
@property(nonatomic) int enable; // @synthesize enable=_enable;
- (void).cxx_destruct;
- (id)initWithAttribute:(id)arg1;

@end

