//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "LCBaseModel.h"

@class NSMutableArray;

@interface QKActivityCardModelList : LCBaseModel
{
    NSMutableArray *_activityCards;
    NSMutableArray *_availableActivityCards;
}

@property(retain, nonatomic) NSMutableArray *availableActivityCards; // @synthesize availableActivityCards=_availableActivityCards;
@property(retain, nonatomic) NSMutableArray *activityCards; // @synthesize activityCards=_activityCards;
- (void).cxx_destruct;
- (void)refreshAvailableActivityCards;
- (id)initWithAttribute:(id)arg1;

@end

