//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "LCBaseModel.h"

@class NSArray, NSDictionary, NSString;

@interface QKActivityCardModel : LCBaseModel
{
    NSString *_pic;
    NSString *_url;
    NSString *_id;
    NSString *_source_id;
    long long _showTimes;
    NSString *_card_type;
    NSDictionary *_card_member;
    NSDictionary *_card_description;
    NSArray *_card_position;
    NSArray *_card_condition;
}

@property(copy, nonatomic) NSArray *card_condition; // @synthesize card_condition=_card_condition;
@property(copy, nonatomic) NSArray *card_position; // @synthesize card_position=_card_position;
@property(copy, nonatomic) NSDictionary *card_description; // @synthesize card_description=_card_description;
@property(copy, nonatomic) NSDictionary *card_member; // @synthesize card_member=_card_member;
@property(copy, nonatomic) NSString *card_type; // @synthesize card_type=_card_type;
@property(nonatomic) long long showTimes; // @synthesize showTimes=_showTimes;
@property(retain, nonatomic) NSString *source_id; // @synthesize source_id=_source_id;
@property(retain, nonatomic) NSString *id; // @synthesize id=_id;
@property(retain, nonatomic) NSString *url; // @synthesize url=_url;
@property(retain, nonatomic) NSString *pic; // @synthesize pic=_pic;
- (void).cxx_destruct;
- (id)initWithAttribute:(id)arg1;

@end

