//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "LCBaseModel.h"

@class NSDictionary;

@interface QKAdsSourceNameModel : LCBaseModel
{
    _Bool _enable;
    NSDictionary *_source_map;
}

@property(retain, nonatomic) NSDictionary *source_map; // @synthesize source_map=_source_map;
@property(nonatomic) _Bool enable; // @synthesize enable=_enable;
- (void).cxx_destruct;
- (id)initWithAttribute:(id)arg1;

@end

