//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "LCBaseModel.h"

@class NSArray, NSString;

@interface QKAdsNativeAdObject : LCBaseModel
{
    _Bool _isLunchAd;
    _Bool _available;
    NSString *_adid;
    NSString *_slotid;
    NSString *_adslotid;
    NSString *_appId;
    NSString *_l;
    NSString *_rbt;
    long long _needTrace;
    NSString *_ad_type;
    NSString *_adunion;
    NSString *_title;
    NSString *_desc;
    NSString *_image;
    NSString *_icon;
    NSArray *_ext_urls;
    NSString *_c_url;
    NSString *_dp_url;
    NSString *_dp_curl;
    NSArray *_viewShowLogUrl;
    NSArray *_viewClickUrl;
    NSString *_pvid;
    NSString *_date;
}

@property(nonatomic) _Bool available; // @synthesize available=_available;
@property(retain, nonatomic) NSString *date; // @synthesize date=_date;
@property(retain, nonatomic) NSString *pvid; // @synthesize pvid=_pvid;
@property(retain, nonatomic) NSArray *viewClickUrl; // @synthesize viewClickUrl=_viewClickUrl;
@property(retain, nonatomic) NSArray *viewShowLogUrl; // @synthesize viewShowLogUrl=_viewShowLogUrl;
@property(retain, nonatomic) NSString *dp_curl; // @synthesize dp_curl=_dp_curl;
@property(retain, nonatomic) NSString *dp_url; // @synthesize dp_url=_dp_url;
@property(retain, nonatomic) NSString *c_url; // @synthesize c_url=_c_url;
@property(retain, nonatomic) NSArray *ext_urls; // @synthesize ext_urls=_ext_urls;
@property(retain, nonatomic) NSString *icon; // @synthesize icon=_icon;
@property(retain, nonatomic) NSString *image; // @synthesize image=_image;
@property(retain, nonatomic) NSString *desc; // @synthesize desc=_desc;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) NSString *adunion; // @synthesize adunion=_adunion;
@property(retain, nonatomic) NSString *ad_type; // @synthesize ad_type=_ad_type;
@property(nonatomic) _Bool isLunchAd; // @synthesize isLunchAd=_isLunchAd;
@property(nonatomic) long long needTrace; // @synthesize needTrace=_needTrace;
@property(retain, nonatomic) NSString *rbt; // @synthesize rbt=_rbt;
@property(retain, nonatomic) NSString *l; // @synthesize l=_l;
@property(retain, nonatomic) NSString *appId; // @synthesize appId=_appId;
@property(retain, nonatomic) NSString *adslotid; // @synthesize adslotid=_adslotid;
@property(retain, nonatomic) NSString *slotid; // @synthesize slotid=_slotid;
@property(retain, nonatomic) NSString *adid; // @synthesize adid=_adid;
- (void).cxx_destruct;
- (id)dictionary;
- (id)initWithDictionary:(id)arg1;
- (id)initWithAttribute:(id)arg1;

@end

