//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QKBaseAlertView.h"

@interface QKAPNSAlertView : QKBaseAlertView
{
    double _displayTime;
}

+ (_Bool)isAlert;
+ (id)alertWithType:(long long)arg1;
@property(nonatomic) double displayTime; // @synthesize displayTime=_displayTime;
- (void)jPush;
- (void)uPush;
- (void)dismiss;
- (void)cancle:(id)arg1;
- (void)confirm:(id)arg1;
- (void)setUpWithType:(long long)arg1;

@end

