//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "LCBaseModel.h"

@interface QKAppStoreScoreRemind : LCBaseModel
{
    int _enable;
    int _active_day;
}

@property(nonatomic) int active_day; // @synthesize active_day=_active_day;
@property(nonatomic) int enable; // @synthesize enable=_enable;
- (id)initWithAttribute:(id)arg1;

@end

