//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QKView.h"

@class BaiduMobAdNativeAdView, QKAdvert, UIButton, UILabel;

@interface QKBaseAdvertView : QKView
{
    UILabel *_textLabel;
    UIButton *_typeBtn;
    UILabel *_brandLabel;
    BaiduMobAdNativeAdView *_baiduNativeAdView;
    QKAdvert *_object;
}

@property(retain, nonatomic) QKAdvert *object; // @synthesize object=_object;
@property(retain, nonatomic) BaiduMobAdNativeAdView *baiduNativeAdView; // @synthesize baiduNativeAdView=_baiduNativeAdView;
@property(retain, nonatomic) UILabel *brandLabel; // @synthesize brandLabel=_brandLabel;
@property(retain, nonatomic) UIButton *typeBtn; // @synthesize typeBtn=_typeBtn;
@property(retain, nonatomic) UILabel *textLabel; // @synthesize textLabel=_textLabel;
- (void).cxx_destruct;
- (void)confignTypeBtnWith:(_Bool)arg1;
- (struct CGSize)sizeWithString:(id)arg1 font:(id)arg2 contentSize:(struct CGSize)arg3;
- (void)update:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

