//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "LCBaseModel.h"

@class NSString, QKAdvert;

@interface QKBanner : LCBaseModel
{
    NSString *_image;
    NSString *_link;
    NSString *_type;
    long long _slotID;
    QKAdvert *_bannerAdvert;
}

@property(retain, nonatomic) QKAdvert *bannerAdvert; // @synthesize bannerAdvert=_bannerAdvert;
@property(nonatomic) long long slotID; // @synthesize slotID=_slotID;
@property(retain, nonatomic) NSString *type; // @synthesize type=_type;
@property(retain, nonatomic) NSString *link; // @synthesize link=_link;
@property(retain, nonatomic) NSString *image; // @synthesize image=_image;
- (void).cxx_destruct;
- (id)initWithAttribute:(id)arg1;

@end

