//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UINavigationController.h>

@class NSDate, QKTabBarItemModel;

@interface QKBaseNavigationController : UINavigationController
{
    _Bool _is_from_pop;
    NSDate *_start_date;
    NSDate *_end_date;
    QKTabBarItemModel *_tabBarItemModel;
}

@property(retain, nonatomic) QKTabBarItemModel *tabBarItemModel; // @synthesize tabBarItemModel=_tabBarItemModel;
@property(nonatomic) _Bool is_from_pop; // @synthesize is_from_pop=_is_from_pop;
@property(retain, nonatomic) NSDate *end_date; // @synthesize end_date=_end_date;
@property(retain, nonatomic) NSDate *start_date; // @synthesize start_date=_start_date;
- (void).cxx_destruct;
- (void)updateTabBar;
- (void)report;
- (void)start;
- (id)childViewControllerForStatusBarStyle;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (id)rootViewController_qk;
- (id)rootClassString;
- (id)initWithTabBarItemModel_web:(id)arg1;
- (id)initWithTabBarItemModel:(id)arg1;

@end

