//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "LCSocialDelegate-Protocol.h"
#import "V5ChatViewDelegate-Protocol.h"

@class NSDate, NSMutableDictionary, NSString, PageFill, QKNavigationBar, QKRootViewController, UILabel;

@interface QKBaseViewController : UIViewController <V5ChatViewDelegate, LCSocialDelegate>
{
    _Bool _lanchByNotifation;
    _Bool _is_fobi_need_back_icon;
    _Bool _isFromAPNs;
    QKNavigationBar *_qkNavigationBar;
    QKRootViewController *_qkTabBarController;
    NSString *_qkTitle;
    NSDate *_start_date;
    NSDate *_end_date;
    PageFill *_fill;
    long long _popType;
    NSString *_memberinfo_menu_key;
    NSString *_cmd;
    NSMutableDictionary *_requests;
    UILabel *_textLabel;
}

@property(retain, nonatomic) UILabel *textLabel; // @synthesize textLabel=_textLabel;
@property(nonatomic) _Bool isFromAPNs; // @synthesize isFromAPNs=_isFromAPNs;
@property(retain, nonatomic) NSMutableDictionary *requests; // @synthesize requests=_requests;
@property(nonatomic) _Bool is_fobi_need_back_icon; // @synthesize is_fobi_need_back_icon=_is_fobi_need_back_icon;
@property(nonatomic) _Bool lanchByNotifation; // @synthesize lanchByNotifation=_lanchByNotifation;
@property(copy, nonatomic) NSString *cmd; // @synthesize cmd=_cmd;
@property(copy, nonatomic) NSString *memberinfo_menu_key; // @synthesize memberinfo_menu_key=_memberinfo_menu_key;
@property(nonatomic) long long popType; // @synthesize popType=_popType;
@property(retain, nonatomic) PageFill *fill; // @synthesize fill=_fill;
@property(retain, nonatomic) NSDate *end_date; // @synthesize end_date=_end_date;
@property(retain, nonatomic) NSDate *start_date; // @synthesize start_date=_start_date;
@property(retain, nonatomic) NSString *qkTitle; // @synthesize qkTitle=_qkTitle;
@property(retain, nonatomic) QKRootViewController *qkTabBarController; // @synthesize qkTabBarController=_qkTabBarController;
@property(retain, nonatomic) QKNavigationBar *qkNavigationBar; // @synthesize qkNavigationBar=_qkNavigationBar;
- (void).cxx_destruct;
- (void)beginRefreshing;
@property(readonly, copy, nonatomic) NSString *pageCmd;
@property(readonly, copy, nonatomic) NSString *pageId;
- (id)getSocial;
- (void)social:(id)arg1 systemShareFail:(id)arg2 platform:(long long)arg3;
- (void)social:(id)arg1 withReportModel:(id)arg2;
- (void)social:(id)arg1 withSLComposeController:(id)arg2;
- (void)social:(id)arg1 withActivityController:(id)arg2;
- (void)social:(id)arg1 withParam:(id)arg2 handler:(CDUnknownBlockType)arg3;
- (void)social:(id)arg1 withWXParam:(id)arg2;
- (void)social:(id)arg1 withContentParam:(id)arg2;
- (_Bool)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(long long)arg3 info:(id)arg4;
- (_Bool)setIsRequesting:(_Bool)arg1 ForKey:(id)arg2;
- (void)clientViewController:(id)arg1 ServingStatusChange:(long long)arg2;
- (void)onClientViewConnect;
- (void)clientViewDidDisappear;
- (void)clientViewWillDisappear;
- (void)clientViewDidAppear;
- (void)clientViewWillAppear;
- (void)__addNavigationBarForChatView;
- (void)openKF;
- (void)handleUIApplicationWillChangeStatusBarFrameNotification:(id)arg1;
- (void)handleUIApplicatioDidEnterBackground:(id)arg1;
- (void)handleUIApplicatioDidEnterForeground:(id)arg1;
- (void)trackEvent:(id)arg1;
- (id)classString;
- (void)close;
- (void)back;
- (void)showBack:(_Bool)arg1;
- (void)setTitle:(id)arg1;
- (void)themeTypeChange;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)setupUnique;
- (void)viewDidLoad;
- (id)init;
- (void)dealloc;
- (void)popped;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

