//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QKBaseViewController.h"

#import "IMYWebViewDelegate-Protocol.h"
#import "LCActionSheetDelegate-Protocol.h"
#import "LCInviteShareDelegate-Protocol.h"
#import "LCWebErrorViewDelegate-Protocol.h"
#import "TSWebViewDelegate-Protocol.h"

@class IMYWebView, InviteShareMod, JavaScriptOC, LCWebErrorView, NJKWebViewProgressView, NSDate, NSMutableArray, NSString, NSURLRequest;

@interface QKBaseWebViewController : QKBaseViewController <IMYWebViewDelegate, LCActionSheetDelegate, LCWebErrorViewDelegate, TSWebViewDelegate, LCInviteShareDelegate>
{
    long long _address_load_count;
    long long _image_q;
    long long _image_selected;
    NSDate *_request_start_time;
    NSDate *_request_end_time;
    _Bool _request_time_report;
    long long _cdn_ecount;
    _Bool _authed;
    _Bool _from_login;
    _Bool _backed;
    _Bool _is_lunch_ad;
    _Bool _is_ad;
    _Bool _needTrace;
    _Bool _isFromOpenView;
    _Bool _js_brage_from;
    NJKWebViewProgressView *_progressView;
    JavaScriptOC *_javaScript;
    NSString *_url;
    NSString *_callback;
    NSString *_origin_url;
    NSString *_request_url;
    NSString *_html;
    NSURLRequest *_originRequest;
    NSString *_comment_id;
    NSString *_content_id;
    NSString *_value;
    NSURLRequest *_request;
    NSMutableArray *_historyStack;
    InviteShareMod *_inviteShare;
    IMYWebView *_webView;
    LCWebErrorView *_eroView;
}

@property(retain, nonatomic) LCWebErrorView *eroView; // @synthesize eroView=_eroView;
@property(retain, nonatomic) IMYWebView *webView; // @synthesize webView=_webView;
@property(retain, nonatomic) InviteShareMod *inviteShare; // @synthesize inviteShare=_inviteShare;
@property(retain, nonatomic) NSMutableArray *historyStack; // @synthesize historyStack=_historyStack;
@property(retain, nonatomic) NSURLRequest *request; // @synthesize request=_request;
@property(retain, nonatomic) NSString *value; // @synthesize value=_value;
@property(retain, nonatomic) NSString *content_id; // @synthesize content_id=_content_id;
@property(retain, nonatomic) NSString *comment_id; // @synthesize comment_id=_comment_id;
@property(retain, nonatomic) NSURLRequest *originRequest; // @synthesize originRequest=_originRequest;
@property(nonatomic) _Bool js_brage_from; // @synthesize js_brage_from=_js_brage_from;
@property(copy, nonatomic) NSString *html; // @synthesize html=_html;
@property(copy, nonatomic) NSString *request_url; // @synthesize request_url=_request_url;
@property(copy, nonatomic) NSString *origin_url; // @synthesize origin_url=_origin_url;
@property(copy, nonatomic) NSString *callback; // @synthesize callback=_callback;
@property(copy, nonatomic) NSString *url; // @synthesize url=_url;
@property(nonatomic) _Bool isFromOpenView; // @synthesize isFromOpenView=_isFromOpenView;
@property(nonatomic) _Bool needTrace; // @synthesize needTrace=_needTrace;
@property(nonatomic) _Bool is_ad; // @synthesize is_ad=_is_ad;
@property(retain, nonatomic) JavaScriptOC *javaScript; // @synthesize javaScript=_javaScript;
@property(nonatomic) _Bool is_lunch_ad; // @synthesize is_lunch_ad=_is_lunch_ad;
@property(retain, nonatomic) NJKWebViewProgressView *progressView; // @synthesize progressView=_progressView;
- (void).cxx_destruct;
- (void)openUrl:(id)arg1;
- (_Bool)getBlackListArrayWithUrl:(id)arg1;
- (_Bool)needOpenUrl:(id)arg1;
- (id)webViewEx;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)lcInviteShare:(id)arg1 withQuCodeURL:(id)arg2;
- (void)uploadFile:(id)arg1 value:(long long)arg2;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)showError:(id)arg1 webView:(id)arg2;
- (void)notification_reload_subcript:(id)arg1;
- (void)loginCallBack;
- (void)back;
- (void)didReport;
- (void)didReload;
- (void)webView:(id)arg1 didFailLoadWithError:(id)arg2;
- (void)webViewDidFinishLoad:(id)arg1;
- (void)webViewDidStartLoad:(id)arg1;
- (void)webView:(id)arg1 didCreateJavaScriptContext:(id)arg2;
- (_Bool)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(long long)arg3;
- (void)loadHTML;
- (id)getHttpsUrl:(id)arg1;
- (id)appendKeywordIntoBaseURL:(id)arg1;
- (id)baseURL;
- (void)beginRefeshing;
- (void)setupNavigationBar;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)classString;
- (id)initWithUrl:(id)arg1;
- (id)initWithRequest:(id)arg1;
- (void)clearWebView;
- (void)dealloc;
- (void)image:(id)arg1 didFinishSavingWithError:(id)arg2 contextInfo:(void *)arg3;
- (id)handlePics:(id)arg1;
- (id)drawMark:(id)arg1 object:(id)arg2;
- (id)drawQRCode:(id)arg1 object:(id)arg2;
- (void)login:(id)arg1;
- (void)attAction:(id)arg1 callback:(id)arg2;
- (void)payOrder:(id)arg1;
- (void)uploadAddressBook:(id)arg1 count:(long long)arg2;
- (void)fetchAddressBook:(long long)arg1;
- (void)shareYQ:(long long)arg1;
- (void)redPacket:(id)arg1;
- (id)dictionaryWithJsonString:(id)arg1;
- (void)targetIsReport:(id)arg1;
- (void)targetIsPay:(id)arg1;
- (void)targetIsGift:(id)arg1;
- (void)targetIsScanner:(id)arg1;
- (void)targetIsOpenview:(id)arg1;
- (void)targetIsViewpics:(id)arg1;
- (void)targetIsChooseImg:(id)arg1;
- (void)targetIsUpload:(id)arg1;
- (void)targetIsSearch:(id)arg1;
- (void)targetIsSavePhotoToAlbum:(id)arg1;
- (void)targetIsBack:(id)arg1;
- (void)targetIsCommentAndContentId:(id)arg1;
- (void)targetIsUpaddress:(id)arg1;
- (void)targetIsShare:(id)arg1;
- (void)targetIsRefmy:(id)arg1;
- (void)targetIsCoinTips2AndValue:(id)arg1;
- (void)targetIsCoinTipsAndValue:(id)arg1;
- (void)targetIsClipboardAndValue:(id)arg1;
- (void)targetIsTs:(id)arg1;
- (void)targetIsLogin:(id)arg1;
- (void)targetIsGetTokenAndCallback:(id)arg1;
- (void)targetIsjumpNoticePage:(id)arg1;
- (void)targetIsYq:(id)arg1;
- (void)targetIsFeedback:(id)arg1;
- (void)targetIsFav:(id)arg1;
- (void)targetIsJsrule:(id)arg1;
- (void)targetIsMall:(id)arg1;
- (void)targetIsTask:(id)arg1;
- (void)targetIsInputcode:(id)arg1;
- (void)targetIsChangebindzfb:(id)arg1;
- (void)targetIsBindzfb:(id)arg1;
- (void)targetIsBindwx:(id)arg1;
- (void)targetIsSetting:(id)arg1;
- (void)targetIsMy:(id)arg1;
- (void)targetIsSubscribe:(id)arg1;
- (void)targetIsSubscribeAndValue:(id)arg1;
- (void)targetIsIndex:(id)arg1;
- (void)targetIsIndexAndRefOne:(id)arg1;
- (void)targetIsIndexAndValue:(id)arg1;
- (void)targetIsTryopen:(id)arg1;
- (void)targetIsSms:(id)arg1;
- (void)targetIsQq:(id)arg1;
- (void)targetIsQqzone:(id)arg1;
- (void)targetIsWx:(id)arg1;
- (void)targetIsWxpy:(id)arg1;
- (void)targetIsHidebar:(id)arg1;
- (void)targetIsKefu:(id)arg1;
- (void)targetIsDownload:(id)arg1;
- (void)targetIsWemediaAndValue:(id)arg1;
- (void)targetIsAttention:(id)arg1;
- (void)targetIsGetEnvAndCallback:(id)arg1;
- (void)targetIsGetEnv:(id)arg1;
- (void)targetIsTFInstall:(id)arg1;
- (void)targetIsNotifySetting:(id)arg1;
- (id)interfaceMethods;
- (id)interfaceMethodKeys;
- (id)readHtml:(id)arg1;
- (void)writeHtmlToFolder:(id)arg1 fileName:(id)arg2;
- (void)showWebBack;
- (id)cache_key;
- (_Bool)is_url_cache:(id)arg1;
- (_Bool)is_using_back_host;
- (void)using_back_host;
- (id)back_host:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

