//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QKContentBaseCell.h"

#import "LCTableViewCellConfigure-Protocol.h"

@class NSString, QKAdvert, QKBaseAdvertView;

@interface QKContentAdvertCell : QKContentBaseCell <LCTableViewCellConfigure>
{
    QKAdvert *_advert;
    QKBaseAdvertView *_advertView;
}

@property(retain, nonatomic) QKBaseAdvertView *advertView; // @synthesize advertView=_advertView;
@property(retain, nonatomic) QKAdvert *advert; // @synthesize advert=_advert;
- (void).cxx_destruct;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (id)largePicAdvertView;
- (id)linkAdvertView;
- (id)longAdvertView;
- (id)mutiAdvertView;
- (id)largeAdvertView;
- (id)rightAdvertView;
- (id)generateAdvertViewFromAdvertObject:(id)arg1;
- (void)adClick;
- (void)bindAdObject:(id)arg1;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)update:(id)arg1;
- (void)dealloc;
- (void)configureCellWithModel:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

