//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QKBaseViewController.h"

#import "BaseCellProtocol-Protocol.h"
#import "DislikeModelViewDelegate-Protocol.h"
#import "QKHotSearchViewDelegate-Protocol.h"
#import "QKVideoCellDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "UITextFieldDelegate-Protocol.h"

@class LCBaseTableView, NSMutableArray, NSString, QKNavigationSearchView, QKView, UIImageView, UILabel, UIView;

@interface QKContentSearchController : QKBaseViewController <UITableViewDelegate, UITableViewDataSource, QKHotSearchViewDelegate, DislikeModelViewDelegate, BaseCellProtocol, UITextFieldDelegate, QKVideoCellDelegate>
{
    long long _refresh_num;
    NSMutableArray *_searchHot;
    long long _contentType;
    long long _searchType;
    NSString *_keywords;
    QKNavigationSearchView *_navigationSearchView;
    QKView *_tableHeaderView;
    QKView *_hsitoryTableHeaderView;
    UIView *_tableFooterView;
    LCBaseTableView *_tableView;
    NSMutableArray *_contents;
    NSMutableArray *_medias;
    NSMutableArray *_searchHistory;
    UIImageView *_emptyView;
    UILabel *_emptyL;
    long long _page;
    long long _media_num;
    NSString *_search_key;
}

@property(copy, nonatomic) NSString *search_key; // @synthesize search_key=_search_key;
@property(nonatomic) long long media_num; // @synthesize media_num=_media_num;
@property(nonatomic) long long page; // @synthesize page=_page;
@property(retain, nonatomic) UILabel *emptyL; // @synthesize emptyL=_emptyL;
@property(retain, nonatomic) UIImageView *emptyView; // @synthesize emptyView=_emptyView;
@property(retain, nonatomic) NSMutableArray *searchHistory; // @synthesize searchHistory=_searchHistory;
@property(retain, nonatomic) NSMutableArray *medias; // @synthesize medias=_medias;
@property(retain, nonatomic) NSMutableArray *contents; // @synthesize contents=_contents;
@property(retain, nonatomic) LCBaseTableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) UIView *tableFooterView; // @synthesize tableFooterView=_tableFooterView;
@property(retain, nonatomic) QKView *hsitoryTableHeaderView; // @synthesize hsitoryTableHeaderView=_hsitoryTableHeaderView;
@property(retain, nonatomic) QKView *tableHeaderView; // @synthesize tableHeaderView=_tableHeaderView;
@property(retain, nonatomic) QKNavigationSearchView *navigationSearchView; // @synthesize navigationSearchView=_navigationSearchView;
@property(copy, nonatomic) NSString *keywords; // @synthesize keywords=_keywords;
@property(nonatomic) long long searchType; // @synthesize searchType=_searchType;
@property(nonatomic) long long contentType; // @synthesize contentType=_contentType;
@property(retain, nonatomic) NSMutableArray *searchHot; // @synthesize searchHot=_searchHot;
- (void).cxx_destruct;
- (_Bool)isBlankString:(id)arg1;
- (void)saveSearchHistory:(id)arg1;
- (void)searchWithKey:(id)arg1 page:(long long)arg2;
- (void)searchWithKey:(id)arg1;
- (void)clearAction;
- (void)searchAction:(id)arg1;
- (void)loadHistory;
- (void)loadMore;
- (void)loadNew;
- (void)didClearSerachHistory;
- (void)layout;
- (void)createNotification;
- (void)viewDidLoad;
- (void)notification_reload_subcript:(id)arg1;
- (void)searchTextDidChange:(id)arg1;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (_Bool)textFieldShouldClear:(id)arg1;
- (void)videoCellShareClickWithModel:(id)arg1;
- (void)searchBar:(id)arg1 textDidChange:(id)arg2;
- (void)didElemsClick:(id)arg1 oper:(int)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (void)showMoreMedia;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)tableView:(id)arg1 accessoryButtonTappedForRowWithIndexPath:(id)arg2;
- (void)accessoryButtonIsTapped:(id)arg1 event:(id)arg2;
- (void)back;
- (void)onDislikeModel:(id)arg1 reason:(id)arg2;
- (void)onDislikeModelView:(id)arg1;
- (void)on_video_dislike:(id)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

