//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QKView.h"

#import "UITextFieldDelegate-Protocol.h"

@class NSString, UIButton, UIControl, UIImageView, UILabel, UITextField;
@protocol QKCodeImageViewDelegate;

@interface QKCodeImageView : QKView <UITextFieldDelegate>
{
    UIButton *_close;
    _Bool _is_loading;
    UIControl *_overlayView;
    UILabel *_titleLable;
    UILabel *_hintLable;
    NSString *_identifier;
    UITextField *_codeField;
    UIImageView *_codeImageView;
    UIButton *_refreshButton;
    NSString *_telephone;
    long long _type;
    id <QKCodeImageViewDelegate> _delegate;
}

@property(nonatomic) __weak id <QKCodeImageViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) long long type; // @synthesize type=_type;
@property(retain, nonatomic) NSString *telephone; // @synthesize telephone=_telephone;
@property(retain, nonatomic) UIButton *refreshButton; // @synthesize refreshButton=_refreshButton;
@property(retain, nonatomic) UIImageView *codeImageView; // @synthesize codeImageView=_codeImageView;
@property(retain, nonatomic) UITextField *codeField; // @synthesize codeField=_codeField;
@property(copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
@property(retain, nonatomic) UILabel *hintLable; // @synthesize hintLable=_hintLable;
@property(retain, nonatomic) UILabel *titleLable; // @synthesize titleLable=_titleLable;
@property(retain, nonatomic) UIControl *overlayView; // @synthesize overlayView=_overlayView;
- (void).cxx_destruct;
- (void)resetInputView;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)didTextFieldValueChanged:(id)arg1;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)checkCodeImage;
- (void)refreshCodeImage;
- (void)callKeyBoard;
- (id)initWithFrame:(struct CGRect)arg1 tel:(id)arg2;
- (void)buttonAction;
- (void)closeAction;
- (void)close;
- (void)show;
- (void)hideKeyBoard;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

