//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QKTableModel.h"

@class NSMutableArray, NSString;

@interface QKContentTableModel : QKTableModel
{
    long long _page;
    NSString *_cid;
    long long _count;
    long long _op;
    NSString *_pv_id;
    NSMutableArray *_ads;
    NSMutableArray *_content_ids;
    id _data;
    long long _max_time;
    long long _min_time;
    long long _show_time;
}

@property(nonatomic) long long show_time; // @synthesize show_time=_show_time;
@property(nonatomic) long long min_time; // @synthesize min_time=_min_time;
@property(nonatomic) long long max_time; // @synthesize max_time=_max_time;
@property(retain, nonatomic) id data; // @synthesize data=_data;
@property(retain, nonatomic) NSMutableArray *content_ids; // @synthesize content_ids=_content_ids;
@property(retain, nonatomic) NSMutableArray *ads; // @synthesize ads=_ads;
@property(copy, nonatomic) NSString *pv_id; // @synthesize pv_id=_pv_id;
@property(nonatomic) long long op; // @synthesize op=_op;
@property(nonatomic) long long count; // @synthesize count=_count;
@property(copy, nonatomic) NSString *cid; // @synthesize cid=_cid;
@property(nonatomic) long long page; // @synthesize page=_page;
- (void).cxx_destruct;
- (id)analyse_model:(id)arg1 cdns:(id)arg2 cache:(_Bool)arg3;
- (id)initWithAttribute:(id)arg1 cdns:(id)arg2 cache:(_Bool)arg3;
- (id)initWithAttribute:(id)arg1 cdns:(id)arg2;
- (id)initWithAttribute:(id)arg1 info:(id)arg2;
- (id)initWithAttribute:(id)arg1;

@end

