//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QKBaseViewController.h"

#import "QKCRMangerViewDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "UITextFieldDelegate-Protocol.h"

@class LCBaseTableView, NSArray, NSIndexPath, NSMutableArray, NSString, QKCommentTableModel, QKContentModel, QKContentToolBar, SDTimeLineCellCommentItemModel, UIImageView, UITextField, UIView;

@interface QKCommentListController : QKBaseViewController <UITableViewDelegate, UITableViewDataSource, UITextFieldDelegate, QKCRMangerViewDelegate>
{
    long long _page;
    double _lastScrollViewOffsetY;
    double _totalKeybordHeight;
    _Bool _isReplyMaster;
    _Bool _isReplayingComment;
    LCBaseTableView *_tableView;
    QKContentModel *_contentModel;
    NSIndexPath *_currentEditingIndexthPath;
    NSMutableArray *_comments;
    NSMutableArray *_dataArray;
    SDTimeLineCellCommentItemModel *_currentReplyTargetModel;
    NSString *_commentToUser;
    QKCommentTableModel *_commentTableModel;
    QKCommentTableModel *_hotCommentTableModel;
    QKContentToolBar *_toolBar;
    UIImageView *_emptyView;
    UITextField *_textField;
    UIView *_textFieldBackground;
    NSArray *_currentPageCommentList;
}

@property(copy, nonatomic) NSArray *currentPageCommentList; // @synthesize currentPageCommentList=_currentPageCommentList;
@property(nonatomic) _Bool isReplayingComment; // @synthesize isReplayingComment=_isReplayingComment;
@property(retain, nonatomic) UIView *textFieldBackground; // @synthesize textFieldBackground=_textFieldBackground;
@property(retain, nonatomic) UITextField *textField; // @synthesize textField=_textField;
@property(retain, nonatomic) UIImageView *emptyView; // @synthesize emptyView=_emptyView;
@property(retain, nonatomic) QKContentToolBar *toolBar; // @synthesize toolBar=_toolBar;
@property(retain, nonatomic) QKCommentTableModel *hotCommentTableModel; // @synthesize hotCommentTableModel=_hotCommentTableModel;
@property(retain, nonatomic) QKCommentTableModel *commentTableModel; // @synthesize commentTableModel=_commentTableModel;
@property(copy, nonatomic) NSString *commentToUser; // @synthesize commentToUser=_commentToUser;
@property(retain, nonatomic) SDTimeLineCellCommentItemModel *currentReplyTargetModel; // @synthesize currentReplyTargetModel=_currentReplyTargetModel;
@property(retain, nonatomic) NSMutableArray *dataArray; // @synthesize dataArray=_dataArray;
@property(retain, nonatomic) NSMutableArray *comments; // @synthesize comments=_comments;
@property(retain, nonatomic) NSIndexPath *currentEditingIndexthPath; // @synthesize currentEditingIndexthPath=_currentEditingIndexthPath;
@property(nonatomic) _Bool isReplyMaster; // @synthesize isReplyMaster=_isReplyMaster;
@property(retain, nonatomic) QKContentModel *contentModel; // @synthesize contentModel=_contentModel;
@property(retain, nonatomic) LCBaseTableView *tableView; // @synthesize tableView=_tableView;
- (void).cxx_destruct;
- (void)loadHotComment;
- (void)foldReply;
- (void)contentFontChanged;
- (void)replyComment:(id)arg1;
- (void)keyboardWillShow:(id)arg1;
- (void)keyboardWillHide:(id)arg1;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (_Bool)textFieldShouldBeginEditing:(id)arg1;
- (void)adjustTableViewToFitKeyboardWithRect:(struct CGRect)arg1;
- (void)adjustTableViewToFitKeyboard;
- (double)cellContentViewWith;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (void)configureCell:(id)arg1 atIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)reloadComments:(id)arg1;
- (void)loadCommentList:(long long)arg1;
- (void)didReceiveMemoryWarning;
- (void)loadMore;
- (void)loadNew;
- (void)setupTextField;
- (void)storeAction;
- (void)shareAction;
- (void)showFonts;
- (void)CRMangerUnlike:(id)arg1;
- (void)CRMangerReport:(id)arg1;
- (void)comment;
- (void)configMJFooter;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

