//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QKTableModel.h"

@class NSMutableArray;

@interface QKCommentTableModel : QKTableModel
{
    NSMutableArray *_comments;
}

@property(retain, nonatomic) NSMutableArray *comments; // @synthesize comments=_comments;
- (void).cxx_destruct;
- (id)initWithAttribute:(id)arg1 src:(int)arg2;
- (id)initWithAttribute:(id)arg1;
- (id)initWithAttribute:(id)arg1 info:(id)arg2;

@end

