//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QKContentBaseCell.h"

#import "LCTableViewCellConfigure-Protocol.h"

@class NSString, QKContentModel, UIButton, UILabel;

@interface QKContentTextCell : QKContentBaseCell <LCTableViewCellConfigure>
{
    UILabel *_titleLabel;
    UILabel *_readCountLabel;
    QKContentModel *_content;
    UILabel *_timeLabel;
    UIButton *_deletButton;
    UILabel *_tagLabel;
    UILabel *_photosTag;
    UIButton *_delButton;
}

@property(retain, nonatomic) UIButton *delButton; // @synthesize delButton=_delButton;
@property(retain, nonatomic) UILabel *photosTag; // @synthesize photosTag=_photosTag;
@property(retain, nonatomic) UILabel *tagLabel; // @synthesize tagLabel=_tagLabel;
@property(retain, nonatomic) UIButton *deletButton; // @synthesize deletButton=_deletButton;
@property(retain, nonatomic) UILabel *timeLabel; // @synthesize timeLabel=_timeLabel;
@property(retain, nonatomic) QKContentModel *content; // @synthesize content=_content;
@property(retain, nonatomic) UILabel *readCountLabel; // @synthesize readCountLabel=_readCountLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void).cxx_destruct;
- (void)removeFav;
- (void)deleteContent:(id)arg1;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)update:(id)arg1;
- (void)makeContent;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)configureCellWithModel:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

