//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QKView.h"

#import "UITextFieldDelegate-Protocol.h"

@class NSString, QKButton, QKContentModel, QKSendBox, UIButton, UILabel, UITextField;

@interface QKContentToolBar : QKView <UITextFieldDelegate>
{
    int _commentStatus;
    int _src;
    UITextField *_inputView;
    UILabel *_commentCount;
    QKButton *_commentButton;
    UIButton *_shareButton;
    UIButton *_storeButton;
    UIButton *_extButton;
    long long _actionType;
    QKContentModel *_contentModel;
    QKSendBox *_sendBox;
}

@property(nonatomic) int src; // @synthesize src=_src;
@property(nonatomic) int commentStatus; // @synthesize commentStatus=_commentStatus;
@property(retain, nonatomic) QKSendBox *sendBox; // @synthesize sendBox=_sendBox;
@property(retain, nonatomic) QKContentModel *contentModel; // @synthesize contentModel=_contentModel;
@property(nonatomic) long long actionType; // @synthesize actionType=_actionType;
@property(retain, nonatomic) UIButton *extButton; // @synthesize extButton=_extButton;
@property(retain, nonatomic) UIButton *storeButton; // @synthesize storeButton=_storeButton;
@property(retain, nonatomic) UIButton *shareButton; // @synthesize shareButton=_shareButton;
@property(retain, nonatomic) QKButton *commentButton; // @synthesize commentButton=_commentButton;
@property(retain, nonatomic) UILabel *commentCount; // @synthesize commentCount=_commentCount;
@property(retain, nonatomic) UITextField *inputView; // @synthesize inputView=_inputView;
- (void).cxx_destruct;
- (void)disableInput;
- (void)updateCommentStatus:(int)arg1;
- (void)setComment:(id)arg1;
- (void)textFieldDidEndEditing:(id)arg1;
- (void)textFieldDidBeginEditing:(id)arg1;
- (_Bool)textFieldShouldEndEditing:(id)arg1;
- (_Bool)textFieldShouldBeginEditing:(id)arg1;
- (void)makeContent;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

