//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QKView.h"

@class UIControl, UISegmentedControl;
@protocol QKCRMangerViewDelegate;

@interface QKCRMangerView : QKView
{
    UIControl *_overlayView;
    UISegmentedControl *_segment;
    long long _type;
    id <QKCRMangerViewDelegate> _delegate;
}

+ (id)showInView:(id)arg1 type:(long long)arg2;
@property(nonatomic) __weak id <QKCRMangerViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) long long type; // @synthesize type=_type;
@property(retain, nonatomic) UISegmentedControl *segment; // @synthesize segment=_segment;
@property(retain, nonatomic) UIControl *overlayView; // @synthesize overlayView=_overlayView;
- (void).cxx_destruct;
- (void)dismiss;
- (void)confirm;
- (void)report:(id)arg1;
- (void)unlike:(id)arg1;
- (void)valueChanged:(id)arg1;
- (void)changeReadMode:(id)arg1;
- (void)changeBrightnessMode:(id)arg1;
- (void)overlayViewDissmiss;
- (void)setUp;
- (id)initWithFrame:(struct CGRect)arg1 type:(long long)arg2;

@end

