//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QKButton.h"

@class QKCycleProgressView, UIColor;

@interface QKCycleProgressBtn : QKButton
{
    double _progressWith;
    UIColor *_progressColor;
    double _progressStartA;
    double _progressRadius;
    double _progress;
    QKCycleProgressView *_progressBgView;
}

@property(retain, nonatomic) QKCycleProgressView *progressBgView; // @synthesize progressBgView=_progressBgView;
@property(nonatomic) double progress; // @synthesize progress=_progress;
@property(nonatomic) double progressRadius; // @synthesize progressRadius=_progressRadius;
@property(nonatomic) double progressStartA; // @synthesize progressStartA=_progressStartA;
@property(retain, nonatomic) UIColor *progressColor; // @synthesize progressColor=_progressColor;
@property(nonatomic) double progressWith; // @synthesize progressWith=_progressWith;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

