//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QKBaseViewController.h"

@class BYDeleteBar, BYDetailsList, QKChannel;
@protocol QKEditCategoryControllerDelegate;

@interface QKEditCategoryController : QKBaseViewController
{
    _Bool _is_menu_edit;
    int _animateType;
    QKChannel *_selectedChannel;
    id <QKEditCategoryControllerDelegate> _editCategorydelelate;
    BYDeleteBar *_deleteBar;
    BYDetailsList *_detailsList;
}

@property(nonatomic) int animateType; // @synthesize animateType=_animateType;
@property(nonatomic) _Bool is_menu_edit; // @synthesize is_menu_edit=_is_menu_edit;
@property(retain, nonatomic) BYDetailsList *detailsList; // @synthesize detailsList=_detailsList;
@property(retain, nonatomic) BYDeleteBar *deleteBar; // @synthesize deleteBar=_deleteBar;
@property(nonatomic) __weak id <QKEditCategoryControllerDelegate> editCategorydelelate; // @synthesize editCategorydelelate=_editCategorydelelate;
@property(retain, nonatomic) QKChannel *selectedChannel; // @synthesize selectedChannel=_selectedChannel;
- (void).cxx_destruct;
- (void)commitChannelsToServier;
- (void)setLocalChannels;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)makeContent;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

@end

