//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "LCBaseModel.h"

#import "LCTableViewRowData-Protocol.h"

@class NSIndexPath, NSString, QKFuncLabel, QKFuncRedDot;

@interface QKFunc : LCBaseModel <LCTableViewRowData>
{
    _Bool _login_need;
    _Bool _showRedDot;
    _Bool _showTip;
    int _sort;
    int _display_menu;
    int _open_notice;
    int _red_rule_type;
    NSString *_desc;
    NSString *_desc_color;
    NSString *_icon;
    NSString *_name;
    NSString *_key;
    NSString *_url;
    NSString *_default_image;
    QKFuncLabel *_label;
    QKFuncRedDot *_red_dot;
    NSString *_corner;
}

@property(copy, nonatomic) NSString *corner; // @synthesize corner=_corner;
@property(nonatomic) _Bool showTip; // @synthesize showTip=_showTip;
@property(nonatomic) _Bool showRedDot; // @synthesize showRedDot=_showRedDot;
@property(retain, nonatomic) QKFuncRedDot *red_dot; // @synthesize red_dot=_red_dot;
@property(retain, nonatomic) QKFuncLabel *label; // @synthesize label=_label;
@property(nonatomic) int red_rule_type; // @synthesize red_rule_type=_red_rule_type;
@property(nonatomic) _Bool login_need; // @synthesize login_need=_login_need;
@property(copy, nonatomic) NSString *default_image; // @synthesize default_image=_default_image;
@property(copy, nonatomic) NSString *url; // @synthesize url=_url;
@property(nonatomic) int open_notice; // @synthesize open_notice=_open_notice;
@property(nonatomic) int display_menu; // @synthesize display_menu=_display_menu;
@property(copy, nonatomic) NSString *key; // @synthesize key=_key;
@property(nonatomic) int sort; // @synthesize sort=_sort;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(copy, nonatomic) NSString *icon; // @synthesize icon=_icon;
@property(copy, nonatomic) NSString *desc_color; // @synthesize desc_color=_desc_color;
@property(copy, nonatomic) NSString *desc; // @synthesize desc=_desc;
- (void).cxx_destruct;
- (void)doRule1;
- (double)cellHeight;
- (id)cellKey;
- (id)initWithAttribute:(id)arg1 cache_info:(id)arg2;
- (id)reusableIdentifier;
- (Class)cellClass;
- (double)cellRowHeight;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(retain, nonatomic) NSIndexPath *indexPath;
@property(nonatomic) SEL rowAction;
@property(readonly) Class superclass;

@end

