//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "LCBaseModel.h"

#import "LCTableViewSectionData-Protocol.h"

@class NSMutableArray, NSString, UIView;

@interface QKFuncs : LCBaseModel <LCTableViewSectionData>
{
    NSMutableArray *_rowData;
    double _sectionFooterHeight;
    UIView *_sectionFooterView;
    NSMutableArray *_funcs;
}

@property(retain, nonatomic) NSMutableArray *funcs; // @synthesize funcs=_funcs;
@property(retain, nonatomic) UIView *sectionFooterView; // @synthesize sectionFooterView=_sectionFooterView;
@property(nonatomic) double sectionFooterHeight; // @synthesize sectionFooterHeight=_sectionFooterHeight;
@property(retain, nonatomic) NSMutableArray *rowData; // @synthesize rowData=_rowData;
- (void).cxx_destruct;
@property(retain, nonatomic) UIView *sectionHeaderView;
@property(nonatomic) double sectionHeaderHeight;
- (id)initWithAttribute:(id)arg1 cache_info:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

