//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "LCBaseModel.h"

@class AdSplashModel, NSDictionary, NSMutableArray, NSMutableDictionary, NSString, QKMsgPush, QKShareContent, QKShareInvite;

@interface QKHeart : LCBaseModel
{
    _Bool _pull_act;
    _Bool _is_mission_update;
    _Bool _is_member_info_update;
    _Bool _is_message_update;
    _Bool _is_share_update;
    _Bool _isShowOnShareIcon;
    _Bool _has_new_pupil;
    _Bool _is_shop_update;
    NSString *_publish_time;
    NSString *_push_time;
    NSMutableArray *_share_way;
    NSDictionary *_H5URL;
    NSDictionary *_gallery_cfg;
    QKShareInvite *_share_invite;
    QKShareContent *_share_content;
    QKMsgPush *_msg_push;
    AdSplashModel *_ad;
    NSMutableDictionary *_share_v2_update;
}

@property(nonatomic) _Bool is_shop_update; // @synthesize is_shop_update=_is_shop_update;
@property(nonatomic) _Bool has_new_pupil; // @synthesize has_new_pupil=_has_new_pupil;
@property(nonatomic) _Bool isShowOnShareIcon; // @synthesize isShowOnShareIcon=_isShowOnShareIcon;
@property(retain, nonatomic) NSMutableDictionary *share_v2_update; // @synthesize share_v2_update=_share_v2_update;
@property(nonatomic) _Bool is_share_update; // @synthesize is_share_update=_is_share_update;
@property(nonatomic) _Bool is_message_update; // @synthesize is_message_update=_is_message_update;
@property(nonatomic) _Bool is_member_info_update; // @synthesize is_member_info_update=_is_member_info_update;
@property(nonatomic) _Bool is_mission_update; // @synthesize is_mission_update=_is_mission_update;
@property(retain, nonatomic) AdSplashModel *ad; // @synthesize ad=_ad;
@property(retain, nonatomic) QKMsgPush *msg_push; // @synthesize msg_push=_msg_push;
@property(retain, nonatomic) QKShareContent *share_content; // @synthesize share_content=_share_content;
@property(retain, nonatomic) QKShareInvite *share_invite; // @synthesize share_invite=_share_invite;
@property(nonatomic) _Bool pull_act; // @synthesize pull_act=_pull_act;
@property(retain, nonatomic) NSDictionary *gallery_cfg; // @synthesize gallery_cfg=_gallery_cfg;
@property(retain, nonatomic) NSDictionary *H5URL; // @synthesize H5URL=_H5URL;
@property(retain, nonatomic) NSMutableArray *share_way; // @synthesize share_way=_share_way;
@property(retain, nonatomic) NSString *push_time; // @synthesize push_time=_push_time;
@property(retain, nonatomic) NSString *publish_time; // @synthesize publish_time=_publish_time;
- (void).cxx_destruct;
- (id)initWithAttribute:(id)arg1 info:(id)arg2;

@end

