//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QKTableViewCell.h"

@class QKSubcript, UIButton, UILabel, UIView;

@interface QKHotSubcriptCell : QKTableViewCell
{
    UIButton *_indicator;
    UIButton *_checkBox;
    UILabel *_lable;
    UILabel *_attention;
    UIView *_background;
    QKSubcript *_subcript;
}

@property(retain, nonatomic) QKSubcript *subcript; // @synthesize subcript=_subcript;
@property(retain, nonatomic) UIView *background; // @synthesize background=_background;
@property(retain, nonatomic) UILabel *attention; // @synthesize attention=_attention;
@property(retain, nonatomic) UILabel *lable; // @synthesize lable=_lable;
@property(retain, nonatomic) UIButton *checkBox; // @synthesize checkBox=_checkBox;
@property(retain, nonatomic) UIButton *indicator; // @synthesize indicator=_indicator;
- (void).cxx_destruct;
- (void)chooseAction:(id)arg1;
- (void)update:(id)arg1;
- (void)layout;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

