//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QKView.h"

@class NSMutableArray, UIButton, UILabel;
@protocol QKHotSearchViewDelegate;

@interface QKHotSearchView : QKView
{
    UIButton *_menuButton;
    UILabel *_alert;
    NSMutableArray *_menuButtons;
    NSMutableArray *_menulist;
    double _viewHeight;
    id <QKHotSearchViewDelegate> _delegate;
}

@property(nonatomic) __weak id <QKHotSearchViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) double viewHeight; // @synthesize viewHeight=_viewHeight;
@property(retain, nonatomic) NSMutableArray *menulist; // @synthesize menulist=_menulist;
@property(retain, nonatomic) NSMutableArray *menuButtons; // @synthesize menuButtons=_menuButtons;
@property(retain, nonatomic) UILabel *alert; // @synthesize alert=_alert;
@property(retain, nonatomic) UIButton *menuButton; // @synthesize menuButton=_menuButton;
- (void).cxx_destruct;
- (void)layout;
- (void)clearAction;
- (id)initWithFrame:(struct CGRect)arg1;

@end

