//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QKBaseViewController.h"

#import "QKCodeImageViewDelegate-Protocol.h"
#import "UITextFieldDelegate-Protocol.h"

@class ClipBoardGifModel, NSMutableDictionary, NSString, NSTimer, UIButton, UILabel, UIView, UIconTextField;

@interface QKLoginViewController : QKBaseViewController <UITextFieldDelegate, QKCodeImageViewDelegate>
{
    _Bool _is_agree_agreement;
    id _scheme;
    NSString *_phone;
    ClipBoardGifModel *_clipboardGif;
    long long _login_type;
    long long _fromPage;
    CDUnknownBlockType _loginCompletion;
    NSMutableDictionary *_paramDictionary;
    UIView *_backgroudView;
    NSTimer *_timer;
    UIconTextField *_phone_field;
    UIconTextField *_password_field;
    UIButton *_tip_button;
    UIView *_bottomLineView;
    UIView *_password_backgroud;
    UIView *_phone_backgroud;
    UIButton *_checkBox_button;
    UILabel *_left_label;
    UIButton *_agreement_button;
    UIButton *_login_button;
    UIButton *_regist_button;
    UIButton *_forgetPass_button;
    UIView *_blockView;
}

@property(retain, nonatomic) UIView *blockView; // @synthesize blockView=_blockView;
@property(retain, nonatomic) UIButton *forgetPass_button; // @synthesize forgetPass_button=_forgetPass_button;
@property(retain, nonatomic) UIButton *regist_button; // @synthesize regist_button=_regist_button;
@property(retain, nonatomic) UIButton *login_button; // @synthesize login_button=_login_button;
@property(retain, nonatomic) UIButton *agreement_button; // @synthesize agreement_button=_agreement_button;
@property(retain, nonatomic) UILabel *left_label; // @synthesize left_label=_left_label;
@property(retain, nonatomic) UIButton *checkBox_button; // @synthesize checkBox_button=_checkBox_button;
@property(retain, nonatomic) UIView *phone_backgroud; // @synthesize phone_backgroud=_phone_backgroud;
@property(retain, nonatomic) UIView *password_backgroud; // @synthesize password_backgroud=_password_backgroud;
@property(retain, nonatomic) UIView *bottomLineView; // @synthesize bottomLineView=_bottomLineView;
@property(retain, nonatomic) UIButton *tip_button; // @synthesize tip_button=_tip_button;
@property(retain, nonatomic) UIconTextField *password_field; // @synthesize password_field=_password_field;
@property(retain, nonatomic) UIconTextField *phone_field; // @synthesize phone_field=_phone_field;
@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
@property(retain, nonatomic) UIView *backgroudView; // @synthesize backgroudView=_backgroudView;
@property(retain, nonatomic) NSMutableDictionary *paramDictionary; // @synthesize paramDictionary=_paramDictionary;
@property(copy, nonatomic) CDUnknownBlockType loginCompletion; // @synthesize loginCompletion=_loginCompletion;
@property(nonatomic) long long fromPage; // @synthesize fromPage=_fromPage;
@property(nonatomic) long long login_type; // @synthesize login_type=_login_type;
@property(retain, nonatomic) ClipBoardGifModel *clipboardGif; // @synthesize clipboardGif=_clipboardGif;
@property(retain, nonatomic) NSString *phone; // @synthesize phone=_phone;
@property(retain, nonatomic) id scheme; // @synthesize scheme=_scheme;
- (void).cxx_destruct;
- (void)openGift:(id)arg1;
- (void)notifyLoginSucess;
- (void)gotoInvite;
- (void)dismiss:(_Bool)arg1;
- (void)getUserContentChannelList:(_Bool)arg1;
- (void)didReceiveMemoryWarnitng;
- (void)forgetPass;
- (void)quickLogin:(_Bool)arg1;
- (void)regist;
- (void)qkCodeImageViewButtonClick:(id)arg1;
- (void)qkCodeImageViewButtonClose:(id)arg1;
- (void)showFreezzingReason:(id)arg1 confirmText:(id)arg2;
- (void)showFreezzingReason:(id)arg1 confirmText:(id)arg2 selector:(id)arg3;
- (void)api_login_finish:(id)arg1;
- (id)loginParam:(id)arg1;
- (void)login;
- (void)reSendCode;
- (void)creatrTimer;
- (void)changeTitle:(id)arg1;
- (void)getCode;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)passwordTextFieldDidChange:(id)arg1;
- (_Bool)textFieldShouldBeginEditing:(id)arg1;
- (void)contact:(id)arg1;
- (void)showPass:(id)arg1;
- (void)agreement;
- (void)agreementAction:(id)arg1;
- (void)layoutSubViews;
- (void)createUI;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithType:(long long)arg1;
- (void)back;
- (void)handleDeepLink;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

