//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString;

@interface QKLocalPushTopViewMaker : NSObject
{
    _Bool _vibrateOnMute;
    _Bool _coverLastOnes;
    unsigned int _soundID;
    long long _style;
    NSString *_iconString;
    NSString *_title;
    NSString *_rightImageString;
    NSString *_date;
    NSString *_content;
    NSString *_skipUrl;
    double _animationDuration;
    double _stayDuration;
    id _object;
    NSString *_soundName;
}

@property(nonatomic) _Bool coverLastOnes; // @synthesize coverLastOnes=_coverLastOnes;
@property(nonatomic) _Bool vibrateOnMute; // @synthesize vibrateOnMute=_vibrateOnMute;
@property(retain, nonatomic) NSString *soundName; // @synthesize soundName=_soundName;
@property(nonatomic) unsigned int soundID; // @synthesize soundID=_soundID;
@property(retain, nonatomic) id object; // @synthesize object=_object;
@property(nonatomic) double stayDuration; // @synthesize stayDuration=_stayDuration;
@property(nonatomic) double animationDuration; // @synthesize animationDuration=_animationDuration;
@property(retain, nonatomic) NSString *skipUrl; // @synthesize skipUrl=_skipUrl;
@property(retain, nonatomic) NSString *content; // @synthesize content=_content;
@property(retain, nonatomic) NSString *date; // @synthesize date=_date;
@property(retain, nonatomic) NSString *rightImageString; // @synthesize rightImageString=_rightImageString;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) NSString *iconString; // @synthesize iconString=_iconString;
@property(nonatomic) long long style; // @synthesize style=_style;
- (void).cxx_destruct;

@end

