//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QKBaseViewController.h"

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSMutableArray, NSString, QKSubcritCategory, UITableView;

@interface QKMangerSubcriptController : QKBaseViewController <UITableViewDataSource, UITableViewDelegate>
{
    long long _page;
    UITableView *_categoryTableView;
    NSMutableArray *_categorys;
    QKSubcritCategory *_subcriptCategory;
    UITableView *_contentTableView;
    NSMutableArray *_contents;
}

@property(retain, nonatomic) NSMutableArray *contents; // @synthesize contents=_contents;
@property(retain, nonatomic) UITableView *contentTableView; // @synthesize contentTableView=_contentTableView;
@property(retain, nonatomic) QKSubcritCategory *subcriptCategory; // @synthesize subcriptCategory=_subcriptCategory;
@property(retain, nonatomic) NSMutableArray *categorys; // @synthesize categorys=_categorys;
@property(retain, nonatomic) UITableView *categoryTableView; // @synthesize categoryTableView=_categoryTableView;
- (void).cxx_destruct;
- (void)loadSubcriptionWithCategory:(id)arg1;
- (void)loadSubcriptionCategory;
- (void)didReceiveMemoryWarning;
- (void)viewWillAppear:(_Bool)arg1;
- (void)loadMore;
- (void)search;
- (void)notification_reload_subcript:(id)arg1;
- (void)reload;
- (void)viewDidLoad;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

