//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TYBasePageTabBar.h"

@class NSArray, UIButton, UIColor, UIFont, UIScrollView;

@interface QKMainNavView : TYBasePageTabBar
{
    UIScrollView *_scrollView;
    UIButton *_btnFold;
    UIFont *_textFont;
    UIFont *_selectedTextFont;
    UIColor *_textColor;
    UIColor *_selectedTextColor;
    NSArray *_titleArray;
    double _titleSpacing;
    NSArray *_btnArray;
    UIButton *_selectBtn;
    struct UIEdgeInsets _edgeInset;
}

@property(retain, nonatomic) UIButton *selectBtn; // @synthesize selectBtn=_selectBtn;
@property(retain, nonatomic) NSArray *btnArray; // @synthesize btnArray=_btnArray;
@property(nonatomic) double titleSpacing; // @synthesize titleSpacing=_titleSpacing;
@property(nonatomic) struct UIEdgeInsets edgeInset; // @synthesize edgeInset=_edgeInset;
@property(retain, nonatomic) NSArray *titleArray; // @synthesize titleArray=_titleArray;
@property(retain, nonatomic) UIColor *selectedTextColor; // @synthesize selectedTextColor=_selectedTextColor;
@property(retain, nonatomic) UIColor *textColor; // @synthesize textColor=_textColor;
@property(retain, nonatomic) UIFont *selectedTextFont; // @synthesize selectedTextFont=_selectedTextFont;
@property(retain, nonatomic) UIFont *textFont; // @synthesize textFont=_textFont;
@property(retain, nonatomic) UIButton *btnFold; // @synthesize btnFold=_btnFold;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
- (void).cxx_destruct;
- (void)switchToPageIndex:(long long)arg1;
- (void)tabButtonClicked:(id)arg1;
- (void)selectButton:(id)arg1;
- (void)removeTitleBtnArray;
- (void)addTitleBtnArray:(long long)arg1;
- (void)setTitleArray:(id)arg1 index:(long long)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

