//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString, NSURLSession, QKMessageRetryInfo;

@interface QKMessageHelper : NSObject
{
    NSURLSession *_urlSession;
    QKMessageRetryInfo *_openRegisterInfo;
    QKMessageRetryInfo *_bindAliasInfo;
    QKMessageRetryInfo *_resetTagsInfo;
    NSString *_deviceToken;
}

+ (id)helperWithDeviceToken:(id)arg1;
@property(copy, nonatomic) NSString *deviceToken; // @synthesize deviceToken=_deviceToken;
@property(retain, nonatomic) QKMessageRetryInfo *resetTagsInfo; // @synthesize resetTagsInfo=_resetTagsInfo;
@property(retain, nonatomic) QKMessageRetryInfo *bindAliasInfo; // @synthesize bindAliasInfo=_bindAliasInfo;
@property(retain, nonatomic) QKMessageRetryInfo *openRegisterInfo; // @synthesize openRegisterInfo=_openRegisterInfo;
- (void).cxx_destruct;
- (id)parseDict:(id)arg1;
- (id)parseData:(id)arg1;
- (id)timestamp;
- (id)sign_SHA256:(id)arg1;
- (id)getRequestWithApi:(id)arg1 param:(id)arg2;
- (void)resetTags:(id)arg1;
- (void)closeRegister;
- (void)openRegister;
- (void)unbindAlias:(id)arg1 type:(id)arg2 response:(CDUnknownBlockType)arg3;
- (void)bindAlias:(id)arg1 type:(id)arg2 response:(CDUnknownBlockType)arg3;
- (void)reportApi:(id)arg1 apdParams:(id)arg2 response:(id)arg3 data:(id)arg4 parseDict:(id)arg5 error:(id)arg6;
- (id)init;

@end

