//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QKBaseViewController.h"

#import "InputTextBoxDelegate-Protocol.h"
#import "LCTableViewConfigure-Protocol.h"

@class CommonPickerView, InputTextBox, LCTableViewManager, NSArray, NSString, QKUser, UserInfoConfigModel;

@interface QKMoreProfileController : QKBaseViewController <LCTableViewConfigure, InputTextBoxDelegate>
{
    id _dataSource;
    UserInfoConfigModel *_configModel;
    NSArray *_sourceData;
    CommonPickerView *_pickerView;
    InputTextBox *_textBox;
    QKUser *_originUser;
    LCTableViewManager *_tableManager;
}

@property(retain, nonatomic) LCTableViewManager *tableManager; // @synthesize tableManager=_tableManager;
@property(retain, nonatomic) QKUser *originUser; // @synthesize originUser=_originUser;
@property(retain, nonatomic) InputTextBox *textBox; // @synthesize textBox=_textBox;
@property(retain, nonatomic) CommonPickerView *pickerView; // @synthesize pickerView=_pickerView;
@property(retain, nonatomic) NSArray *sourceData; // @synthesize sourceData=_sourceData;
@property(retain, nonatomic) UserInfoConfigModel *configModel; // @synthesize configModel=_configModel;
@property(retain, nonatomic) id dataSource; // @synthesize dataSource=_dataSource;
- (void).cxx_destruct;
- (void)InputTextBoxDidSelectConfirm:(id)arg1;
- (void)handlerRequstCallBack:(id)arg1;
- (void)modifyMemberInfo;
- (void)_moreProfileIntroduceModify;
- (void)_moreProfileEducationModify;
- (void)_moreProfileCareerModify;
- (void)tableViewManager:(id)arg1 tableViewEmptyButtonTouchAction:(long long)arg2;
- (void)tableViewManager:(id)arg1 cellForRowAtIndexPath:(id)arg2 tableViewCell:(id)arg3;
- (void)tableViewManager:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)initSourceData;
- (void)copyUserInfo;
- (void)commonInit;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

