//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface QKPaymentManager : NSObject
{
    CDUnknownBlockType _callback;
}

+ (id)manger;
@property(copy, nonatomic) CDUnknownBlockType callback; // @synthesize callback=_callback;
- (void).cxx_destruct;
- (void)payResult:(id)arg1;
- (void)wxpay:(id)arg1;
- (void)alipay:(id)arg1;
- (void)payWithOrder:(id)arg1 callback:(CDUnknownBlockType)arg2;
- (id)init;
- (void)dealloc;

@end

