//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "LCBaseModel.h"

@class NSString;

@interface QKPersonTopImg : LCBaseModel
{
    NSString *_titleBg;
    NSString *_UserBg;
}

@property(copy, nonatomic) NSString *UserBg; // @synthesize UserBg=_UserBg;
@property(copy, nonatomic) NSString *titleBg; // @synthesize titleBg=_titleBg;
- (void).cxx_destruct;
- (id)initWithAttribute:(id)arg1;

@end

