//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIButton, UIImageView, UILabel, UISlider;

@interface QKPlayerControlView : UIView
{
    _Bool _isShow;
    _Bool _isFullScreen;
    _Bool _isHor;
    int _playPauseBtnType;
    UIView *_bgMaskView;
    UIButton *_playPauseBtn;
    UIView *_topView;
    UIButton *_backBtn;
    UILabel *_titleLabel;
    UIImageView *_topBgImageView;
    UIImageView *_bottomImageView;
    UIButton *_playButton;
    UISlider *_videoProgressSlider;
    UILabel *_timeLabel;
    UIButton *_fullScreenBtn;
}

+ (id)playerControlView;
@property(nonatomic) _Bool isHor; // @synthesize isHor=_isHor;
@property(nonatomic) _Bool isFullScreen; // @synthesize isFullScreen=_isFullScreen;
@property(nonatomic) _Bool isShow; // @synthesize isShow=_isShow;
@property(retain, nonatomic) UIButton *fullScreenBtn; // @synthesize fullScreenBtn=_fullScreenBtn;
@property(retain, nonatomic) UILabel *timeLabel; // @synthesize timeLabel=_timeLabel;
@property(retain, nonatomic) UISlider *videoProgressSlider; // @synthesize videoProgressSlider=_videoProgressSlider;
@property(retain, nonatomic) UIButton *playButton; // @synthesize playButton=_playButton;
@property(retain, nonatomic) UIImageView *bottomImageView; // @synthesize bottomImageView=_bottomImageView;
@property(retain, nonatomic) UIImageView *topBgImageView; // @synthesize topBgImageView=_topBgImageView;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIButton *backBtn; // @synthesize backBtn=_backBtn;
@property(retain, nonatomic) UIView *topView; // @synthesize topView=_topView;
@property(nonatomic) int playPauseBtnType; // @synthesize playPauseBtnType=_playPauseBtnType;
@property(retain, nonatomic) UIButton *playPauseBtn; // @synthesize playPauseBtn=_playPauseBtn;
@property(retain, nonatomic) UIView *bgMaskView; // @synthesize bgMaskView=_bgMaskView;
- (void).cxx_destruct;
- (void)setupUI;
- (void)layoutSubviews;
- (id)init;
- (void)hiddenControlView;
- (void)showControlView;
- (void)updateSubViewLayout;

@end

