//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "LCTableViewRowData-Protocol.h"

@class NSIndexPath, NSString;

@interface QKProfileModel : NSObject <LCTableViewRowData>
{
    long long _cellType;
    NSString *_profileTitle;
}

@property(copy, nonatomic) NSString *profileTitle; // @synthesize profileTitle=_profileTitle;
@property(nonatomic) long long cellType; // @synthesize cellType=_cellType;
- (void).cxx_destruct;
- (double)cellHeight;
- (id)initWithTitle:(id)arg1 cellType:(long long)arg2;
- (double)cellRowHeight;
- (id)reusableIdentifier;
- (Class)cellClass;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(retain, nonatomic) NSIndexPath *indexPath;
@property(nonatomic) SEL rowAction;
@property(readonly) Class superclass;

@end

