//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "LCBaseModel.h"

@class NSArray, NSDictionary;

@interface QKPreSignModel : LCBaseModel
{
    NSDictionary *_amount;
    long long _continuation;
    long long _today;
    long long _show;
    NSArray *_signStatusArr;
    long long _todayCoin;
}

@property(nonatomic) long long todayCoin; // @synthesize todayCoin=_todayCoin;
@property(retain, nonatomic) NSArray *signStatusArr; // @synthesize signStatusArr=_signStatusArr;
@property(nonatomic) long long show; // @synthesize show=_show;
@property(nonatomic) long long today; // @synthesize today=_today;
@property(nonatomic) long long continuation; // @synthesize continuation=_continuation;
@property(retain, nonatomic) NSDictionary *amount; // @synthesize amount=_amount;
- (void).cxx_destruct;
- (void)sortSignStatusArr;
- (id)initWithAttribute:(id)arg1;

@end

