//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

#import "LCTableViewCellConfigure-Protocol.h"

@class NSString, QKProfileModel, UIImageView;

@interface QKProfileCell : UITableViewCell <LCTableViewCellConfigure>
{
    QKProfileModel *_profileModel;
    UIImageView *_avatarIV;
}

@property(retain, nonatomic) UIImageView *avatarIV; // @synthesize avatarIV=_avatarIV;
@property(retain, nonatomic) QKProfileModel *profileModel; // @synthesize profileModel=_profileModel;
- (void).cxx_destruct;
- (void)updateUI:(id)arg1;
- (void)configureCellWithModel:(id)arg1;
- (void)layoutSubviews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

