//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QKContentModel.h"

@class NSDate, NSMutableAttributedString, NSString;

@interface QKPushBoxItemModel : QKContentModel
{
    double _time;
    NSString *_timeString;
    NSMutableAttributedString *_attString;
    NSDate *_date;
    NSString *_content_id;
}

@property(copy, nonatomic) NSString *content_id; // @synthesize content_id=_content_id;
@property(retain, nonatomic) NSDate *date; // @synthesize date=_date;
@property(retain, nonatomic) NSMutableAttributedString *attString; // @synthesize attString=_attString;
@property(copy, nonatomic) NSString *timeString; // @synthesize timeString=_timeString;
@property(nonatomic) double time; // @synthesize time=_time;
- (void).cxx_destruct;
- (double)rowHeight;
- (id)initWithAttribute:(id)arg1;

@end

