//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "LCBaseModel.h"

@class NSString;

@interface QKReadAntiCheatingModel : LCBaseModel
{
    double _read_length_limit;
    NSString *_read_length_limit_tips;
    NSString *_read_times_limit_tips;
    double _read_multiple;
    double _read_rate;
    double _read_random;
}

@property(nonatomic) double read_random; // @synthesize read_random=_read_random;
@property(nonatomic) double read_rate; // @synthesize read_rate=_read_rate;
@property(nonatomic) double read_multiple; // @synthesize read_multiple=_read_multiple;
@property(copy, nonatomic) NSString *read_times_limit_tips; // @synthesize read_times_limit_tips=_read_times_limit_tips;
@property(copy, nonatomic) NSString *read_length_limit_tips; // @synthesize read_length_limit_tips=_read_length_limit_tips;
@property(nonatomic) double read_length_limit; // @synthesize read_length_limit=_read_length_limit;
- (void).cxx_destruct;
- (id)initWithAttribute:(id)arg1;

@end

