//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class QKReadAntiCheatingView;

@interface QKReadAntiCheatingManager : NSObject
{
    double _lengthLimit;
    QKReadAntiCheatingView *_readAntiCheatingView;
}

@property(nonatomic) __weak QKReadAntiCheatingView *readAntiCheatingView; // @synthesize readAntiCheatingView=_readAntiCheatingView;
@property(nonatomic) double lengthLimit; // @synthesize lengthLimit=_lengthLimit;
- (void).cxx_destruct;
- (void)dealloc;
- (void)showReadAntiCheatingTypeLengthDirectly;
- (void)showReadAntiCheatingTypeLengthIndirectly;
- (void)antiCheatingWithModel:(id)arg1 lengthLimit:(double)arg2 view:(id)arg3;

@end

