//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QKView.h"

@class QKPackageModel, UIButton, UIControl, UIImageView, UILabel;
@protocol QKRedPackageViewDelegate;

@interface QKRedPackageView : QKView
{
    UIControl *_overlayView;
    UIButton *_confirmButton;
    QKPackageModel *_gift;
    id <QKRedPackageViewDelegate> _delegate;
    UIImageView *_header;
    UIImageView *_footer;
    UIImageView *_money;
    UILabel *_hint_3;
    UILabel *_footer_hint;
    UILabel *_header_hint;
    UILabel *_header_hint1;
    UILabel *_header_hint2;
    UIButton *_open_redPackage;
    UIImageView *_gifView;
    double _displayTime;
    QKPackageModel *_model;
}

@property(retain, nonatomic) QKPackageModel *model; // @synthesize model=_model;
@property(nonatomic) double displayTime; // @synthesize displayTime=_displayTime;
@property(retain, nonatomic) UIImageView *gifView; // @synthesize gifView=_gifView;
@property(retain, nonatomic) UIButton *open_redPackage; // @synthesize open_redPackage=_open_redPackage;
@property(retain, nonatomic) UILabel *header_hint2; // @synthesize header_hint2=_header_hint2;
@property(retain, nonatomic) UILabel *header_hint1; // @synthesize header_hint1=_header_hint1;
@property(retain, nonatomic) UILabel *header_hint; // @synthesize header_hint=_header_hint;
@property(retain, nonatomic) UILabel *footer_hint; // @synthesize footer_hint=_footer_hint;
@property(retain, nonatomic) UILabel *hint_3; // @synthesize hint_3=_hint_3;
@property(retain, nonatomic) UIImageView *money; // @synthesize money=_money;
@property(retain, nonatomic) UIImageView *footer; // @synthesize footer=_footer;
@property(retain, nonatomic) UIImageView *header; // @synthesize header=_header;
@property(nonatomic) __weak id <QKRedPackageViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) QKPackageModel *gift; // @synthesize gift=_gift;
@property(retain, nonatomic) UIButton *confirmButton; // @synthesize confirmButton=_confirmButton;
@property(retain, nonatomic) UIControl *overlayView; // @synthesize overlayView=_overlayView;
- (void).cxx_destruct;
- (void)open_redPackage:(id)arg1;
- (void)openPackage;
- (id)initWithGift:(id)arg1;
- (void)dismiss;
- (void)close;
- (void)confirm;
- (void)show;
- (void)dealloc;

@end

