//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "LCBaseModel.h"

@class NSDictionary;

@interface QKread_timer_config : LCBaseModel
{
    NSDictionary *_tasks;
    NSDictionary *_next_task;
    NSDictionary *_curr_task;
    NSDictionary *_read_conf;
}

@property(retain, nonatomic) NSDictionary *read_conf; // @synthesize read_conf=_read_conf;
@property(retain, nonatomic) NSDictionary *curr_task; // @synthesize curr_task=_curr_task;
@property(retain, nonatomic) NSDictionary *next_task; // @synthesize next_task=_next_task;
@property(retain, nonatomic) NSDictionary *tasks; // @synthesize tasks=_tasks;
- (void).cxx_destruct;
- (id)initWithAttribute:(id)arg1;

@end

