//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITabBarController.h>

#import "QKRedPackageViewDelegate-Protocol.h"
#import "SplashViewDelegate-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"
#import "UITabBarControllerDelegate-Protocol.h"
#import "UITabBarDelegate-Protocol.h"

@class NSString, QKPackageModel, QKTabbarConfig, UIButton, UIView;

@interface QKRootViewController : UITabBarController <QKRedPackageViewDelegate, UIScrollViewDelegate, SplashViewDelegate, UITabBarControllerDelegate, UITabBarDelegate>
{
    UIButton *_redPacket;
    long long _redPacket_shake_times;
    QKPackageModel *_packageModel;
    NSString *_indexRecordKey;
    UIView *_myPageBageValue;
    QKTabbarConfig *_tabbarConfig;
}

@property(retain, nonatomic) QKTabbarConfig *tabbarConfig; // @synthesize tabbarConfig=_tabbarConfig;
@property(retain, nonatomic) UIView *myPageBageValue; // @synthesize myPageBageValue=_myPageBageValue;
@property(retain, nonatomic) NSString *indexRecordKey; // @synthesize indexRecordKey=_indexRecordKey;
@property(retain, nonatomic) QKPackageModel *packageModel; // @synthesize packageModel=_packageModel;
@property(nonatomic) long long redPacket_shake_times; // @synthesize redPacket_shake_times=_redPacket_shake_times;
@property(retain, nonatomic) UIButton *redPacket; // @synthesize redPacket=_redPacket;
- (void).cxx_destruct;
- (void)gotoHomeFromViewController:(id)arg1;
- (void)reloadHomeFromViewController:(id)arg1;
- (void)splashViewClickedWithDpUrl:(id)arg1 dpCurl:(id)arg2 cUrl:(id)arg3 needTrace:(_Bool)arg4;
- (void)splashViewClickedWithurl:(id)arg1;
- (id)isExitClipBoardGift;
- (void)showRedPackage;
- (void)updateMyPage;
- (_Bool)containsMission;
- (unsigned long long)indexWithKey:(id)arg1;
- (void)heart;
- (void)showMsgPush;
- (void)bannerDidClick:(id)arg1;
- (void)delayMethod:(id)arg1;
- (void)showNewController:(id)arg1;
- (void)checkPushMsgs;
- (void)lanuchCheckPushMsgs;
- (void)updatePushBox:(_Bool)arg1;
- (void)selectedIndexKey:(id)arg1;
- (void)userLogout:(id)arg1;
- (void)notification_logout:(id)arg1;
- (void)moveRedPacketToIndex:(unsigned long long)arg1;
- (void)setSelectedIndex:(unsigned long long)arg1;
- (void)tabBarController:(id)arg1 didSelectViewController:(id)arg2;
- (void)switchIndex:(long long)arg1 toIndex:(long long)arg2;
- (void)refreshIndex:(long long)arg1;
- (_Bool)tabBarController:(id)arg1 shouldSelectViewController:(id)arg2;
- (id)getNewTabbarConfig;
- (void)checkTabbarUpdateAndChange;
- (void)updateNewTabbarAndViewController;
- (void)checkTabbarRemoveOrHidden;
- (_Bool)checkTabbarConfigHaveChange;
- (id)getController:(id)arg1;
- (void)setupViewControllers;
- (void)showRedpackage;
- (void)shakeView:(id)arg1;
- (void)beginShakeRedPacket;
- (void)giftReceiveClose;
- (void)giftReceiveFailure;
- (void)giftReceiveSucess:(id)arg1;
- (void)reciveRedpackage;
- (void)openPackage;
- (void)fristShowRedPage;
- (void)showInvitePage;
- (void)viewDidAppear:(_Bool)arg1;
- (void)setRedPacketHidden:(_Bool)arg1;
- (void)showSplashView;
- (void)viewDidLoad;
- (void)initTabBarItems;
- (void)viewDidLayoutSubviews;
- (void)getClipboardRegex;
- (void)handleClipBoardGifShow;
- (void)handleDeepLink;
- (void)notification_enter_foreground:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

