//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "LCBaseModel.h"

@class NSMutableArray;

@interface QKSearchTableModel : LCBaseModel
{
    NSMutableArray *_contents;
    NSMutableArray *_subcripts;
    long long _num;
}

@property(nonatomic) long long num; // @synthesize num=_num;
@property(retain, nonatomic) NSMutableArray *subcripts; // @synthesize subcripts=_subcripts;
@property(retain, nonatomic) NSMutableArray *contents; // @synthesize contents=_contents;
- (void).cxx_destruct;
- (id)initWithAttribute:(id)arg1 cdns:(id)arg2;
- (id)initWithAttribute:(id)arg1 info:(id)arg2;

@end

