//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QKView.h"

#import "UITextViewDelegate-Protocol.h"

@class NSDictionary, NSString, QKContentModel, QKTextView, UIButton, UIControl, UILabel;

@interface QKSendBox : QKView <UITextViewDelegate>
{
    _Bool _is_sending;
    QKTextView *_sendBox;
    NSString *_placeholderText;
    long long _sendType;
    UILabel *_placeholder;
    QKContentModel *_contentModel;
    NSDictionary *_params;
    UIControl *_overlayView;
    UILabel *_textLabel;
    UIButton *_sendButton;
}

@property(retain, nonatomic) UIButton *sendButton; // @synthesize sendButton=_sendButton;
@property(retain, nonatomic) UILabel *textLabel; // @synthesize textLabel=_textLabel;
@property(retain, nonatomic) UIControl *overlayView; // @synthesize overlayView=_overlayView;
@property(retain, nonatomic) NSDictionary *params; // @synthesize params=_params;
@property(retain, nonatomic) QKContentModel *contentModel; // @synthesize contentModel=_contentModel;
@property(retain, nonatomic) UILabel *placeholder; // @synthesize placeholder=_placeholder;
@property(nonatomic) long long sendType; // @synthesize sendType=_sendType;
@property(retain, nonatomic) NSString *placeholderText; // @synthesize placeholderText=_placeholderText;
@property(retain, nonatomic) QKTextView *sendBox; // @synthesize sendBox=_sendBox;
- (void).cxx_destruct;
- (void)keyboardHide:(id)arg1;
- (void)keyboardWillChangeFrame:(id)arg1;
- (void)sendAction;
- (void)cancelAction;
- (void)show;
- (void)textViewDidChange:(id)arg1;
- (_Bool)textViewShouldBeginEditing:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

