//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QKHomeTableCell.h"

#import "LCTableViewCellConfigure-Protocol.h"

@class NSString, UILabel, UIScrollView, UIView;
@protocol QKShortVideoCellDelegate;

@interface QKShortVideoCell : QKHomeTableCell <LCTableViewCellConfigure>
{
    id <QKShortVideoCellDelegate> _shortVideoCellDelegate;
    UIScrollView *_scrollView;
    UIView *_containerView;
    UILabel *_shortVideoTag;
}

@property(retain, nonatomic) UILabel *shortVideoTag; // @synthesize shortVideoTag=_shortVideoTag;
@property(retain, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(nonatomic) __weak id <QKShortVideoCellDelegate> shortVideoCellDelegate; // @synthesize shortVideoCellDelegate=_shortVideoCellDelegate;
- (void).cxx_destruct;
- (void)didClickShortVideo:(id)arg1;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)update:(id)arg1;
- (void)layoutUI;
- (void)createUI;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)configureCellWithModel:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

