//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIButton, UIImageView, UILabel;

@interface QKShortVideoExceptionView : UIView
{
    int _type;
    UIButton *_clickBtn;
    UIView *_contentView;
    UIImageView *_iconImageView;
    UILabel *_titleLabel;
}

+ (id)shortVideoExceptionView;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIImageView *iconImageView; // @synthesize iconImageView=_iconImageView;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(nonatomic) int type; // @synthesize type=_type;
@property(retain, nonatomic) UIButton *clickBtn; // @synthesize clickBtn=_clickBtn;
- (void).cxx_destruct;
- (void)setupUI;
- (void)layoutSubviews;
- (id)init;
- (void)showExceptionViewViewWith:(id)arg1 withType:(int)arg2;

@end

