//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QKView.h"

@class QKContentModel, QKSendBox, UIControl, UIImageView, UILabel;

@interface QKShortVideoContentToolBar : QKView
{
    QKContentModel *_contentModel;
    QKSendBox *_sendBox;
    UIControl *_commentControl;
    UIControl *_commentListControl;
    UIControl *_collectionControl;
    UIControl *_likeControl;
    UIControl *_shareControl;
    UILabel *_commentCountLabel;
    UIImageView *_commentImgv;
    UIImageView *_collectionImgv;
    UIImageView *_writeCommentImgv;
    UILabel *_commentLabel;
    UILabel *_collectionCountLabel;
    UIImageView *_likeImgv;
    UILabel *_likeCountLabel;
    UIImageView *_shareImgv;
    UILabel *_shareLabel;
}

@property(retain, nonatomic) UILabel *shareLabel; // @synthesize shareLabel=_shareLabel;
@property(retain, nonatomic) UIImageView *shareImgv; // @synthesize shareImgv=_shareImgv;
@property(retain, nonatomic) UILabel *likeCountLabel; // @synthesize likeCountLabel=_likeCountLabel;
@property(retain, nonatomic) UIImageView *likeImgv; // @synthesize likeImgv=_likeImgv;
@property(retain, nonatomic) UILabel *collectionCountLabel; // @synthesize collectionCountLabel=_collectionCountLabel;
@property(retain, nonatomic) UILabel *commentLabel; // @synthesize commentLabel=_commentLabel;
@property(retain, nonatomic) UIImageView *writeCommentImgv; // @synthesize writeCommentImgv=_writeCommentImgv;
@property(retain, nonatomic) UIImageView *collectionImgv; // @synthesize collectionImgv=_collectionImgv;
@property(retain, nonatomic) UIImageView *commentImgv; // @synthesize commentImgv=_commentImgv;
@property(retain, nonatomic) UILabel *commentCountLabel; // @synthesize commentCountLabel=_commentCountLabel;
@property(retain, nonatomic) UIControl *shareControl; // @synthesize shareControl=_shareControl;
@property(retain, nonatomic) UIControl *likeControl; // @synthesize likeControl=_likeControl;
@property(retain, nonatomic) UIControl *collectionControl; // @synthesize collectionControl=_collectionControl;
@property(retain, nonatomic) UIControl *commentListControl; // @synthesize commentListControl=_commentListControl;
@property(retain, nonatomic) UIControl *commentControl; // @synthesize commentControl=_commentControl;
@property(retain, nonatomic) QKSendBox *sendBox; // @synthesize sendBox=_sendBox;
@property(retain, nonatomic) QKContentModel *contentModel; // @synthesize contentModel=_contentModel;
- (void).cxx_destruct;
- (void)commentAction:(id)arg1;
- (void)setBackgroundColorAlpha:(double)arg1;
- (void)configUI:(id)arg1;
- (void)layoutUI;
- (void)createUI;
- (id)initWithFrame:(struct CGRect)arg1;

@end

