//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSArray, NSMutableArray, NSString, UIImage;

@interface QKShareModel : NSObject
{
    NSString *_app_id;
    NSString *_shareID;
    NSString *_url;
    NSString *_cover;
    NSArray *_coverArray;
    NSString *_title;
    NSString *_descri;
    UIImage *_image;
    NSMutableArray *_images;
    long long _dataType;
    long long _objective;
}

@property(nonatomic) long long objective; // @synthesize objective=_objective;
@property(nonatomic) long long dataType; // @synthesize dataType=_dataType;
@property(retain, nonatomic) NSMutableArray *images; // @synthesize images=_images;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
@property(retain, nonatomic) NSString *descri; // @synthesize descri=_descri;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) NSArray *coverArray; // @synthesize coverArray=_coverArray;
@property(retain, nonatomic) NSString *cover; // @synthesize cover=_cover;
@property(retain, nonatomic) NSString *url; // @synthesize url=_url;
@property(retain, nonatomic) NSString *shareID; // @synthesize shareID=_shareID;
@property(retain, nonatomic) NSString *app_id; // @synthesize app_id=_app_id;
- (void).cxx_destruct;

@end

