//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "LCBaseModel.h"

@class NSString;

@interface QKShareContent : LCBaseModel
{
    NSString *_invite_title;
    NSString *_invite_url;
    NSString *_invite_icon;
    NSString *_invite_desc;
    NSString *_ios_way;
    NSString *_ios_appid;
    NSString *_invite_background;
}

@property(retain, nonatomic) NSString *invite_background; // @synthesize invite_background=_invite_background;
@property(retain, nonatomic) NSString *ios_appid; // @synthesize ios_appid=_ios_appid;
@property(retain, nonatomic) NSString *ios_way; // @synthesize ios_way=_ios_way;
@property(retain, nonatomic) NSString *invite_desc; // @synthesize invite_desc=_invite_desc;
@property(retain, nonatomic) NSString *invite_icon; // @synthesize invite_icon=_invite_icon;
@property(retain, nonatomic) NSString *invite_url; // @synthesize invite_url=_invite_url;
@property(retain, nonatomic) NSString *invite_title; // @synthesize invite_title=_invite_title;
- (void).cxx_destruct;
- (id)initWithAttribute:(id)arg1;

@end

