//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "LCBaseModel.h"

@class NSMutableAttributedString, NSString;

@interface QKSubcript : LCBaseModel
{
    _Bool _isUpdate;
    _Bool _is_exit_video;
    _Bool _is_exit_article;
    _Bool _show_article;
    _Bool _is_selected;
    _Bool _is_pv_report;
    NSString *_article_url;
    NSString *_avatar;
    NSString *_create_time;
    NSString *_descriptions;
    NSString *_id;
    long long _is_rss;
    long long _is_show;
    long long _comment_num;
    long long _follow_num;
    long long _pv_num;
    long long _fav_num;
    NSString *_comment_num_show;
    NSString *_fav_num_show;
    NSString *_follow_num_show;
    NSString *_pv_num_show;
    NSString *_keyword;
    NSMutableAttributedString *_keyword_title;
    NSMutableAttributedString *_keyword_desc;
    NSString *_publish_time;
    long long _update_time;
    long long _last_read_timex;
    NSString *_qr_code;
    NSString *_round_avatar;
    NSString *_status;
    NSString *_type;
    NSString *_source_type;
    NSString *_exponent_type_top_show;
    NSString *_url;
    NSString *_pv_id;
    NSString *_last_title;
    NSString *_source;
    NSString *_type_time;
    NSString *_wx_id;
    NSString *_wx_name;
    double _rowHeight;
    long long _row_index;
}

@property(nonatomic) long long row_index; // @synthesize row_index=_row_index;
@property(nonatomic) double rowHeight; // @synthesize rowHeight=_rowHeight;
@property(retain, nonatomic) NSString *wx_name; // @synthesize wx_name=_wx_name;
@property(retain, nonatomic) NSString *wx_id; // @synthesize wx_id=_wx_id;
@property(nonatomic) _Bool is_pv_report; // @synthesize is_pv_report=_is_pv_report;
@property(nonatomic) _Bool is_selected; // @synthesize is_selected=_is_selected;
@property(nonatomic) _Bool show_article; // @synthesize show_article=_show_article;
@property(nonatomic) _Bool is_exit_article; // @synthesize is_exit_article=_is_exit_article;
@property(nonatomic) _Bool is_exit_video; // @synthesize is_exit_video=_is_exit_video;
@property(nonatomic) _Bool isUpdate; // @synthesize isUpdate=_isUpdate;
@property(retain, nonatomic) NSString *type_time; // @synthesize type_time=_type_time;
@property(retain, nonatomic) NSString *source; // @synthesize source=_source;
@property(retain, nonatomic) NSString *last_title; // @synthesize last_title=_last_title;
@property(retain, nonatomic) NSString *pv_id; // @synthesize pv_id=_pv_id;
@property(retain, nonatomic) NSString *url; // @synthesize url=_url;
@property(retain, nonatomic) NSString *exponent_type_top_show; // @synthesize exponent_type_top_show=_exponent_type_top_show;
@property(retain, nonatomic) NSString *source_type; // @synthesize source_type=_source_type;
@property(retain, nonatomic) NSString *type; // @synthesize type=_type;
@property(retain, nonatomic) NSString *status; // @synthesize status=_status;
@property(retain, nonatomic) NSString *round_avatar; // @synthesize round_avatar=_round_avatar;
@property(retain, nonatomic) NSString *qr_code; // @synthesize qr_code=_qr_code;
@property(nonatomic) long long last_read_timex; // @synthesize last_read_timex=_last_read_timex;
@property(nonatomic) long long update_time; // @synthesize update_time=_update_time;
@property(retain, nonatomic) NSString *publish_time; // @synthesize publish_time=_publish_time;
@property(retain, nonatomic) NSMutableAttributedString *keyword_desc; // @synthesize keyword_desc=_keyword_desc;
@property(retain, nonatomic) NSMutableAttributedString *keyword_title; // @synthesize keyword_title=_keyword_title;
@property(retain, nonatomic) NSString *keyword; // @synthesize keyword=_keyword;
@property(retain, nonatomic) NSString *pv_num_show; // @synthesize pv_num_show=_pv_num_show;
@property(retain, nonatomic) NSString *follow_num_show; // @synthesize follow_num_show=_follow_num_show;
@property(retain, nonatomic) NSString *fav_num_show; // @synthesize fav_num_show=_fav_num_show;
@property(retain, nonatomic) NSString *comment_num_show; // @synthesize comment_num_show=_comment_num_show;
@property(nonatomic) long long fav_num; // @synthesize fav_num=_fav_num;
@property(nonatomic) long long pv_num; // @synthesize pv_num=_pv_num;
@property(nonatomic) long long follow_num; // @synthesize follow_num=_follow_num;
@property(nonatomic) long long comment_num; // @synthesize comment_num=_comment_num;
@property(nonatomic) long long is_show; // @synthesize is_show=_is_show;
@property(nonatomic) long long is_rss; // @synthesize is_rss=_is_rss;
@property(retain, nonatomic) NSString *id; // @synthesize id=_id;
@property(retain, nonatomic) NSString *descriptions; // @synthesize descriptions=_descriptions;
@property(retain, nonatomic) NSString *create_time; // @synthesize create_time=_create_time;
@property(retain, nonatomic) NSString *avatar; // @synthesize avatar=_avatar;
@property(retain, nonatomic) NSString *article_url; // @synthesize article_url=_article_url;
- (void).cxx_destruct;
- (id)cellKey;
- (long long)last_read_time:(id)arg1;
- (id)initWithAttribute:(id)arg1;

@end

