//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QKBaseViewController.h"

#import "BaseCellProtocol-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class LCBaseTableView, NSMutableArray, NSString, UIView;

@interface QKSubcriptViewController : QKBaseViewController <UITableViewDataSource, UITableViewDelegate, BaseCellProtocol>
{
    long long _page;
    _Bool _follow_action;
    LCBaseTableView *_tableView;
    UIView *_tableFooterView;
    UIView *_tableHeaderView;
    NSMutableArray *_subcriptions;
    NSMutableArray *_hotSubcriptions;
}

@property(retain, nonatomic) NSMutableArray *hotSubcriptions; // @synthesize hotSubcriptions=_hotSubcriptions;
@property(retain, nonatomic) NSMutableArray *subcriptions; // @synthesize subcriptions=_subcriptions;
@property(retain, nonatomic) UIView *tableHeaderView; // @synthesize tableHeaderView=_tableHeaderView;
@property(retain, nonatomic) UIView *tableFooterView; // @synthesize tableFooterView=_tableFooterView;
@property(retain, nonatomic) LCBaseTableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) _Bool follow_action; // @synthesize follow_action=_follow_action;
- (void).cxx_destruct;
- (void)endRefreshingWithPage:(long long)arg1;
- (void)loadSubcriptions:(long long)arg1;
- (void)loadHotSubcriptions;
- (void)addSubcript;
- (void)findMore;
- (void)subcriptAction;
- (void)didReceiveMemoryWarning;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)beginRefreshing;
- (void)reload;
- (void)logoutAction;
- (void)loadMore;
- (void)loadNew;
- (void)viewDidLoad;
- (void)notification_reload_subcript:(id)arg1;
- (void)showMangerSubcripts;
- (_Bool)searchBarShouldBeginEditing:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 titleForDeleteConfirmationButtonForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (_Bool)tableView:(id)arg1 canMoveRowAtIndexPath:(id)arg2;
- (_Bool)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (void)didElemsClick:(id)arg1 oper:(int)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

