//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QKTableViewCell.h"

@class QKSubcript, UIButton, UIImageView, UILabel;

@interface QKSubcriptCell : QKTableViewCell
{
    UIImageView *_avatar;
    UILabel *_nameLabel;
    UILabel *_timeLabel;
    UILabel *_depictLabel;
    UILabel *_readCount;
    UIButton *_subcriptButton;
    QKSubcript *_subcript;
    QKSubcript *_att_subcript;
}

@property(retain, nonatomic) QKSubcript *att_subcript; // @synthesize att_subcript=_att_subcript;
@property(retain, nonatomic) QKSubcript *subcript; // @synthesize subcript=_subcript;
@property(retain, nonatomic) UIButton *subcriptButton; // @synthesize subcriptButton=_subcriptButton;
@property(retain, nonatomic) UILabel *readCount; // @synthesize readCount=_readCount;
@property(retain, nonatomic) UILabel *depictLabel; // @synthesize depictLabel=_depictLabel;
@property(retain, nonatomic) UILabel *timeLabel; // @synthesize timeLabel=_timeLabel;
@property(retain, nonatomic) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(retain, nonatomic) UIImageView *avatar; // @synthesize avatar=_avatar;
- (void).cxx_destruct;
- (void)subcriptAction:(id)arg1;
- (void)update:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)dealloc;
- (void)loginAttAction;

@end

