//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITabBar.h>

@class NSMutableArray;

@interface QKTabBar : UITabBar
{
    NSMutableArray *_tabbarItemModels;
    NSMutableArray *_buttons;
}

@property(retain, nonatomic) NSMutableArray *buttons; // @synthesize buttons=_buttons;
@property(retain, nonatomic) NSMutableArray *tabbarItemModels; // @synthesize tabbarItemModels=_tabbarItemModels;
- (void).cxx_destruct;
- (void)stopAnimatingAtIndex:(long long)arg1;
- (void)startAnimatingAtIndex:(long long)arg1;
- (id)getImageViewAt;
- (id)getImageViewAtIndex:(long long)arg1;
- (id)getLabelAtIndex:(long long)arg1;
- (id)getArray;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)setFrame:(struct CGRect)arg1;

@end

