//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class LCBaseModel;
@protocol BaseCellProtocol;

@interface QKTableViewCell : UITableViewCell
{
    LCBaseModel *_object;
    id <BaseCellProtocol> _delegate;
}

@property(nonatomic) __weak id <BaseCellProtocol> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) LCBaseModel *object; // @synthesize object=_object;
- (void).cxx_destruct;
- (void)update:(id)arg1;
- (void)setRightPointHidden:(_Bool)arg1;
- (void)setLeftRedHidden:(_Bool)arg1;
- (void)setLeftRed_x:(double)arg1;
- (void)removeCustomLine;
- (void)addCustomLine:(double)arg1 rightIndent:(double)arg2;
- (void)addCustomLine:(double)arg1;
- (void)layoutSubviews;
- (void)awakeFromNib;
- (void)dealloc;

@end

