//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "LCBaseModel.h"

@interface QKTrackPoint : LCBaseModel
{
    _Bool _trackPointSwitch;
    long long _first_refresh_time;
    long long _first_refresh_num;
    long long _next_refresh_time;
    long long _next_refresh_num;
}

@property(nonatomic) long long next_refresh_num; // @synthesize next_refresh_num=_next_refresh_num;
@property(nonatomic) long long next_refresh_time; // @synthesize next_refresh_time=_next_refresh_time;
@property(nonatomic) long long first_refresh_num; // @synthesize first_refresh_num=_first_refresh_num;
@property(nonatomic) long long first_refresh_time; // @synthesize first_refresh_time=_first_refresh_time;
@property(nonatomic) _Bool trackPointSwitch; // @synthesize trackPointSwitch=_trackPointSwitch;
- (id)initWithAttribute:(id)arg1;

@end

