//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QKView.h"

@class UIButton;

@interface QKUserStyleView : QKView
{
    _Bool _isSelected;
    UIButton *_avatar;
    UIButton *_status;
    UIButton *_button;
    long long _style;
    CDUnknownBlockType _block;
}

@property(nonatomic) _Bool isSelected; // @synthesize isSelected=_isSelected;
@property(copy, nonatomic) CDUnknownBlockType block; // @synthesize block=_block;
@property(nonatomic) long long style; // @synthesize style=_style;
@property(retain, nonatomic) UIButton *button; // @synthesize button=_button;
@property(retain, nonatomic) UIButton *status; // @synthesize status=_status;
@property(retain, nonatomic) UIButton *avatar; // @synthesize avatar=_avatar;
- (void).cxx_destruct;
- (id)imageWithStyle:(long long)arg1;
- (void)touch:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1 style:(long long)arg2;

@end

