//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "LCBaseModel.h"

@class NSDictionary, NSMutableArray, NSString, ShareConfig;

@interface QKUser : LCBaseModel
{
    _Bool _msg_tips_enable;
    int _is_bind_wx;
    int _is_bind_alipay;
    int _is_bind_invite_code;
    int _welfare_show_first;
    NSString *_nickname;
    NSString *_member_name;
    NSString *_wx_nickname;
    NSString *_alipay_nickname;
    long long _is_official;
    NSString *_avatar;
    NSString *_birth;
    NSString *_constellation;
    long long _age;
    long long _is_interest_collect_sucess;
    NSString *_memberId;
    NSString *_balance;
    NSString *_coin;
    NSString *_inviteCode;
    NSString *_teacherId;
    NSString *_phone;
    NSString *_profession;
    NSString *_profession_key;
    NSString *_industry;
    NSString *_education;
    NSString *_education_key;
    NSString *_introduction;
    long long _sex;
    NSDictionary *_H5URL;
    NSMutableArray *_banners;
    NSMutableArray *_funcs;
    NSDictionary *_msg_tips;
    NSDictionary *_read_time;
    ShareConfig *_share_config;
}

@property(nonatomic) int welfare_show_first; // @synthesize welfare_show_first=_welfare_show_first;
@property(retain, nonatomic) ShareConfig *share_config; // @synthesize share_config=_share_config;
@property(retain, nonatomic) NSDictionary *read_time; // @synthesize read_time=_read_time;
@property(retain, nonatomic) NSDictionary *msg_tips; // @synthesize msg_tips=_msg_tips;
@property(nonatomic) _Bool msg_tips_enable; // @synthesize msg_tips_enable=_msg_tips_enable;
@property(retain, nonatomic) NSMutableArray *funcs; // @synthesize funcs=_funcs;
@property(retain, nonatomic) NSMutableArray *banners; // @synthesize banners=_banners;
@property(retain, nonatomic) NSDictionary *H5URL; // @synthesize H5URL=_H5URL;
@property(nonatomic) int is_bind_invite_code; // @synthesize is_bind_invite_code=_is_bind_invite_code;
@property(nonatomic) int is_bind_alipay; // @synthesize is_bind_alipay=_is_bind_alipay;
@property(nonatomic) int is_bind_wx; // @synthesize is_bind_wx=_is_bind_wx;
@property(nonatomic) long long sex; // @synthesize sex=_sex;
@property(copy, nonatomic) NSString *introduction; // @synthesize introduction=_introduction;
@property(copy, nonatomic) NSString *education_key; // @synthesize education_key=_education_key;
@property(copy, nonatomic) NSString *education; // @synthesize education=_education;
@property(copy, nonatomic) NSString *industry; // @synthesize industry=_industry;
@property(copy, nonatomic) NSString *profession_key; // @synthesize profession_key=_profession_key;
@property(copy, nonatomic) NSString *profession; // @synthesize profession=_profession;
@property(copy, nonatomic) NSString *phone; // @synthesize phone=_phone;
@property(copy, nonatomic) NSString *teacherId; // @synthesize teacherId=_teacherId;
@property(copy, nonatomic) NSString *inviteCode; // @synthesize inviteCode=_inviteCode;
@property(copy, nonatomic) NSString *coin; // @synthesize coin=_coin;
@property(copy, nonatomic) NSString *balance; // @synthesize balance=_balance;
@property(copy, nonatomic) NSString *memberId; // @synthesize memberId=_memberId;
@property(nonatomic) long long is_interest_collect_sucess; // @synthesize is_interest_collect_sucess=_is_interest_collect_sucess;
@property(nonatomic) long long age; // @synthesize age=_age;
@property(copy, nonatomic) NSString *constellation; // @synthesize constellation=_constellation;
@property(copy, nonatomic) NSString *birth; // @synthesize birth=_birth;
@property(copy, nonatomic) NSString *avatar; // @synthesize avatar=_avatar;
@property(nonatomic) long long is_official; // @synthesize is_official=_is_official;
@property(copy, nonatomic) NSString *alipay_nickname; // @synthesize alipay_nickname=_alipay_nickname;
@property(copy, nonatomic) NSString *wx_nickname; // @synthesize wx_nickname=_wx_nickname;
@property(copy, nonatomic) NSString *member_name; // @synthesize member_name=_member_name;
@property(copy, nonatomic) NSString *nickname; // @synthesize nickname=_nickname;
- (void).cxx_destruct;
- (id)constellationByMonth:(long long)arg1 day:(long long)arg2;
- (void)analyseMenu:(id)arg1 info:(id)arg2;
- (id)initWithAttribute:(id)arg1 info:(id)arg2;

@end

