//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSTimer, QKCycleProgressBtn, UIButton, UIImageView, UILabel;

@interface QKVideoPlayEndView : UIView
{
    _Bool _isFullScreen;
    _Bool _isHor;
    _Bool _isPauseTimer;
    int _type;
    CDUnknownBlockType _nextBtnClickBlock;
    CDUnknownBlockType _backBtnClickBlock;
    CDUnknownBlockType _replayBtnClickBlock;
    CDUnknownBlockType _pauseBtnClickBlock;
    UIView *_contentView;
    UIImageView *_iconImageView;
    QKCycleProgressBtn *_nextBtn;
    UIButton *_sNextBtn;
    UIButton *_replayBtn;
    UIButton *_continueBtn;
    UILabel *_titleLabel;
    NSTimer *_timer;
}

+ (id)videoPlayEndView;
@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIButton *continueBtn; // @synthesize continueBtn=_continueBtn;
@property(retain, nonatomic) UIButton *replayBtn; // @synthesize replayBtn=_replayBtn;
@property(retain, nonatomic) UIButton *sNextBtn; // @synthesize sNextBtn=_sNextBtn;
@property(retain, nonatomic) QKCycleProgressBtn *nextBtn; // @synthesize nextBtn=_nextBtn;
@property(retain, nonatomic) UIImageView *iconImageView; // @synthesize iconImageView=_iconImageView;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(copy, nonatomic) CDUnknownBlockType pauseBtnClickBlock; // @synthesize pauseBtnClickBlock=_pauseBtnClickBlock;
@property(copy, nonatomic) CDUnknownBlockType replayBtnClickBlock; // @synthesize replayBtnClickBlock=_replayBtnClickBlock;
@property(copy, nonatomic) CDUnknownBlockType backBtnClickBlock; // @synthesize backBtnClickBlock=_backBtnClickBlock;
@property(copy, nonatomic) CDUnknownBlockType nextBtnClickBlock; // @synthesize nextBtnClickBlock=_nextBtnClickBlock;
@property(nonatomic) int type; // @synthesize type=_type;
@property(nonatomic) _Bool isPauseTimer; // @synthesize isPauseTimer=_isPauseTimer;
@property(nonatomic) _Bool isHor; // @synthesize isHor=_isHor;
@property(nonatomic) _Bool isFullScreen; // @synthesize isFullScreen=_isFullScreen;
- (void).cxx_destruct;
- (void)pasueBtnClick:(id)arg1;
- (void)replayBtnClick:(id)arg1;
- (void)nextBtnClick:(id)arg1;
- (void)sNextBtnClick:(id)arg1;
- (void)resumeTimer;
- (void)pasueTimer;
- (void)stopTimerAndHidden:(_Bool)arg1;
- (void)configureContentWithType:(int)arg1;
- (void)setup;
- (void)layoutSubviews;
- (id)init;
- (void)startWithCountDown:(double)arg1 withNeedPasue:(_Bool)arg2;
- (void)onlyShowMask;

@end

