//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "LCBaseModel.h"

@class NSString;

@interface QKVideoHoverAdsModel : LCBaseModel
{
    _Bool _enable;
    _Bool _close_btn_show;
    int _start_show_time;
    int _show_time;
    NSString *_ads_id;
}

@property(nonatomic) _Bool close_btn_show; // @synthesize close_btn_show=_close_btn_show;
@property(retain, nonatomic) NSString *ads_id; // @synthesize ads_id=_ads_id;
@property(nonatomic) int show_time; // @synthesize show_time=_show_time;
@property(nonatomic) int start_show_time; // @synthesize start_show_time=_start_show_time;
@property(nonatomic) _Bool enable; // @synthesize enable=_enable;
- (void).cxx_destruct;
- (id)initWithAttribute:(id)arg1;

@end

