//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "LCBaseModel.h"

@class NSString;

@interface QKVideoEndAdModel : LCBaseModel
{
    _Bool _enable;
    _Bool _skip_enable;
    NSString *_slotId;
    long long _ad_source;
    long long _countdown;
}

@property(nonatomic) _Bool skip_enable; // @synthesize skip_enable=_skip_enable;
@property(nonatomic) long long countdown; // @synthesize countdown=_countdown;
@property(nonatomic) long long ad_source; // @synthesize ad_source=_ad_source;
@property(retain, nonatomic) NSString *slotId; // @synthesize slotId=_slotId;
@property(nonatomic) _Bool enable; // @synthesize enable=_enable;
- (void).cxx_destruct;
- (id)initWithAttribute:(id)arg1;

@end

