//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QKBaseAdvertView.h"

@class NSTimer, QKAdImageView, QKAdvert, UIButton, UILabel;

@interface QKVideoEndAdvertView : QKBaseAdvertView
{
    QKAdImageView *_imageView;
    CDUnknownBlockType _dismissCompleteBlock;
    CDUnknownBlockType _skipBtnDismissBlock;
    QKAdvert *_advert;
    UILabel *_countDownLabel;
    UIButton *_skipBtn;
    NSTimer *_timer;
}

@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
@property(retain, nonatomic) UIButton *skipBtn; // @synthesize skipBtn=_skipBtn;
@property(retain, nonatomic) UILabel *countDownLabel; // @synthesize countDownLabel=_countDownLabel;
@property(retain, nonatomic) QKAdvert *advert; // @synthesize advert=_advert;
@property(copy, nonatomic) CDUnknownBlockType skipBtnDismissBlock; // @synthesize skipBtnDismissBlock=_skipBtnDismissBlock;
@property(copy, nonatomic) CDUnknownBlockType dismissCompleteBlock; // @synthesize dismissCompleteBlock=_dismissCompleteBlock;
@property(retain, nonatomic) QKAdImageView *imageView; // @synthesize imageView=_imageView;
- (void).cxx_destruct;
- (void)dismiss;
- (void)skipBtnDismiss;
- (void)dismissWithHasOverAdvertising;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)adClickReport;
- (void)adTouchesEndedClick;
- (void)stopTimer;
- (void)setupBtnJump;
- (void)update:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

