//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QKBaseViewController.h"

#import "IMYWebViewDelegate-Protocol.h"
#import "LCWebErrorViewDelegate-Protocol.h"
#import "QKCRMangerViewDelegate-Protocol.h"
#import "TSWebViewDelegate-Protocol.h"

@class IMYWebView, JavaScriptOC, NJKWebViewProgressView, NSString, QKContentModel, QKContentToolBar;

@interface QKVideoContentController : QKBaseViewController <IMYWebViewDelegate, LCWebErrorViewDelegate, QKCRMangerViewDelegate, TSWebViewDelegate>
{
    double _oldPanOffsetY;
    _Bool _is_report_read_time;
    _Bool _is_goto_comment;
    long long _cdn_ecount;
    NJKWebViewProgressView *_progressView;
    long long _statusBarStyle;
    _Bool _is_loading;
    QKContentModel *_videoModel;
    QKContentModel *_fromContentModel;
    JavaScriptOC *_javaScript;
    NSString *_callback;
    QKContentToolBar *_toolBar;
    IMYWebView *_webView;
    NSString *_request_url;
}

+ (id)videoController:(id)arg1;
@property(nonatomic) _Bool is_loading; // @synthesize is_loading=_is_loading;
@property(copy, nonatomic) NSString *request_url; // @synthesize request_url=_request_url;
@property(retain, nonatomic) IMYWebView *webView; // @synthesize webView=_webView;
@property(retain, nonatomic) QKContentToolBar *toolBar; // @synthesize toolBar=_toolBar;
@property(copy, nonatomic) NSString *callback; // @synthesize callback=_callback;
@property(retain, nonatomic) JavaScriptOC *javaScript; // @synthesize javaScript=_javaScript;
@property(retain, nonatomic) QKContentModel *fromContentModel; // @synthesize fromContentModel=_fromContentModel;
@property(retain, nonatomic) QKContentModel *videoModel; // @synthesize videoModel=_videoModel;
- (void).cxx_destruct;
- (void)didPopRoot;
- (void)showCoinValue:(id)arg1 message:(id)arg2;
- (void)gotoComment;
- (void)commentAction:(id)arg1;
- (void)storeAction;
- (void)shareAction;
- (void)showFonts;
- (void)CRMangerUnlike:(id)arg1;
- (void)CRMangerReport:(id)arg1;
- (void)load;
- (_Bool)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(long long)arg3;
- (void)webView:(id)arg1 didCreateJavaScriptContext:(id)arg2;
- (void)showError:(id)arg1 webView:(id)arg2;
- (void)webView:(id)arg1 didFailLoadWithError:(id)arg2;
- (void)webViewDidFinishLoad:(id)arg1;
- (void)login:(id)arg1;
- (void)loginCallBack;
- (void)hideToolBar:(_Bool)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (id)webViewEx;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)showArticleNotFoundView;
- (void)loadContent;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (void)handleDeepLink;
- (void)notification_reload_subcript:(id)arg1;
- (void)contentFontChanged;
- (void)closeAction;
- (void)handleUIApplicatioDidEnterBackground:(id)arg1;
- (void)pVReport;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)endPlayVideo:(id)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (_Bool)shouldAutorotate;
- (_Bool)prefersStatusBarHidden;
- (long long)preferredStatusBarStyle;
- (void)back;
- (void)didReport;
- (void)didReload;
- (id)initWithModel:(id)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

