//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QKTableViewCell.h"

#import "LCTableViewCellConfigure-Protocol.h"

@class NSString, QKContentModel, UIButton, UIImageView, UILabel, UIView;
@protocol QKVideoCellDelegate;

@interface QKVideoCell : QKTableViewCell <LCTableViewCellConfigure>
{
    UIImageView *_videoView;
    UIImageView *_avatar;
    UIView *_interval;
    UIButton *_shareButton;
    UIButton *_commentButton;
    UILabel *_readLabel;
    UILabel *_contentLabel;
    UIImageView *_contentLabelBg;
    UILabel *_play_time_label;
    UIButton *_delButton;
    QKContentModel *_model;
    UIView *_videoPlayerBgView;
    id <QKVideoCellDelegate> _videoCellDelegate;
}

@property(nonatomic) __weak id <QKVideoCellDelegate> videoCellDelegate; // @synthesize videoCellDelegate=_videoCellDelegate;
@property(retain, nonatomic) UIView *videoPlayerBgView; // @synthesize videoPlayerBgView=_videoPlayerBgView;
@property(retain, nonatomic) QKContentModel *model; // @synthesize model=_model;
@property(retain, nonatomic) UIButton *delButton; // @synthesize delButton=_delButton;
@property(retain, nonatomic) UILabel *play_time_label; // @synthesize play_time_label=_play_time_label;
@property(retain, nonatomic) UIImageView *contentLabelBg; // @synthesize contentLabelBg=_contentLabelBg;
@property(retain, nonatomic) UILabel *contentLabel; // @synthesize contentLabel=_contentLabel;
@property(retain, nonatomic) UILabel *readLabel; // @synthesize readLabel=_readLabel;
@property(retain, nonatomic) UIButton *commentButton; // @synthesize commentButton=_commentButton;
@property(retain, nonatomic) UIButton *shareButton; // @synthesize shareButton=_shareButton;
@property(retain, nonatomic) UIView *interval; // @synthesize interval=_interval;
@property(retain, nonatomic) UIImageView *avatar; // @synthesize avatar=_avatar;
@property(retain, nonatomic) UIImageView *videoView; // @synthesize videoView=_videoView;
- (void).cxx_destruct;
- (void)didSelectVideo:(id)arg1;
- (void)gotoSubcript;
- (void)removeFav;
- (void)didConfirmFontSetting:(id)arg1;
- (void)didFontSettingChanged:(id)arg1;
- (void)dislike;
- (void)shareAction;
- (void)storeAction;
- (void)comment;
- (void)update:(id)arg1;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)configureCellWithModel:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

