//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "LCBaseModel.h"

@class NSString;

@interface QKWeiXinKey : LCBaseModel
{
    NSString *_app_id;
    NSString *_app_secret;
}

@property(copy, nonatomic) NSString *app_secret; // @synthesize app_secret=_app_secret;
@property(copy, nonatomic) NSString *app_id; // @synthesize app_id=_app_id;
- (void).cxx_destruct;
- (id)initWithAttribute:(id)arg1;

@end

