//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "LCBaseModel.h"

@class NSArray, NSString;

@interface QuCodeConfig : LCBaseModel
{
    NSString *_title_pic;
    NSArray *_share;
    NSString *_title;
    NSString *_desc;
    NSString *_desc_url;
}

@property(copy, nonatomic) NSString *desc_url; // @synthesize desc_url=_desc_url;
@property(copy, nonatomic) NSString *desc; // @synthesize desc=_desc;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) NSArray *share; // @synthesize share=_share;
@property(copy, nonatomic) NSString *title_pic; // @synthesize title_pic=_title_pic;
- (void).cxx_destruct;
- (id)initWithAttribute:(id)arg1;

@end

