//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class QKActivityCardModel, UIButton, UIControl, UIImageView, UILabel;

@interface RecallCardAlertView : UIView
{
    UIImageView *_avatar;
    UILabel *_nick;
    UILabel *_welcome;
    UILabel *_title;
    UILabel *_desc;
    UIButton *_button;
    UIControl *_overlayView;
    QKActivityCardModel *_card;
}

+ (void)dismiss;
+ (void)show:(id)arg1;
+ (id)recallCard;
@property(retain, nonatomic) QKActivityCardModel *card; // @synthesize card=_card;
@property(retain, nonatomic) UIControl *overlayView; // @synthesize overlayView=_overlayView;
@property(retain, nonatomic) UIButton *button; // @synthesize button=_button;
@property(retain, nonatomic) UILabel *desc; // @synthesize desc=_desc;
@property(retain, nonatomic) UILabel *title; // @synthesize title=_title;
@property(retain, nonatomic) UILabel *welcome; // @synthesize welcome=_welcome;
@property(retain, nonatomic) UILabel *nick; // @synthesize nick=_nick;
@property(retain, nonatomic) UIImageView *avatar; // @synthesize avatar=_avatar;
- (void).cxx_destruct;
- (void)update:(id)arg1;
- (void)initUI;
- (void)buttonAction:(id)arg1;
- (void)closeAction:(id)arg1;
- (void)dismiss;
- (id)initWithFrame:(struct CGRect)arg1;

@end

