//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "LCBaseModel.h"

@class NSArray, NSString;

@interface RedPacketsStyleModel : LCBaseModel
{
    NSString *_title;
    NSString *_imageURL;
    NSString *_h5_url;
    NSArray *_targets;
}

@property(retain, nonatomic) NSArray *targets; // @synthesize targets=_targets;
@property(copy, nonatomic) NSString *h5_url; // @synthesize h5_url=_h5_url;
@property(copy, nonatomic) NSString *imageURL; // @synthesize imageURL=_imageURL;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;
- (id)initWithAttribute:(id)arg1;

@end

