//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "LCBaseModel.h"

@class RedPacketsStyleModel;

@interface RedPacketsConfigModel : LCBaseModel
{
    _Bool _enabled;
    long long _start_time;
    long long _end_time;
    long long _start_countDown;
    long long _sev_time;
    RedPacketsStyleModel *_activityCountdownStyle;
    RedPacketsStyleModel *_activityNotStartStyle;
    RedPacketsStyleModel *_activityStartStyle;
    RedPacketsStyleModel *_activityEndStyle;
    long long _countDown_totalTime;
}

@property(nonatomic) long long countDown_totalTime; // @synthesize countDown_totalTime=_countDown_totalTime;
@property(retain, nonatomic) RedPacketsStyleModel *activityEndStyle; // @synthesize activityEndStyle=_activityEndStyle;
@property(retain, nonatomic) RedPacketsStyleModel *activityStartStyle; // @synthesize activityStartStyle=_activityStartStyle;
@property(retain, nonatomic) RedPacketsStyleModel *activityNotStartStyle; // @synthesize activityNotStartStyle=_activityNotStartStyle;
@property(retain, nonatomic) RedPacketsStyleModel *activityCountdownStyle; // @synthesize activityCountdownStyle=_activityCountdownStyle;
@property(nonatomic) long long sev_time; // @synthesize sev_time=_sev_time;
@property(nonatomic) long long start_countDown; // @synthesize start_countDown=_start_countDown;
@property(nonatomic) long long end_time; // @synthesize end_time=_end_time;
@property(nonatomic) long long start_time; // @synthesize start_time=_start_time;
@property(nonatomic) _Bool enabled; // @synthesize enabled=_enabled;
- (void).cxx_destruct;
- (id)initWithAttribute:(id)arg1;

@end

