//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "LCBaseModel.h"

@class NSArray, NSString;

@interface RegUnbindMasterModel : LCBaseModel
{
    int _enable;
    int _login_time;
    int _active_time;
    int _every_active_time;
    NSArray *_white;
    NSString *_gift_text;
    NSString *_text;
}

@property(retain, nonatomic) NSString *text; // @synthesize text=_text;
@property(retain, nonatomic) NSString *gift_text; // @synthesize gift_text=_gift_text;
@property(retain, nonatomic) NSArray *white; // @synthesize white=_white;
@property(nonatomic) int every_active_time; // @synthesize every_active_time=_every_active_time;
@property(nonatomic) int active_time; // @synthesize active_time=_active_time;
@property(nonatomic) int login_time; // @synthesize login_time=_login_time;
@property(nonatomic) int enable; // @synthesize enable=_enable;
- (void).cxx_destruct;
- (id)initWithAttribute:(id)arg1;

@end

