//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString, NSURL;

@interface Schemes : NSObject
{
    NSString *_id;
    NSString *_url;
    NSURL *_link;
    long long _isNeedLogin;
    NSString *_tab;
}

+ (id)schemes:(id)arg1;
@property(retain, nonatomic) NSString *tab; // @synthesize tab=_tab;
@property(nonatomic) long long isNeedLogin; // @synthesize isNeedLogin=_isNeedLogin;
@property(retain, nonatomic) NSURL *link; // @synthesize link=_link;
@property(retain, nonatomic) NSString *url; // @synthesize url=_url;
@property(retain, nonatomic) NSString *id; // @synthesize id=_id;
- (void).cxx_destruct;
- (SEL)action;
- (id)initWithLink:(id)arg1;

@end

