//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "MLLinkLabelDelegate-Protocol.h"

@class MLLinkLabel, NSArray, NSMutableArray, NSString, UIGestureRecognizer, UIImageView;

@interface SDTimeLineCellCommentView : UIView <MLLinkLabelDelegate>
{
    CDUnknownBlockType _didClickCommentLabelBlock;
    NSArray *_likeItemsArray;
    NSMutableArray *_commentItemsArray;
    UIImageView *_bgImageView;
    MLLinkLabel *_likeLabel;
    UIView *_likeLableBottomLine;
    NSMutableArray *_commentLabelsArray;
    UIGestureRecognizer *_gesture;
}

@property(retain, nonatomic) UIGestureRecognizer *gesture; // @synthesize gesture=_gesture;
@property(retain, nonatomic) NSMutableArray *commentLabelsArray; // @synthesize commentLabelsArray=_commentLabelsArray;
@property(retain, nonatomic) UIView *likeLableBottomLine; // @synthesize likeLableBottomLine=_likeLableBottomLine;
@property(retain, nonatomic) MLLinkLabel *likeLabel; // @synthesize likeLabel=_likeLabel;
@property(retain, nonatomic) UIImageView *bgImageView; // @synthesize bgImageView=_bgImageView;
@property(retain, nonatomic) NSMutableArray *commentItemsArray; // @synthesize commentItemsArray=_commentItemsArray;
@property(retain, nonatomic) NSArray *likeItemsArray; // @synthesize likeItemsArray=_likeItemsArray;
@property(copy, nonatomic) CDUnknownBlockType didClickCommentLabelBlock; // @synthesize didClickCommentLabelBlock=_didClickCommentLabelBlock;
- (void).cxx_destruct;
- (void)didClickLink:(id)arg1 linkText:(id)arg2 linkLabel:(id)arg3;
- (id)generateAttributedStringWithLikeItemModel:(id)arg1;
- (id)generateAttributedStringWithCommentItemModel:(id)arg1;
- (void)commentLabelTapped:(id)arg1;
- (void)setFrame:(struct CGRect)arg1;
- (void)setupWithLikeItemsArray:(id)arg1 commentItemsArray:(id)arg2;
- (void)freeze;
- (void)remove;
- (_Bool)canBecomeFirstResponder;
- (_Bool)canPerformAction:(SEL)arg1 withSender:(id)arg2;
- (void)report;
- (void)comment;
- (void)ensconce;
- (void)longPress:(id)arg1;
- (void)setupViews;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

