//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface SGQRCodeTool : NSObject
{
}

+ (id)SG_generateWithColorQRCodeData:(id)arg1 backgroundColor:(id)arg2 mainColor:(id)arg3;
+ (id)SG_generateWithLogoQRCodeData:(id)arg1 logoImageName:(id)arg2 logoScaleToSuperView:(double)arg3;
+ (id)createNonInterpolatedUIImageFormCIImage:(id)arg1 withSize:(double)arg2;
+ (id)SG_generateWithDefaultQRCodeData:(id)arg1 imageViewWidth:(double)arg2;

@end

