//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "WKNavigationDelegate-Protocol.h"
#import "WKUIDelegate-Protocol.h"

@class NSString, UIColor, UIProgressView, WKWebView;
@protocol SGWebViewDelegate;

@interface SGWebView : UIView <WKNavigationDelegate, WKUIDelegate>
{
    _Bool _isNavigationBarOrTranslucent;
    id <SGWebViewDelegate> _SGQRCodeDelegate;
    UIColor *_progressViewColor;
    NSString *_navigationItemTitle;
    WKWebView *_wkWebView;
    UIProgressView *_progressView;
}

+ (id)webViewWithFrame:(struct CGRect)arg1;
@property(retain, nonatomic) UIProgressView *progressView; // @synthesize progressView=_progressView;
@property(retain, nonatomic) WKWebView *wkWebView; // @synthesize wkWebView=_wkWebView;
@property(nonatomic) _Bool isNavigationBarOrTranslucent; // @synthesize isNavigationBarOrTranslucent=_isNavigationBarOrTranslucent;
@property(copy, nonatomic) NSString *navigationItemTitle; // @synthesize navigationItemTitle=_navigationItemTitle;
@property(retain, nonatomic) UIColor *progressViewColor; // @synthesize progressViewColor=_progressViewColor;
@property(nonatomic) __weak id <SGWebViewDelegate> SGQRCodeDelegate; // @synthesize SGQRCodeDelegate=_SGQRCodeDelegate;
- (void).cxx_destruct;
- (void)dealloc;
- (void)reloadData;
- (void)loadHTMLString:(id)arg1;
- (void)loadRequest:(id)arg1;
- (void)webView:(id)arg1 didFailNavigation:(id)arg2 withError:(id)arg3;
- (void)webView:(id)arg1 didFinishNavigation:(id)arg2;
- (void)webView:(id)arg1 didCommitNavigation:(id)arg2;
- (void)webView:(id)arg1 didStartProvisionalNavigation:(id)arg2;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

