//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QKTableViewCell.h"

@class QKContentModel, QKShareModel, UIScrollView, UIView;
@protocol ShortVideoShareCellDelegate;

@interface ShortVideoShareCell : QKTableViewCell
{
    id <ShortVideoShareCellDelegate> _shareDelegate;
    UIScrollView *_scrollView;
    UIView *_scrollContainerView;
    QKContentModel *_contentModel;
    QKShareModel *_shareModel;
}

@property(retain, nonatomic) QKShareModel *shareModel; // @synthesize shareModel=_shareModel;
@property(retain, nonatomic) QKContentModel *contentModel; // @synthesize contentModel=_contentModel;
@property(retain, nonatomic) UIView *scrollContainerView; // @synthesize scrollContainerView=_scrollContainerView;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(retain, nonatomic) id <ShortVideoShareCellDelegate> shareDelegate; // @synthesize shareDelegate=_shareDelegate;
- (void).cxx_destruct;
- (void)requestShareUrlCallback:(CDUnknownBlockType)arg1;
- (void)shareTimeline;
- (void)shareWXSession;
- (void)shareQZone;
- (void)shareQQ;
- (void)addShareItemAction:(id)arg1 type:(id)arg2;
- (id)shareType:(int)arg1;
- (void)configVideoModel:(id)arg1;
- (void)layoutUI;
- (void)createUI;
- (void)setupParam;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

