//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, QKContentModel;

@protocol ShortVideoPlayViewControllerDelegate <NSObject>

@optional
- (void)didDeleteDislikeContents:(NSArray *)arg1;
- (void)playVCWillPop;
- (void)playVCLastPageScrollToNext;
- (void)playVCDidChangePage:(QKContentModel *)arg1;
@end

