//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class UIImageView, UILabel;

@interface ShortVideoCollectionCell : UICollectionViewCell
{
    UIImageView *_coverImgv;
    UILabel *_titleLabel;
    UIImageView *_avatarImgv;
    UILabel *_nicknameLabel;
    UIImageView *_gradientImgv;
    UIImageView *_playPlaceholderImgv;
}

@property(retain, nonatomic) UIImageView *playPlaceholderImgv; // @synthesize playPlaceholderImgv=_playPlaceholderImgv;
@property(retain, nonatomic) UIImageView *gradientImgv; // @synthesize gradientImgv=_gradientImgv;
@property(retain, nonatomic) UILabel *nicknameLabel; // @synthesize nicknameLabel=_nicknameLabel;
@property(retain, nonatomic) UIImageView *avatarImgv; // @synthesize avatarImgv=_avatarImgv;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIImageView *coverImgv; // @synthesize coverImgv=_coverImgv;
- (void).cxx_destruct;
- (void)configUI:(id)arg1;
- (void)layoutUI;
- (void)createUI;
- (id)initWithFrame:(struct CGRect)arg1;

@end

