//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSMutableDictionary, NSString;

@interface Steps : NSObject
{
    _Bool _report;
    NSString *_unique;
    double _from;
    double _to;
    NSMutableDictionary *_steps;
}

@property(retain, nonatomic) NSMutableDictionary *steps; // @synthesize steps=_steps;
@property(nonatomic) double to; // @synthesize to=_to;
@property(nonatomic) double from; // @synthesize from=_from;
@property(retain, nonatomic) NSString *unique; // @synthesize unique=_unique;
@property(nonatomic) _Bool report; // @synthesize report=_report;
- (void).cxx_destruct;
- (unsigned int)duration;
- (unsigned int)steps_duration;
- (id)steps_info;
- (void)updateStepForKey:(id)arg1 status:(int)arg2;
- (void)updateTo;
- (void)startStepForKey:(id)arg1;
- (void)addStep:(id)arg1;
- (_Bool)should_report;
- (_Bool)valid;

@end

