//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "LCBaseModel.h"

@class NSString;

@interface SwitchPushInfo : LCBaseModel
{
    NSString *_ios_first_title;
    NSString *_ios_first;
    NSString *_ios_next;
}

@property(retain, nonatomic) NSString *ios_next; // @synthesize ios_next=_ios_next;
@property(retain, nonatomic) NSString *ios_first; // @synthesize ios_first=_ios_first;
@property(retain, nonatomic) NSString *ios_first_title; // @synthesize ios_first_title=_ios_first_title;
- (void).cxx_destruct;
- (id)initWithAttribute:(id)arg1;

@end

