//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "TYBasePageTabBarPrivateDelegate-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"

@class NSArray, NSString, TYBasePageTabBar, UIScrollView;
@protocol TYSlidePageScrollViewDataSource, TYSlidePageScrollViewDelegate;

@interface TYSlidePageScrollView : UIView <UIScrollViewDelegate, TYBasePageTabBarPrivateDelegate>
{
    struct {
        unsigned int horizenScrollToPageIndex:1;
        unsigned int horizenScrollViewDidScroll:1;
        unsigned int horizenScrollViewDidEndDecelerating:1;
        unsigned int horizenScrollViewWillBeginDragging:1;
        unsigned int verticalScrollViewDidScroll:1;
        unsigned int pageTabBarScrollOffset:1;
        unsigned int horizenScrollViewDoReloadPageIndex:1;
    } _delegateFlags;
    _Bool _automaticallyAdjustsScrollViewInsets;
    _Bool _pageTabBarIsStopOnTop;
    _Bool _needChangeOtherPage;
    id <TYSlidePageScrollViewDataSource> _dataSource;
    id <TYSlidePageScrollViewDelegate> _delegate;
    UIView *_headerView;
    TYBasePageTabBar *_pageTabBar;
    double _pageTabBarStopOnTopHeight;
    UIView *_footerView;
    long long _curPageIndex;
    double _changeToNextIndexWhenScrollToWidthOfPercent;
    UIScrollView *_horScrollView;
    UIView *_headerContentView;
    NSArray *_pageViewArray;
}

@property(retain, nonatomic) NSArray *pageViewArray; // @synthesize pageViewArray=_pageViewArray;
@property(nonatomic) __weak UIView *headerContentView; // @synthesize headerContentView=_headerContentView;
@property(nonatomic) __weak UIScrollView *horScrollView; // @synthesize horScrollView=_horScrollView;
@property(nonatomic) _Bool needChangeOtherPage; // @synthesize needChangeOtherPage=_needChangeOtherPage;
@property(nonatomic) double changeToNextIndexWhenScrollToWidthOfPercent; // @synthesize changeToNextIndexWhenScrollToWidthOfPercent=_changeToNextIndexWhenScrollToWidthOfPercent;
@property(readonly, nonatomic) long long curPageIndex; // @synthesize curPageIndex=_curPageIndex;
@property(retain, nonatomic) UIView *footerView; // @synthesize footerView=_footerView;
@property(nonatomic) double pageTabBarStopOnTopHeight; // @synthesize pageTabBarStopOnTopHeight=_pageTabBarStopOnTopHeight;
@property(nonatomic) _Bool pageTabBarIsStopOnTop; // @synthesize pageTabBarIsStopOnTop=_pageTabBarIsStopOnTop;
@property(retain, nonatomic) TYBasePageTabBar *pageTabBar; // @synthesize pageTabBar=_pageTabBar;
@property(retain, nonatomic) UIView *headerView; // @synthesize headerView=_headerView;
@property(nonatomic) _Bool automaticallyAdjustsScrollViewInsets; // @synthesize automaticallyAdjustsScrollViewInsets=_automaticallyAdjustsScrollViewInsets;
@property(nonatomic) __weak id <TYSlidePageScrollViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak id <TYSlidePageScrollViewDataSource> dataSource; // @synthesize dataSource=_dataSource;
- (void).cxx_destruct;
- (void)dealloc;
- (void)basePageTabBar:(id)arg1 clickedPageTabBarAtIndex:(long long)arg2;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)pageScrollViewDidScroll:(id)arg1 changeOtherPageViews:(_Bool)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (long long)indexOfPageScrollView:(id)arg1;
- (id)pageScrollViewForIndex:(long long)arg1;
- (void)scrollToPageIndex:(long long)arg1 nimated:(_Bool)arg2 force:(_Bool)arg3;
- (void)scrollToPageIndex:(long long)arg1 nimated:(_Bool)arg2;
- (void)reloadData;
- (void)resetPageScrollViewContentOffset;
- (void)changeAllPageScrollViewOffsetY:(double)arg1 isOnTop:(_Bool)arg2;
- (void)dealAllPageScrollViewMinContentSize;
- (void)dealPageScrollViewMinContentSize:(id)arg1;
- (double)scrollViewMinContentSizeHeight;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)addPageViewKeyPathOffsetWithOldIndex:(long long)arg1 newIndex:(long long)arg2;
- (void)updatePageViews;
- (void)updateFooterView;
- (void)updateHeaderContentView;
- (void)setViewControllerAdjustsScrollView;
- (void)addHeaderContentView;
- (void)addHorScrollView;
- (id)viewController;
- (void)resetPropertys;
- (void)setPropertys;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

