//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class TYSlidePageScrollView, UIScrollView;

@protocol TYSlidePageScrollViewDelegate <NSObject>

@optional
- (void)slidePageScrollView:(TYSlidePageScrollView *)arg1 clickedPageTabBarAtIndex:(long long)arg2;
- (void)slidePageScrollView:(TYSlidePageScrollView *)arg1 horizenScrollViewDoReloadPageIndex:(long long)arg2 force:(_Bool)arg3;
- (void)slidePageScrollView:(TYSlidePageScrollView *)arg1 horizenScrollViewDidEndDecelerating:(UIScrollView *)arg2;
- (void)slidePageScrollView:(TYSlidePageScrollView *)arg1 horizenScrollViewWillBeginDragging:(UIScrollView *)arg2;
- (void)slidePageScrollView:(TYSlidePageScrollView *)arg1 horizenScrollViewDidScroll:(UIScrollView *)arg2;
- (void)slidePageScrollView:(TYSlidePageScrollView *)arg1 horizenScrollToPageIndex:(long long)arg2;
- (void)slidePageScrollView:(TYSlidePageScrollView *)arg1 pageTabBarScrollOffset:(double)arg2 state:(unsigned long long)arg3;
- (void)slidePageScrollView:(TYSlidePageScrollView *)arg1 verticalScrollViewDidScroll:(UIScrollView *)arg2;
@end

