//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIAlertView.h>

@interface UIAlertView (V5Blocks)
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)didPresentAlertView:(id)arg1;
@property(copy, nonatomic) CDUnknownBlockType clickedButtonBlock;
@property(copy, nonatomic) CDUnknownBlockType didPresentBlock;
- (id)originalDelegate;
- (void)checkDelegate;
@end

