//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIButton.h>

@interface UIButton (BFKit)
+ (id)initWithFrame:(struct CGRect)arg1 image:(id)arg2 highlightedImage:(id)arg3;
+ (id)initWithFrame:(struct CGRect)arg1 image:(id)arg2;
+ (id)initWithFrame:(struct CGRect)arg1 color:(id)arg2 highlightedColor:(id)arg3;
+ (id)initWithFrame:(struct CGRect)arg1 color:(id)arg2;
+ (id)initWithFrame:(struct CGRect)arg1 title:(id)arg2 color:(id)arg3 highlightedColor:(id)arg4;
+ (id)initWithFrame:(struct CGRect)arg1 title:(id)arg2 color:(id)arg3;
+ (id)initWithFrame:(struct CGRect)arg1 title:(id)arg2 backgroundImage:(id)arg3 highlightedBackgroundImage:(id)arg4;
+ (id)initWithFrame:(struct CGRect)arg1 title:(id)arg2 backgroundImage:(id)arg3;
+ (id)initWithFrame:(struct CGRect)arg1 title:(id)arg2;
+ (id)initWithFrame:(struct CGRect)arg1;
- (void)setTitleColor:(id)arg1 highlightedColor:(id)arg2;
- (void)setTitleColor:(id)arg1;
- (void)setTitleFont:(long long)arg1 size:(double)arg2;
@end

