//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIColor.h>

@interface UIColor (BFKit)
+ (void)red:(double)arg1 green:(double)arg2 blue:(double)arg3 toHue:(double *)arg4 saturation:(double *)arg5 brightness:(double *)arg6;
+ (id)colorWithColor:(id)arg1 alpha:(float)arg2;
+ (id)randomColor;
+ (id)colorForColorString:(id)arg1;
+ (id)colorWithHex:(unsigned int)arg1 alpha:(float)arg2;
+ (id)colorWithHex:(unsigned int)arg1;
+ (double)colorComponentFrom:(id)arg1 start:(unsigned long long)arg2 length:(unsigned long long)arg3;
+ (id)colorWithHexString:(id)arg1;
+ (id)hexString:(id)arg1;
+ (id)hex:(id)arg1;
- (_Bool)red:(double *)arg1 green:(double *)arg2 blue:(double *)arg3 alpha:(double *)arg4;
- (_Bool)hue:(double *)arg1 saturation:(double *)arg2 brightness:(double *)arg3 alpha:(double *)arg4;
- (id)complementaryColor;
- (id)contrastingColor;
@property(readonly, nonatomic) double luminance;
@property(readonly, nonatomic) double alpha;
@property(readonly, nonatomic) double brightness;
@property(readonly, nonatomic) double saturation;
@property(readonly, nonatomic) double hue;
@property(readonly, nonatomic) double white;
@property(readonly, nonatomic) double blue;
@property(readonly, nonatomic) double green;
@property(readonly, nonatomic) double red;
- (_Bool)canProvideRGBComponents;
@end

