//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIDevice.h>

@interface UIDevice (BFKit)
+ (void)updateUniqueIdentifier:(id)arg1 block:(CDUnknownBlockType)arg2;
+ (id)uniqueIdentifier;
+ (id)macAddress;
+ (id)freeDiskSpace;
+ (id)totalDiskSpace;
+ (unsigned long long)userMemory;
+ (unsigned long long)totalMemory;
+ (unsigned long long)cpuNumber;
+ (unsigned long long)ramSize;
+ (unsigned long long)busFrequency;
+ (unsigned long long)cpuFrequency;
+ (unsigned long long)getSysInfo:(unsigned int)arg1;
+ (long long)iOSVersion;
+ (_Bool)isRetinaHD;
+ (_Bool)isRetina;
+ (_Bool)isSimulator;
+ (_Bool)isAppleWatch;
+ (_Bool)isAppleTV;
+ (_Bool)isiPod;
+ (_Bool)isiPhone;
+ (_Bool)isiPad;
+ (id)devicePlatformString;
+ (id)devicePlatform;
@end

