//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIFont.h>

@interface UIFont (BFKit)
+ (id)fontForFontName:(long long)arg1 size:(double)arg2;
+ (id)fontsNameForFamilyName:(long long)arg1;
+ (id)allFamilyAndFonts;
+ (void)setBoldFont:(id)arg1;
+ (id)boldFont;
+ (void)setRegularFont:(id)arg1;
+ (id)regularFont;
+ (void)setLightFont:(id)arg1;
+ (id)lightFont;
@end

