//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UILabel.h>

@interface UILabel (BFKit)
+ (id)initWithFrame:(struct CGRect)arg1 text:(id)arg2 font:(long long)arg3 size:(double)arg4 color:(id)arg5 alignment:(long long)arg6 lines:(long long)arg7 shadowColor:(id)arg8;
+ (id)initWithFrame:(struct CGRect)arg1 text:(id)arg2 font:(long long)arg3 size:(double)arg4 color:(id)arg5 alignment:(long long)arg6 lines:(long long)arg7;
- (void)setFont:(id)arg1 fromIndex:(long long)arg2 toIndex:(long long)arg3;
- (double)calculatedHeight;
@end

