//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UILabel.h>

@interface UILabel (Ext)
+ (id)instanceWithFrame:(struct CGRect)arg1 text:(id)arg2 textColor:(id)arg3 font:(id)arg4;
- (struct CGSize)sizeWithSize:(struct CGSize)arg1 withFont:(id)arg2;
- (struct CGSize)sizeWithSize:(struct CGSize)arg1;
- (void)setTextExt:(id)arg1;
- (struct CGSize)sizeUtilForTitle:(id)arg1;
- (void)setlineH:(double)arg1;
- (void)changeFont:(id)arg1;
- (void)setTextWithImageStr:(id)arg1;
- (void)setText:(id)arg1 hColor:(id)arg2;
- (void)deletelineText:(id)arg1 hColor:(id)arg2;
- (void)underlineText:(id)arg1 hColor:(id)arg2;
- (void)hightlightText:(id)arg1 hColor:(id)arg2 hFont:(id)arg3;
- (void)hightlightText:(id)arg1 hColor:(id)arg2;
@end

