//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIScrollView.h>

@interface UIScrollView (BFKit)
+ (id)initWithFrame:(struct CGRect)arg1 contentSize:(struct CGSize)arg2 clipsToBounds:(_Bool)arg3 pagingEnabled:(_Bool)arg4 showScrollIndicators:(_Bool)arg5 delegate:(id)arg6;
@end

