//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIScrollView.h>

@interface UIScrollView (ty_swizzle)
+ (_Bool)ty_swizzleMethodWithOrignalSel:(SEL)arg1 replacementSel:(SEL)arg2;
+ (void)load;
- (void)ty_setContentSize:(struct CGSize)arg1;
@property(nonatomic) double minContentSizeHeight;
@end

