//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableView.h>

@interface UITableView (BFKit)
+ (id)initWithFrame:(struct CGRect)arg1 style:(long long)arg2 cellSeparatorStyle:(long long)arg3 separatorInset:(struct UIEdgeInsets)arg4 dataSource:(id)arg5 delegate:(id)arg6;
- (id)getPreviousIndexPath:(unsigned long long)arg1 forSection:(unsigned long long)arg2;
- (id)getNextIndexPath:(unsigned long long)arg1 forSection:(unsigned long long)arg2;
- (id)getIndexPathsForSection:(unsigned long long)arg1;
@end

