//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITextField.h>

@interface UITextField (BFKit)
+ (id)initWithFrame:(struct CGRect)arg1 placeholder:(id)arg2 color:(id)arg3 font:(long long)arg4 size:(float)arg5 returnType:(long long)arg6 keyboardType:(long long)arg7 secure:(_Bool)arg8 borderStyle:(long long)arg9 autoCapitalization:(long long)arg10 keyboardAppearance:(long long)arg11 enablesReturnKeyAutomatically:(_Bool)arg12 clearButtonMode:(long long)arg13 autoCorrectionType:(long long)arg14 delegate:(id)arg15;
@end

