//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITextView.h>

@interface UITextView (BFKit)
+ (id)initWithFrame:(struct CGRect)arg1 text:(id)arg2 color:(id)arg3 font:(long long)arg4 size:(float)arg5 alignment:(long long)arg6 dataDetectorTypes:(unsigned long long)arg7 editable:(_Bool)arg8 selectable:(_Bool)arg9 returnType:(long long)arg10 keyboardType:(long long)arg11 secure:(_Bool)arg12 autoCapitalization:(long long)arg13 keyboardAppearance:(long long)arg14 enablesReturnKeyAutomatically:(_Bool)arg15 autoCorrectionType:(long long)arg16 delegate:(id)arg17;
@end

