//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@interface UIViewController (OneLibrary)
- (id)_formatLogWithHint:(id)arg1;
- (id)_addFlagString:(id)arg1 forLog:(id)arg2;
- (id)_prefixString;
- (id)_outputDateString;
- (void)_printLogWithHint:(id)arg1 withFlag:(id)arg2;
- (void)ol_deallocLog;
- (void)ol_leftLog;
- (void)ol_enteredLog;
@end

