//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface UIView (EasyUsing)
- (CDUnknownBlockType)ol_handler;
- (void)setOl_handler:(CDUnknownBlockType)arg1;
- (void)__handlerTapAction:(id)arg1;
- (void)ol_tapWithHandler:(CDUnknownBlockType)arg1;
- (id)ol_tapWithTarget:(id)arg1 action:(SEL)arg2;
- (void)ol_limitUserInteractionEnabledWithTimeInterval:(double)arg1;
- (void)ol_limitUserInteractionEnabled;
- (void)ol_eachSubviews:(CDUnknownBlockType)arg1;
- (void)ol_removeAllSubviews;
- (void)setOl_contentImage:(id)arg1;
- (id)ol_contentImage;
- (id)ol_snapshot;
- (id)ol_viewController;
@end

