//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface UIView (BFKit)
+ (id)initWithFrame:(struct CGRect)arg1 backgroundColor:(id)arg2;
- (void)removeAllSubviews;
- (id)saveScreenshot;
- (id)screenshot;
- (void)translateAroundTheView:(id)arg1 duration:(double)arg2 direction:(long long)arg3 repeat:(_Bool)arg4 startFromEdge:(_Bool)arg5;
- (void)flipWithDuration:(double)arg1 direction:(long long)arg2;
- (void)applyMotionEffects;
- (void)heartbeatViewWithDuration:(double)arg1;
- (void)pulseViewWithTime:(double)arg1;
- (void)pulseViewWithDuration:(double)arg1;
- (void)shakeView;
- (void)createGradientWithColors:(id)arg1 direction:(long long)arg2;
- (void)createCornerRadiusShadowWithCornerRadius:(double)arg1 offset:(struct CGSize)arg2 opacity:(double)arg3 radius:(double)arg4;
- (void)createRectShadowWithOffset:(struct CGSize)arg1 opacity:(double)arg2 radius:(double)arg3;
- (void)setCornerRadius:(double)arg1;
- (void)removeShadow;
- (void)removeBorders;
- (void)createBordersWithColor:(id)arg1 withCornerRadius:(double)arg2 andWidth:(double)arg3;
@end

