//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@interface UIViewController (Content)
+ (void)scanningQRCode:(id)arg1 webView:(id)arg2;
+ (void)openview:(id)arg1;
+ (void)onDislikeModel:(id)arg1 reason:(id)arg2 from:(long long)arg3;
+ (void)onDislikeModelView:(id)arg1;
+ (void)prot_call_dislike:(id)arg1 from:(long long)arg2;
+ (void)prot_call_like:(id)arg1 fromModel:(id)arg2 callback:(id)arg3 webView:(id)arg4;
+ (void)attAction:(id)arg1 callback:(id)arg2 model:(id)arg3 fromModel:(id)arg4;
- (void)store:(id)arg1 block:(CDUnknownBlockType)arg2;
@end

