//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface UIView (ViewGeometry)
- (id)viewWithTag_safe:(unsigned long long)arg1;
- (void)addGradientLayer;
- (id)appendLine:(int)arg1 borderWidth:(double)arg2 indent:(double)arg3 cor:(id)arg4;
- (id)appendLine:(int)arg1 indent:(double)arg2 cor:(id)arg3;
- (id)appendLine:(int)arg1 borderWidth:(double)arg2;
- (id)appendLine:(int)arg1;
- (void)setAppendLineHidden:(_Bool)arg1 flag:(int)arg2;
- (void)addClick:(SEL)arg1 toTarget:(id)arg2;
- (void)fitInSize:(struct CGSize)arg1;
- (void)scaleBy:(double)arg1;
- (void)moveBy:(struct CGPoint)arg1;
- (void)setRight:(double)arg1;
- (double)right;
- (void)setBottom:(double)arg1;
- (double)bottom;
- (void)setLeft:(double)arg1;
- (double)left;
- (void)setTop:(double)arg1;
- (double)top;
- (void)setWidth:(double)arg1;
- (double)width;
- (void)setHeight:(double)arg1;
- (double)height;
- (struct CGPoint)topRight;
- (struct CGPoint)bottomLeft;
- (struct CGPoint)bottomRight;
- (void)setSize:(struct CGSize)arg1;
- (struct CGSize)size;
- (void)setOrigin:(struct CGPoint)arg1;
- (struct CGPoint)origin;
@end

