//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "UMPBaseModel.h"

@class NSString;

@interface UMPCustomButtonModel : UMPBaseModel
{
    NSString *_action_type;
    NSString *_url;
    NSString *_activity;
}

@property(copy, nonatomic) NSString *activity; // @synthesize activity=_activity;
@property(copy, nonatomic) NSString *url; // @synthesize url=_url;
@property(copy, nonatomic) NSString *action_type; // @synthesize action_type=_action_type;
- (void).cxx_destruct;
- (id)initWithDict:(id)arg1;

@end

