//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSDictionary, NSMutableArray, NSMutableDictionary, NSString, UIViewController, UMPADModel, UMPCardCloseButton;
@protocol OS_dispatch_queue;

@interface UMPCardMessage : NSObject
{
    _Bool _debugMode;
    _Bool _closebuttondisplaymode;
    NSObject<OS_dispatch_queue> *_umessageworkQueue;
    NSMutableDictionary *_cardsetting;
    UMPCardCloseButton *_closeBtn;
    NSDictionary *_cardDictionary;
    NSString *_file;
    UIViewController *_webViewController;
    NSMutableArray *_initlabels;
    NSMutableDictionary *_initmodels;
    NSMutableArray *_displayviews;
    UMPADModel *_curModel;
    NSString *_curLabel;
}

+ (void)setWebViewController:(id)arg1;
+ (_Bool)debugMode;
+ (void)setUMCustomCardMessageCloseButtonDisplayMode:(_Bool)arg1;
+ (void)setDebugMode:(_Bool)arg1;
+ (void)initPlainTextCardMessageWithTitleFont:(id)arg1 ContentFont:(id)arg2 buttonFont:(id)arg3 Label:(id)arg4;
+ (void)initCustomCardMessageWithPortraitSize:(struct CGSize)arg1 LandscapeSize:(struct CGSize)arg2 CloseBtn:(id)arg3 Label:(id)arg4 umCustomCloseButtonDisplayMode:(_Bool)arg5;
+ (void)initCardMessageWithLabel:(id)arg1;
+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)sharedInstance;
@property(copy, nonatomic) NSString *curLabel; // @synthesize curLabel=_curLabel;
@property(retain, nonatomic) UMPADModel *curModel; // @synthesize curModel=_curModel;
@property(retain, nonatomic) NSMutableArray *displayviews; // @synthesize displayviews=_displayviews;
@property(retain, nonatomic) NSMutableDictionary *initmodels; // @synthesize initmodels=_initmodels;
@property(retain, nonatomic) NSMutableArray *initlabels; // @synthesize initlabels=_initlabels;
@property(retain, nonatomic) UIViewController *webViewController; // @synthesize webViewController=_webViewController;
@property(copy, nonatomic) NSString *file; // @synthesize file=_file;
@property(retain, nonatomic) NSDictionary *cardDictionary; // @synthesize cardDictionary=_cardDictionary;
@property(retain, nonatomic) UMPCardCloseButton *closeBtn; // @synthesize closeBtn=_closeBtn;
@property(retain, nonatomic) NSMutableDictionary *cardsetting; // @synthesize cardsetting=_cardsetting;
@property(nonatomic) _Bool closebuttondisplaymode; // @synthesize closebuttondisplaymode=_closebuttondisplaymode;
@property(nonatomic) _Bool debugMode; // @synthesize debugMode=_debugMode;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *umessageworkQueue; // @synthesize umessageworkQueue=_umessageworkQueue;
- (void).cxx_destruct;
- (void)statusBarOrientationChange;
- (void)displayNextView;
- (void)openUrlWithUrl:(id)arg1;
- (void)plainbuttonclick;
- (void)custombuttonclick;
- (void)remove;
- (void)imagetap;
- (id)dealWithDisplayStatisticsWithModel:(id)arg1;
- (void)dealWithDisplayStatWithResult:(id)arg1 Model:(id)arg2;
- (void)initPlainTextWithModel:(id)arg1 Label:(id)arg2 Array:(id)arg3;
- (void)initCustomCardViewWithModel:(id)arg1 Image:(id)arg2 Label:(id)arg3 Array:(id)arg4;
- (void)initCardViewWithModel:(id)arg1 Image:(id)arg2 Label:(id)arg3 Array:(id)arg4;
- (void)displayCardADWithModel:(id)arg1 Label:(id)arg2;
- (void)dealwithLogicWithLabel:(id)arg1;
- (void)dealWithLogicWhenRequestFailWithLabel:(id)arg1;
- (int)dealwithShowtimesWithModel:(id)arg1;
- (void)saveNewMessageDataWithresponseObject:(id)arg1 Label:(id)arg2 WithModel:(id)arg3;
- (void)initWithCardMessageWithLabel:(id)arg1;
- (void)createDB;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

