//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIButton.h>

@class UIColor;

@interface UMPCardCloseButton : UIButton
{
    UIColor *_closeButtonTintColor;
}

+ (id)buttonWithType:(long long)arg1;
@property(retain, nonatomic) UIColor *closeButtonTintColor; // @synthesize closeButtonTintColor=_closeButtonTintColor;
- (void).cxx_destruct;
- (_Bool)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)drawRect:(struct CGRect)arg1;

@end

