//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString, UMHashArray;
@protocol OS_dispatch_queue;

@interface UMPCoreData : NSObject
{
    UMHashArray *_msgCache;
    NSObject<OS_dispatch_queue> *_msgCacheQueue;
    long long _reportPolicy;
    long long _tagPolicy;
}

+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)sharedInstance;
@property(nonatomic) long long tagPolicy; // @synthesize tagPolicy=_tagPolicy;
@property(nonatomic) long long reportPolicy; // @synthesize reportPolicy=_reportPolicy;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *msgCacheQueue; // @synthesize msgCacheQueue=_msgCacheQueue;
@property(retain, nonatomic) UMHashArray *msgCache; // @synthesize msgCache=_msgCache;
- (void).cxx_destruct;
- (void)clearAllData;
- (void)clearCacheMsgs;
- (void)clearLaunchSendedDate;
- (void)clearRegisterSendedDate;
- (void)updateLaunchSendedDate;
- (void)updateRegisterSendedDate;
- (_Bool)launchDailySended;
- (_Bool)registerDailySended;
- (id)cacheMsgsArrayExceptMsgId:(id)arg1;
- (void)clearToken;
@property(copy, nonatomic) NSString *notificationstate;
- (id)token;
- (void)setToken:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

