//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface UMPDBManager : NSObject
{
}

+ (id)shareDataBaseHandle;
- (id)selectMessagesWithSQL:(id)arg1;
- (id)selectLabelsWithTableName:(id)arg1 Label:(id)arg2;
- (id)selectAllWithTableName:(id)arg1;
- (id)selectNewlyWithTableName:(id)arg1;
- (id)selectObjectWithTableName:(id)arg1 MsgID:(id)arg2;
- (void)updateSQL:(id)arg1;
- (void)closeDB;
- (void)open:(id)arg1;

@end

