//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "NSCacheDelegate-Protocol.h"

@class NSDictionary, NSString, UIButton, UIImageView, UIViewController, UIWindow, UMPADModel, UMPADViewController;
@protocol OS_dispatch_source;

@interface UMPLaunchMessage : NSObject <NSCacheDelegate>
{
    _Bool _debugMode;
    long long _noDataDuration;
    UMPADViewController *_launchVc;
    UIImageView *_launchView;
    UIImageView *_messageImgView;
    UIImageView *_bottomImgView;
    UIButton *_skipButton;
    NSObject<OS_dispatch_source> *_noDataTimer;
    NSObject<OS_dispatch_source> *_skipButtonTimer;
    long long _duration;
    UMPADModel *_launchModel;
    NSDictionary *_launchDictionary;
    NSString *_skipDisplayName;
    long long _postDurantion;
    double _startT;
    UIWindow *_finishDisplayWindow;
    UIViewController *_finishViewController;
    UIWindow *_adwindow;
    NSString *_file;
    UIViewController *_webViewController;
    struct CGRect _messageFrame;
}

+ (void)initLaunchMessage;
+ (void)setWebViewController:(id)arg1;
+ (_Bool)debugMode;
+ (void)setDebugMode:(_Bool)arg1;
+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)sharedInstance;
@property(retain, nonatomic) UIViewController *webViewController; // @synthesize webViewController=_webViewController;
@property(copy, nonatomic) NSString *file; // @synthesize file=_file;
@property(retain, nonatomic) UIWindow *adwindow; // @synthesize adwindow=_adwindow;
@property(retain, nonatomic) UIViewController *finishViewController; // @synthesize finishViewController=_finishViewController;
@property(retain, nonatomic) UIWindow *finishDisplayWindow; // @synthesize finishDisplayWindow=_finishDisplayWindow;
@property(nonatomic) double startT; // @synthesize startT=_startT;
@property(nonatomic) _Bool debugMode; // @synthesize debugMode=_debugMode;
@property(nonatomic) long long postDurantion; // @synthesize postDurantion=_postDurantion;
@property(copy, nonatomic) NSString *skipDisplayName; // @synthesize skipDisplayName=_skipDisplayName;
@property(retain, nonatomic) NSDictionary *launchDictionary; // @synthesize launchDictionary=_launchDictionary;
@property(retain, nonatomic) UMPADModel *launchModel; // @synthesize launchModel=_launchModel;
@property(nonatomic) long long duration; // @synthesize duration=_duration;
@property(retain, nonatomic) NSObject<OS_dispatch_source> *skipButtonTimer; // @synthesize skipButtonTimer=_skipButtonTimer;
@property(retain, nonatomic) NSObject<OS_dispatch_source> *noDataTimer; // @synthesize noDataTimer=_noDataTimer;
@property(nonatomic) struct CGRect messageFrame; // @synthesize messageFrame=_messageFrame;
@property(retain, nonatomic) UIButton *skipButton; // @synthesize skipButton=_skipButton;
@property(retain, nonatomic) UIImageView *bottomImgView; // @synthesize bottomImgView=_bottomImgView;
@property(retain, nonatomic) UIImageView *messageImgView; // @synthesize messageImgView=_messageImgView;
@property(retain, nonatomic) UIImageView *launchView; // @synthesize launchView=_launchView;
@property(retain, nonatomic) UMPADViewController *launchVc; // @synthesize launchVc=_launchVc;
@property(nonatomic) long long noDataDuration; // @synthesize noDataDuration=_noDataDuration;
- (void).cxx_destruct;
- (id)dealWithDisplayStatistics;
- (void)tapBottomAction:(id)arg1;
- (void)openUrlWithUrl:(id)arg1;
- (void)tapAction:(id)arg1;
- (id)launchImageWithType:(id)arg1;
- (id)getLaunchImage;
- (void)remove;
- (void)btnclick;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)startSkipButtonTimer;
- (void)startNoDataDispath_tiemr;
- (void)setupAdImgViewAndSkipButton;
- (void)dealWithBottomStatWithResult:(id)arg1 image:(id)arg2;
- (void)displayBottom;
- (void)dealWithTopStatWithResult:(id)arg1 image:(id)arg2;
- (void)displayLaunchAD;
- (void)dealWithLogic;
- (void)removeCache;
- (int)dealwithShowtimes;
- (void)saveNewMessageDataWithresponseObject:(id)arg1;
- (void)initViewFrame;
- (void)dealWithLogicWhenRequestFail;
- (void)createDB;
- (void)initLaunchMessage;
- (id)copyWithZone:(struct _NSZone *)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

