//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "UMPBaseModel.h"

@class NSNumber, NSString, UMPActionModel, UMPCustomButtonModel, UMPPlainTextModel;

@interface UMPMsgInfoModel : UMPBaseModel
{
    NSNumber *_display_button;
    NSString *_display_name;
    NSNumber *_display_time;
    NSString *_skip_backgroundcolor;
    NSString *_skip_fontcolor;
    UMPActionModel *_image;
    UMPActionModel *_bottom_image;
    UMPCustomButtonModel *_custom_button;
    UMPPlainTextModel *_plain_text;
}

@property(retain, nonatomic) UMPPlainTextModel *plain_text; // @synthesize plain_text=_plain_text;
@property(retain, nonatomic) UMPCustomButtonModel *custom_button; // @synthesize custom_button=_custom_button;
@property(retain, nonatomic) UMPActionModel *bottom_image; // @synthesize bottom_image=_bottom_image;
@property(retain, nonatomic) UMPActionModel *image; // @synthesize image=_image;
@property(copy, nonatomic) NSString *skip_fontcolor; // @synthesize skip_fontcolor=_skip_fontcolor;
@property(copy, nonatomic) NSString *skip_backgroundcolor; // @synthesize skip_backgroundcolor=_skip_backgroundcolor;
@property(retain, nonatomic) NSNumber *display_time; // @synthesize display_time=_display_time;
@property(copy, nonatomic) NSString *display_name; // @synthesize display_name=_display_name;
@property(retain, nonatomic) NSNumber *display_button; // @synthesize display_button=_display_button;
- (void).cxx_destruct;
- (id)initWithDict:(id)arg1;

@end

