//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface UMPTools : NSObject
{
}

+ (_Bool)isReadyReportWithLastPostTimeKey:(id)arg1 IntervalKey:(id)arg2;
+ (id)getTimeIntervalS;
+ (void)handleResponeString:(id)arg1 error:(id)arg2 handle:(CDUnknownBlockType)arg3;
+ (id)requestWithUrl:(id)arg1 parameters:(id)arg2;
+ (id)errorWithType:(long long)arg1 reason:(id)arg2;
+ (void)resetAllData;
+ (id)handleWeightedTags:(id)arg1;
+ (id)getTagsWithString:(id)arg1;
+ (id)getStringWithWeightedTags:(id)arg1;
+ (id)getStringWithTags:(id)arg1;
+ (id)sdkVersionString;
+ (id)tokenStringWithData:(id)arg1;
+ (id)getStringWithWeightedTag:(id)arg1;
+ (id)getStringWithAliasType:(id)arg1;
+ (id)getStringWithAlias:(id)arg1;
+ (id)checkLengthWithString:(id)arg1;
+ (id)handleStringWithType:(id)arg1 String:(id)arg2 Limit:(long long)arg3;

@end

