//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSURLRequest;

@interface URLSessionHelper : NSObject
{
    NSURLRequest *_req;
    CDUnknownBlockType _completionBlock;
    CDUnknownBlockType _successBlock;
    CDUnknownBlockType _failureBlock;
}

+ (id)configure:(CDUnknownBlockType)arg1;
@property(copy, nonatomic) CDUnknownBlockType failureBlock; // @synthesize failureBlock=_failureBlock;
@property(copy, nonatomic) CDUnknownBlockType successBlock; // @synthesize successBlock=_successBlock;
@property(copy, nonatomic) CDUnknownBlockType completionBlock; // @synthesize completionBlock=_completionBlock;
@property(retain, nonatomic) NSURLRequest *req; // @synthesize req=_req;
- (void).cxx_destruct;
@property(readonly, copy, nonatomic) CDUnknownBlockType failure;
@property(readonly, copy, nonatomic) CDUnknownBlockType success;
@property(readonly, copy, nonatomic) CDUnknownBlockType completion;
@property(readonly, copy, nonatomic) CDUnknownBlockType requestURL;
@property(readonly, copy, nonatomic) CDUnknownBlockType request;
- (id)init;

@end

