//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "LCBaseModel.h"

@class NSMutableArray, NSMutableDictionary;

@interface UserInfoConfigModel : LCBaseModel
{
    NSMutableArray *_career_list;
    NSMutableArray *_edu_list;
    NSMutableArray *_sex_list;
    NSMutableDictionary *_career_info_list;
    NSMutableArray *_all_career_info_list;
}

@property(retain, nonatomic) NSMutableArray *all_career_info_list; // @synthesize all_career_info_list=_all_career_info_list;
@property(retain, nonatomic) NSMutableDictionary *career_info_list; // @synthesize career_info_list=_career_info_list;
@property(retain, nonatomic) NSMutableArray *sex_list; // @synthesize sex_list=_sex_list;
@property(retain, nonatomic) NSMutableArray *edu_list; // @synthesize edu_list=_edu_list;
@property(retain, nonatomic) NSMutableArray *career_list; // @synthesize career_list=_career_list;
- (void).cxx_destruct;
- (id)initWithAttribute:(id)arg1;

@end

