//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "V5SRWebSocketDelegate-Protocol.h"

@class NSArray, NSString, NSUserDefaults, V5Config, V5DBHelper, V5Message, V5SRWebSocket;
@protocol V5MessageDelegate;

@interface V5ClientAgent : NSObject <V5SRWebSocketDelegate>
{
    V5Message *_openingAnswer;
    long long _status;
    NSArray *_magic;
    _Bool _siteInfo;
    _Bool _connected;
    _Bool _photoLibrary;
    V5Config *_config;
    id <V5MessageDelegate> _messageDelegate;
    V5SRWebSocket *_webSocket;
    unsigned long long _photoLibraryInterfaceOrientations;
    NSUserDefaults *_userData;
    V5DBHelper *_dbHelper;
    NSString *_wxytUrl;
    NSString *_wxytAuth;
}

+ (void)clearMediaCache;
+ (id)createChatViewController;
+ (void)doInitAuthWithSite:(id)arg1 account:(id)arg2 appId:(id)arg3 exceptionBlock:(CDUnknownBlockType)arg4;
+ (void)initWithSiteId:(id)arg1 account:(id)arg2 appId:(id)arg3 exceptionBlock:(CDUnknownBlockType)arg4;
+ (void)initWithSiteId:(id)arg1 appId:(id)arg2 exceptionBlock:(CDUnknownBlockType)arg3;
+ (id)version;
+ (void)destroyDealloc;
+ (id)copyWithZone:(struct _NSZone *)arg1;
+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)shareClient;
@property(retain, nonatomic) NSString *wxytAuth; // @synthesize wxytAuth=_wxytAuth;
@property(retain, nonatomic) NSString *wxytUrl; // @synthesize wxytUrl=_wxytUrl;
@property(retain, nonatomic) V5DBHelper *dbHelper; // @synthesize dbHelper=_dbHelper;
@property(retain, nonatomic) NSUserDefaults *userData; // @synthesize userData=_userData;
@property(nonatomic) unsigned long long photoLibraryInterfaceOrientations; // @synthesize photoLibraryInterfaceOrientations=_photoLibraryInterfaceOrientations;
@property(nonatomic, getter=isPhotoLibrary) _Bool photoLibrary; // @synthesize photoLibrary=_photoLibrary;
@property(nonatomic, getter=isConnected) _Bool connected; // @synthesize connected=_connected;
@property(retain, nonatomic) V5SRWebSocket *webSocket; // @synthesize webSocket=_webSocket;
@property(nonatomic) __weak id <V5MessageDelegate> messageDelegate; // @synthesize messageDelegate=_messageDelegate;
@property(retain, nonatomic) V5Config *config; // @synthesize config=_config;
- (void).cxx_destruct;
- (void)getOpeningMessageOfMode:(long long)arg1 withParam:(id)arg2;
- (void)sendPrologue:(id)arg1;
- (void)onApplicationWillEnterForeground;
- (void)onApplicationDidEnterBackground;
- (void)shouldClientOffline;
- (void)shouldClientOnline;
- (id)switchToArtificialService;
- (void)humanServiceOfGroupId:(long long)arg1 workerId:(long long)arg2;
- (void)sendMessage:(id)arg1 exceptionOfStatus:(long long)arg2 desc:(id)arg3;
- (void)clearMessagesCache;
- (void)getMessagesWithOffset:(long long)arg1 messageSize:(long long)arg2;
- (void)getCurrentMessagesWithOffset:(long long)arg1 messageSize:(long long)arg2;
- (void)getStatus;
- (void)sendMagicInfo:(id)arg1;
- (id)sendImageMessageWithImage:(id)arg1;
- (id)sendTextMessageWithContent:(id)arg1;
- (void)sendMessage:(id)arg1 withResult:(_Bool)arg2;
- (void)sendMessage:(id)arg1;
- (void)sendRawMessage:(id)arg1 withResult:(_Bool)arg2;
- (void)refresh;
- (void)checkConnect;
- (void)sendMessageString:(id)arg1;
- (void)addUserInfo:(id)arg1;
- (void)webSocket:(id)arg1 didReceivePong:(id)arg2;
- (void)webSocket:(id)arg1 didFailWithError:(id)arg2;
- (void)webSocket:(id)arg1 didCloseWithCode:(long long)arg2 reason:(id)arg3 wasClean:(_Bool)arg4;
- (void)webSocket:(id)arg1 didReceiveMessage:(id)arg2;
- (void)webSocketDidOpen:(id)arg1;
- (void)getSiteInfoCallback:(_Bool)arg1;
- (void)updateSiteInfo;
- (void)doAccountAuth;
- (void)startWebsocketWithDelegate:(id)arg1;
- (void)stopClient;
- (void)startClientWithDelegate:(id)arg1;
- (id)tableName;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

