//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSDictionary, NSString, NSUserDefaults;

@interface V5Config : NSObject
{
    _Bool _pushEnable;
    _Bool _autoSSL;
    NSString *_visitor;
    NSString *_uid;
    NSString *_openId;
    NSString *_deviceToken;
    NSString *_site;
    NSString *_account;
    NSString *_appId;
    long long _timestamp;
    long long _expires;
    NSString *_authorization;
    NSString *_robotName;
    NSString *_robotPhoto;
    NSString *_robotIntro;
    NSString *_workerIntro;
    NSString *_nickname;
    NSString *_avatar;
    long long _gender;
    long long _vip;
    NSDictionary *_userInfo;
    NSString *_workerPhoto;
    NSString *_workerName;
    long long _workerId;
    NSUserDefaults *_userData;
}

@property(nonatomic) NSUserDefaults *userData; // @synthesize userData=_userData;
@property(nonatomic) _Bool autoSSL; // @synthesize autoSSL=_autoSSL;
@property(nonatomic) long long workerId; // @synthesize workerId=_workerId;
@property(retain, nonatomic) NSString *workerName; // @synthesize workerName=_workerName;
@property(retain, nonatomic) NSString *workerPhoto; // @synthesize workerPhoto=_workerPhoto;
@property(nonatomic) _Bool pushEnable; // @synthesize pushEnable=_pushEnable;
@property(retain, nonatomic) NSDictionary *userInfo; // @synthesize userInfo=_userInfo;
@property(nonatomic) long long vip; // @synthesize vip=_vip;
@property(nonatomic) long long gender; // @synthesize gender=_gender;
@property(retain, nonatomic) NSString *avatar; // @synthesize avatar=_avatar;
@property(retain, nonatomic) NSString *nickname; // @synthesize nickname=_nickname;
- (void).cxx_destruct;
- (void)shouldUpdateUserInfo;
@property(retain, nonatomic) NSString *workerIntro; // @synthesize workerIntro=_workerIntro;
@property(retain, nonatomic) NSString *robotIntro; // @synthesize robotIntro=_robotIntro;
@property(retain, nonatomic) NSString *robotPhoto; // @synthesize robotPhoto=_robotPhoto;
@property(retain, nonatomic) NSString *robotName; // @synthesize robotName=_robotName;
@property(retain, nonatomic) NSString *authorization; // @synthesize authorization=_authorization;
@property(nonatomic) long long expires; // @synthesize expires=_expires;
@property(nonatomic) long long timestamp; // @synthesize timestamp=_timestamp;
@property(retain, nonatomic) NSString *appId; // @synthesize appId=_appId;
@property(retain, nonatomic) NSString *account; // @synthesize account=_account;
@property(retain, nonatomic) NSString *site; // @synthesize site=_site;
@property(retain, nonatomic) NSString *deviceToken; // @synthesize deviceToken=_deviceToken;
@property(readonly, nonatomic) NSString *visitor; // @synthesize visitor=_visitor;
@property(retain, nonatomic) NSString *openId; // @synthesize openId=_openId;
@property(retain, nonatomic) NSString *uid; // @synthesize uid=_uid;
- (void)dealloc;
- (id)initWithUserDefaults:(id)arg1;

@end

