//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString, V5FMDatabase;

@interface V5DBHelper : NSObject
{
    V5FMDatabase *db;
    NSString *tableName;
}

+ (_Bool)isDatabase:(id)arg1 hasTable:(id)arg2;
- (void).cxx_destruct;
- (void)setTableName:(id)arg1;
- (_Bool)clear;
- (id)datebasePathInDocumentDir:(id)arg1;
- (_Bool)hasMessageContent:(long long)arg1;
- (void)createTable:(id)arg1;
- (_Bool)queryMessages:(id)arg1 offset:(long long)arg2 size:(long long)arg3;
- (_Bool)insertMessage:(id)arg1 force:(_Bool)arg2;
- (_Bool)insertMessage:(id)arg1;
- (id)initWithDBName:(id)arg1 tableName:(id)arg2;

@end

