//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface V5ImageLoader : NSObject
{
}

+ (void)setButton:(id)arg1 withBackgroundImageURL:(id)arg2 forState:(unsigned long long)arg3 placeholderImage:(id)arg4 failureImage:(id)arg5 complete:(CDUnknownBlockType)arg6;
+ (void)setImageView:(id)arg1 withURL:(id)arg2 placeholderImage:(id)arg3 failureImage:(id)arg4 completed:(CDUnknownBlockType)arg5;
+ (void)setImageView:(id)arg1 withURL:(id)arg2 completed:(CDUnknownBlockType)arg3;
+ (void)setImageView:(id)arg1 withURL:(id)arg2 placeholderImage:(id)arg3 failureImage:(id)arg4;
+ (void)setImageView:(id)arg1 withURL:(id)arg2 placeholderImage:(id)arg3;
+ (void)setImageView:(id)arg1 withURL:(id)arg2;

@end

