//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface V5MessageManager : NSObject
{
}

+ (id)obtainControlMessageWithCode:(long long)arg1 argc:(long long)arg2 argv:(id)arg3;
+ (id)obtainImageMessageWithImage:(id)arg1;
+ (id)obtainImageMessageWithPicUrl:(id)arg1 mediaId:(id)arg2;
+ (id)obtainLocationMessageWithX:(double)arg1 y:(double)arg2 scale:(double)arg3 label:(id)arg4;
+ (id)obtainTextMessageWithContent:(id)arg1;
+ (id)receiveMessageFromJSON:(id)arg1;

@end

