//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, NSString, V5Message;

@protocol V5MessageDelegate <NSObject>
- (void)receiveJSONString:(NSString *)arg1;
- (void)receiveV5Message:(V5Message *)arg1;

@optional
- (void)servingStatusChange:(long long)arg1;
- (void)getMessagesResult:(NSArray *)arg1 offset:(long long)arg2 size:(long long)arg3 finish:(_Bool)arg4 expcetion:(long long)arg5;
- (void)sendMessageResult:(V5Message *)arg1 expcetion:(long long)arg2;
- (void)receiveExceptionStatus:(long long)arg1 desc:(NSString *)arg2;
- (void)disconnectWithCode:(long long)arg1 reason:(NSString *)arg2;
- (void)onConnectWithUnreadCount:(long long)arg1;
- (void)onConnect;
@end

