//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "V5MediaMessage.h"

@class NSString;

@interface V5MusicMessage : V5MediaMessage
{
    NSString *_title;
    NSString *_desc;
    NSString *_music_url;
    NSString *_hq_music_url;
    NSString *_thumb_id;
}

@property(retain, nonatomic) NSString *thumb_id; // @synthesize thumb_id=_thumb_id;
@property(retain, nonatomic) NSString *hq_music_url; // @synthesize hq_music_url=_hq_music_url;
@property(retain, nonatomic) NSString *music_url; // @synthesize music_url=_music_url;
@property(retain, nonatomic) NSString *desc; // @synthesize desc=_desc;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;
- (void)addPropertyToJSONObject:(id)arg1;
- (id)toJSONString;
- (void)parseMessageContent:(id)arg1;
- (id)initWithJSON:(id)arg1;
- (id)initWithTitle:(id)arg1 desc:(id)arg2 url:(id)arg3;
- (id)init;

@end

