//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "V5Message.h"

@class NSString;

@interface V5TextMessage : V5Message
{
    NSString *_content;
}

@property(retain, nonatomic) NSString *content; // @synthesize content=_content;
- (void).cxx_destruct;
- (id)toJSONString;
- (id)initWithJSON:(id)arg1;
- (id)initWithContent:(id)arg1;
- (id)init;

@end

