//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "LCBaseModel.h"

@interface videoPieChartModel : LCBaseModel
{
    _Bool _isContinuePlay;
    _Bool _readingTimeSwitch;
    float _amount;
    float _curr_task;
    float _next_task;
    float _totalReadTime;
    float _lastReadTime;
    float _nodeCount;
    float _nodeReadTime;
    float _articleTimeLimit;
    int _videoID;
}

+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)instance;
@property(nonatomic) int videoID; // @synthesize videoID=_videoID;
@property(nonatomic) float articleTimeLimit; // @synthesize articleTimeLimit=_articleTimeLimit;
@property(nonatomic) _Bool readingTimeSwitch; // @synthesize readingTimeSwitch=_readingTimeSwitch;
@property(nonatomic) _Bool isContinuePlay; // @synthesize isContinuePlay=_isContinuePlay;
@property(nonatomic) float nodeReadTime; // @synthesize nodeReadTime=_nodeReadTime;
@property(nonatomic) float nodeCount; // @synthesize nodeCount=_nodeCount;
@property(nonatomic) float lastReadTime; // @synthesize lastReadTime=_lastReadTime;
@property(nonatomic) float totalReadTime; // @synthesize totalReadTime=_totalReadTime;
@property(nonatomic) float next_task; // @synthesize next_task=_next_task;
@property(nonatomic) float curr_task; // @synthesize curr_task=_curr_task;
@property(nonatomic) float amount; // @synthesize amount=_amount;
- (void)updateDateWithVideoPieChartModel:(id)arg1;
- (id)initWithAttribute:(id)arg1;

@end

