//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TYSlidePageScrollViewController.h"

@class NSMutableDictionary, QKChannel, QKVideoNavView;

@interface VideosViewController : TYSlidePageScrollViewController
{
    QKVideoNavView *_videoNavView;
    _Bool _reset;
    _Bool _isSelectedScroll;
    QKChannel *_channel;
    NSMutableDictionary *_allControllers;
}

@property(retain, nonatomic) NSMutableDictionary *allControllers; // @synthesize allControllers=_allControllers;
@property(nonatomic) _Bool isSelectedScroll; // @synthesize isSelectedScroll=_isSelectedScroll;
@property(retain, nonatomic) QKChannel *channel; // @synthesize channel=_channel;
- (void).cxx_destruct;
- (void)slidePageScrollView:(id)arg1 horizenScrollViewDidEndDecelerating:(id)arg2;
- (void)slidePageScrollView:(id)arg1 horizenScrollViewWillBeginDragging:(id)arg2;
- (void)slidePageScrollView:(id)arg1 clickedPageTabBarAtIndex:(long long)arg2;
- (void)slidePageScrollView:(id)arg1 horizenScrollViewDoReloadPageIndex:(long long)arg2 force:(_Bool)arg3;
- (void)beginRefreshing;
- (void)search:(id)arg1;
- (void)notification_enter_foreground:(id)arg1;
- (void)resetCurrentChannel;
- (void)resetRecommendChannel;
- (void)recoverRequestVideoChannel;
- (id)videoChannels;
- (void)setChannelController:(id)arg1 reset:(_Bool)arg2;
- (void)resetChannels:(id)arg1;
- (id)getChannelController:(id)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;

@end

