//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSError;

@protocol VideoPlayerControllerDelegate <NSObject>

@optional
- (void)didChangeVideoPlayerState:(int)arg1;
- (void)didPlayNextVideoIsAutoPlay:(_Bool)arg1;
- (void)didPlayEndInThreeSeconds;
- (void)didPlayerError:(NSError *)arg1;
- (void)didPopRoot;
- (void)didPlayerClose;
- (void)didSmallScreenAction;
- (void)didFullScreenAction;
- (void)didPayerEnd;
- (void)didPayerStart;
- (void)billingReport;
@end

