//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class NSString, NSURL;
@protocol IJKMediaPlayback;

@interface VrMovieViewController : UIViewController
{
    _Bool _looping;
    _Bool _enableVideoToolBox;
    int _playerType;
    int _interactiveMode;
    int _displayMode;
    int _projectionMode;
    int _sourceType;
    int _seekWhenPrepared;
    long long _maxBufferSize;
    long long _scaleMode;
    NSURL *_url;
    id <IJKMediaPlayback> _player;
    long long _curPlayerState;
    long long _tarPlayerState;
    long long _curRenderState;
    NSString *_videoName;
}

@property(copy, nonatomic) NSString *videoName; // @synthesize videoName=_videoName;
@property(nonatomic) int seekWhenPrepared; // @synthesize seekWhenPrepared=_seekWhenPrepared;
@property(nonatomic) long long curRenderState; // @synthesize curRenderState=_curRenderState;
@property(nonatomic) long long tarPlayerState; // @synthesize tarPlayerState=_tarPlayerState;
@property(nonatomic) long long curPlayerState; // @synthesize curPlayerState=_curPlayerState;
@property(retain) id <IJKMediaPlayback> player; // @synthesize player=_player;
@property(retain) NSURL *url; // @synthesize url=_url;
@property(nonatomic) long long scaleMode; // @synthesize scaleMode=_scaleMode;
@property(nonatomic) _Bool enableVideoToolBox; // @synthesize enableVideoToolBox=_enableVideoToolBox;
@property(nonatomic) long long maxBufferSize; // @synthesize maxBufferSize=_maxBufferSize;
@property(nonatomic) _Bool looping; // @synthesize looping=_looping;
@property(nonatomic) int sourceType; // @synthesize sourceType=_sourceType;
@property(nonatomic) int projectionMode; // @synthesize projectionMode=_projectionMode;
@property(nonatomic) int displayMode; // @synthesize displayMode=_displayMode;
@property(nonatomic) int interactiveMode; // @synthesize interactiveMode=_interactiveMode;
@property(nonatomic) int playerType; // @synthesize playerType=_playerType;
- (void).cxx_destruct;
- (void)mediaPlayerError:(id)arg1;
- (void)mediaPlayerVideoSizeChange:(id)arg1;
- (void)mediaPlayerSeekLoadCost:(id)arg1;
- (void)mediaPlayerBufferingEnd:(id)arg1;
- (void)mediaPlayerBufferingStart:(id)arg1;
- (void)mediaPlayerBufferingUpdate:(id)arg1;
- (void)mediaPlayerDidSeekComplete:(id)arg1;
- (void)mediaPlayerFirstVideoFrameRendered:(id)arg1;
- (void)mediaIsPreparedToPlayDidChange:(id)arg1;
- (void)moviePlayBackDidFinish:(id)arg1;
- (void)removeVRLibNotificationObservers;
- (void)removeMediaPlayerNotificationObservers;
- (void)installMediaPlayerNotificationObservers;
- (void)handleError:(int)arg1 detailedErrorCode:(int)arg2;
- (id)getMethodName:(id)arg1;
- (void)printCommonLog:(id)arg1;
- (void)printCommonLog;
- (float)getVolume;
- (float)getAvgFramesPerSecond;
- (long long)getSeekLoadDuration;
- (long long)getTcpSpeed;
- (long long)getBitRate;
- (long long)getAsyncStatisticBufCapacity;
- (long long)getAsyncStatisticBufForwards;
- (long long)getAsyncStatisticBufBackwards;
- (long long)getAudioCachedPackets;
- (long long)getVideoCachedPackets;
- (long long)getAudioCachedBytes;
- (long long)getVideoCachedBytes;
- (long long)getAudioCachedDuration;
- (long long)getVideoCachedDuration;
- (float)getVideoDecodeFramesPerSecond;
- (float)getVideoOutputFramesPerSecond;
- (int)getVideoDecoder;
- (void)destroyRender;
- (void)pauseRender;
- (void)resumeRender;
- (_Bool)isPlaying;
- (void)unMute;
- (void)mute;
- (void)setVolume:(float)arg1;
- (void)seekTo:(double)arg1;
- (long long)getBufferingProgress;
- (long long)getCurrentPosition;
- (long long)getDuration;
- (void)destroyPlayer;
- (void)stopPlayer;
- (void)pausePlayer:(_Bool)arg1;
- (void)startPlayer;
- (_Bool)isPlayerIdle;
- (_Bool)isInPlaybackState;
- (void)destroy;
- (void)stop;
- (void)pauseWithBufferingOff;
- (void)pause;
- (void)start;
- (_Bool)isAllReady;
- (_Bool)isLooping;
- (void)setVideoUrl:(id)arg1;
- (void)initView;
- (void)createPlayer;
- (void)initPlayer;
- (void)enableHardwareAcc:(_Bool)arg1;
- (void)init2D;

@end

