//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UIWebViewDelegate-Protocol.h"

@class JavaScriptOC, NSString, UIWebView;

@interface WebBridgeAlertView : UIView <UIWebViewDelegate>
{
    float _maxAlertScale;
    JavaScriptOC *_javaScript;
    UIWebView *_alertWeb;
    CDUnknownBlockType _action;
    NSString *_webScale;
    NSString *_request_url;
    long long _cdn_ecount;
}

@property(nonatomic) float maxAlertScale; // @synthesize maxAlertScale=_maxAlertScale;
@property(nonatomic) long long cdn_ecount; // @synthesize cdn_ecount=_cdn_ecount;
@property(copy, nonatomic) NSString *request_url; // @synthesize request_url=_request_url;
@property(copy, nonatomic) NSString *webScale; // @synthesize webScale=_webScale;
@property(copy, nonatomic) CDUnknownBlockType action; // @synthesize action=_action;
@property(retain, nonatomic) UIWebView *alertWeb; // @synthesize alertWeb=_alertWeb;
@property(retain, nonatomic) JavaScriptOC *javaScript; // @synthesize javaScript=_javaScript;
- (void).cxx_destruct;
- (void)dealloc;
- (void)webView:(id)arg1 didFailLoadWithError:(id)arg2;
- (void)webViewDidFinishLoad:(id)arg1;
- (_Bool)webView:(id)arg1 shouldStartLoadWithRequest:(id)arg2 navigationType:(long long)arg3;
- (void)webView:(id)arg1 didCreateJavaScriptContext:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)show;
- (void)updateWebFrame:(id)arg1;
- (float)getMaxHeightScale;
- (void)loadWithHtmlUrl:(id)arg1 sizeScale:(id)arg2 actionBlock:(CDUnknownBlockType)arg3;
- (void)loadWithHtmlString:(id)arg1 sizeScale:(id)arg2 actionBlock:(CDUnknownBlockType)arg3;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

