//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class CMMotionManager;

@interface zzcFNbqQUZYIFgtL : NSObject
{
    CMMotionManager *_motionManager;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (id)otVdylNoVUGbYMLK:(id)arg1 qUoNiCKewptWRbJS:(_Bool)arg2;
- (id)EHXgQDwvOYtYRmGu:(id)arg1;
- (void)lKOIzSXatCdVDRPI:(id)arg1 withBlock:(CDUnknownBlockType)arg2;
- (id)init;

@end

